-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.atm_denoms
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    atm_id bigint NOT NULL,
    denom_id bigint NOT NULL,
    CONSTRAINT atm_denoms_pkey PRIMARY KEY (id),
    CONSTRAINT atm_denoms_atm_denom_uq UNIQUE (atm_id, denom_id)
);

CREATE TABLE IF NOT EXISTS public.atm_vendor_packages
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    atm_id bigint NOT NULL,
    vendor_package_id bigint NOT NULL,
    effective_start_date date NOT NULL,
    effective_end_date date,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT atm_vendor_packages_pkey PRIMARY KEY (id),
    CONSTRAINT atm_vendor_packages_atm_package_start_uq UNIQUE (atm_id, vendor_package_id, effective_start_date)
);

CREATE TABLE IF NOT EXISTS public.atms
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    terminal_id text COLLATE pg_catalog."default" NOT NULL,
    location_id bigint NOT NULL,
    machine_type text COLLATE pg_catalog."default" NOT NULL,
    brand text COLLATE pg_catalog."default" NOT NULL,
    model text COLLATE pg_catalog."default" NOT NULL,
    operation_hours text COLLATE pg_catalog."default" NOT NULL,
    deployment_type text COLLATE pg_catalog."default" NOT NULL,
    capacity_amount numeric(20, 2),
    low_threshold_amount numeric(20, 2),
    critical_threshold_amount numeric(20, 2),
    blacklisted boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT atms_pkey PRIMARY KEY (id),
    CONSTRAINT atms_terminal_id_uq UNIQUE (terminal_id)
);

CREATE TABLE IF NOT EXISTS public.currencies
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT currencies_pkey PRIMARY KEY (id),
    CONSTRAINT currencies_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.denoms
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    curr_id bigint NOT NULL,
    denom numeric(20, 2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT denoms_pkey PRIMARY KEY (id),
    CONSTRAINT denoms_curr_id_denom_uq UNIQUE (curr_id, denom)
);

CREATE TABLE IF NOT EXISTS public.dmaa_atm_forecast
(
    terminal_id text COLLATE pg_catalog."default" NOT NULL,
    dmaa_file_id bigint NOT NULL,
    periode_pred date NOT NULL,
    denom integer NOT NULL,
    amount_replenish bigint NOT NULL DEFAULT 0,
    amount_refund bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmaa_atm_forecast PRIMARY KEY (dmaa_file_id, terminal_id, periode_pred, denom)
);

CREATE TABLE IF NOT EXISTS public.dmaa_files
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    is_valid boolean NOT NULL DEFAULT true,
    file_date date,
    source_system text COLLATE pg_catalog."default",
    checksum text COLLATE pg_catalog."default",
    row_count integer,
    success_count integer,
    error_count integer,
    error_message text COLLATE pg_catalog."default",
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT dmaa_files_pkey PRIMARY KEY (id),
    CONSTRAINT uq_dmaa_files_checksum UNIQUE (checksum)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    region_id bigint NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    address_line1 text COLLATE pg_catalog."default" NOT NULL,
    address_line2 text COLLATE pg_catalog."default",
    rt text COLLATE pg_catalog."default",
    rw text COLLATE pg_catalog."default",
    kelurahan text COLLATE pg_catalog."default",
    kecamatan text COLLATE pg_catalog."default",
    city_or_regency text COLLATE pg_catalog."default" NOT NULL,
    province text COLLATE pg_catalog."default" NOT NULL,
    postal_code text COLLATE pg_catalog."default",
    country_code character(2) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.regions
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code text COLLATE pg_catalog."default" NOT NULL,
    region text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT regions_pkey PRIMARY KEY (id),
    CONSTRAINT uq_regions_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigserial NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_role_key UNIQUE (role)
);

COMMENT ON COLUMN public.roles.role
    IS 'ADMIN | ADMIN_PARAM | ATM-USER | ATM-SPV | BRANCH-USER | BRANCH-SPV | BRANCH-ATM-USER | BRANCH-ATM-SPV | VENDOR-USER';

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    role_id bigint NOT NULL,
    employee_id text COLLATE pg_catalog."default",
    username text COLLATE pg_catalog."default" NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    is_karyawan boolean NOT NULL,
    auth_source text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default",
    vendor_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_employee_id_key UNIQUE (employee_id),
    CONSTRAINT users_username_key UNIQUE (username)
);

COMMENT ON COLUMN public.users.employee_id
    IS 'Nullable for external/vendor users';

COMMENT ON COLUMN public.users.auth_source
    IS 'ldap | local';

COMMENT ON COLUMN public.users.password_hash
    IS 'Only for auth_source=local';

COMMENT ON COLUMN public.users.vendor_id
    IS 'Required for vendor/local users, null for internal LDAP users';

CREATE TABLE IF NOT EXISTS public.vendor_branches
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vendor_id bigint NOT NULL,
    branch_code text COLLATE pg_catalog."default" NOT NULL,
    branch_name text COLLATE pg_catalog."default" NOT NULL,
    location_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vendor_branches_pkey PRIMARY KEY (id),
    CONSTRAINT uq_vendor_branches_branch_code UNIQUE (branch_code)
);

CREATE TABLE IF NOT EXISTS public.vendor_packages
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vendor_branch_id bigint NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    priority_class text COLLATE pg_catalog."default" NOT NULL,
    price numeric(20, 2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vendor_packages_pkey PRIMARY KEY (id),
    CONSTRAINT vendor_packages_branch_code_uq UNIQUE (vendor_branch_id, code)
);

CREATE TABLE IF NOT EXISTS public.vendors
(
    id bigserial NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    contact_email text COLLATE pg_catalog."default",
    contact_phone text COLLATE pg_catalog."default",
    hq_address text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT vendors_pkey PRIMARY KEY (id),
    CONSTRAINT vendors_code_key UNIQUE (code)
);

ALTER TABLE IF EXISTS public.atm_denoms
    ADD CONSTRAINT fk_atm_denoms_atm FOREIGN KEY (atm_id)
    REFERENCES public.atms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS atm_denoms_atm_idx
    ON public.atm_denoms(atm_id);


ALTER TABLE IF EXISTS public.atm_denoms
    ADD CONSTRAINT fk_atm_denoms_denom FOREIGN KEY (denom_id)
    REFERENCES public.denoms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS atm_denoms_denom_idx
    ON public.atm_denoms(denom_id);


ALTER TABLE IF EXISTS public.atm_vendor_packages
    ADD CONSTRAINT fk_atm_vendor_packages_atm FOREIGN KEY (atm_id)
    REFERENCES public.atms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS atm_vendor_packages_atm_idx
    ON public.atm_vendor_packages(atm_id);


ALTER TABLE IF EXISTS public.atm_vendor_packages
    ADD CONSTRAINT fk_atm_vendor_packages_vendor_package FOREIGN KEY (vendor_package_id)
    REFERENCES public.vendor_packages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS atm_vendor_packages_vendor_package_idx
    ON public.atm_vendor_packages(vendor_package_id);


ALTER TABLE IF EXISTS public.atms
    ADD CONSTRAINT fk_atms_location FOREIGN KEY (location_id)
    REFERENCES public.locations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS atms_location_idx
    ON public.atms(location_id);


ALTER TABLE IF EXISTS public.denoms
    ADD CONSTRAINT denoms_currencies_fk FOREIGN KEY (curr_id)
    REFERENCES public.currencies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS denoms_curr_id_idx
    ON public.denoms(curr_id);


ALTER TABLE IF EXISTS public.dmaa_atm_forecast
    ADD CONSTRAINT fk_dmaa_atm_forecast_dmaa_file FOREIGN KEY (dmaa_file_id)
    REFERENCES public.dmaa_files (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.dmaa_atm_forecast
    ADD CONSTRAINT fk_dmaa_atm_forecast_terminal FOREIGN KEY (terminal_id)
    REFERENCES public.atms (terminal_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS dmaa_atm_forecast_terminal_id_idx
    ON public.dmaa_atm_forecast(terminal_id);


ALTER TABLE IF EXISTS public.locations
    ADD CONSTRAINT fk_locations_region FOREIGN KEY (region_id)
    REFERENCES public.regions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_fk FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS users_role_idx
    ON public.users(role_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_vendor_fk FOREIGN KEY (vendor_id)
    REFERENCES public.vendors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS users_vendor_idx
    ON public.users(vendor_id);


ALTER TABLE IF EXISTS public.vendor_branches
    ADD CONSTRAINT fk_vendor_branches_location FOREIGN KEY (location_id)
    REFERENCES public.locations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendor_branches
    ADD CONSTRAINT fk_vendor_branches_vendor FOREIGN KEY (vendor_id)
    REFERENCES public.vendors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendor_packages
    ADD CONSTRAINT fk_vendor_packages_vendor_branch FOREIGN KEY (vendor_branch_id)
    REFERENCES public.vendor_branches (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS vendor_packages_vendor_branch_idx
    ON public.vendor_packages(vendor_branch_id);

END;
