BEGIN;

CREATE TABLE IF NOT EXISTS currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT currencies_code_chk CHECK (char_length(code) = 3)
);

CREATE TABLE IF NOT EXISTS denoms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curr_id BIGINT NOT NULL,
    denom NUMERIC(20,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT denoms_currencies_fk
        FOREIGN KEY (curr_id) REFERENCES currencies(id),
    CONSTRAINT denoms_value_chk CHECK (denom > 0),
    CONSTRAINT denoms_curr_id_denom_uq UNIQUE (curr_id, denom)
);

CREATE INDEX IF NOT EXISTS denoms_curr_id_idx ON denoms(curr_id);

COMMIT;