-- vendor_branches seed generated from MASTER_ATM_ESQ source
-- assumptions:
-- 1) vendor_branches.branch_name comes from FLMVendorSubRegion
-- 2) vendor_branches.location_id is left NULL::bigint because source does not provide a reliable branch location master
-- 3) branch_code is generated deterministically per vendor as VENDORCODE_### sorted by branch_name
-- 4) vendor normalization applied: Bijak + BIJAK => BIJAK
BEGIN;

WITH seed_vendor_branches(vendor_code, branch_code, branch_name, location_id, is_active) AS (
    VALUES
    ('ABACUS', 'ABACUS_001', 'Abacus Bali', NULL::bigint, true),
    ('ABACUS', 'ABACUS_002', 'Abacus Bandung', NULL::bigint, true),
    ('ABACUS', 'ABACUS_003', 'Abacus Ciamis', NULL::bigint, true),
    ('ABACUS', 'ABACUS_004', 'Abacus Medan', NULL::bigint, true),
    ('ABACUS', 'ABACUS_005', 'Abacus Solo', NULL::bigint, true),
    ('ABACUS', 'ABACUS_006', 'Abacus Subang', NULL::bigint, true),
    ('ABACUS', 'ABACUS_007', 'Abacus Sukabumi', NULL::bigint, true),
    ('ABACUS', 'ABACUS_008', 'Abacus Yogyakarta', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_001', 'Advantage Balikpapan', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_002', 'Advantage Banjarmasin', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_003', 'Advantage Batam', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_004', 'Advantage Jambi', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_005', 'Advantage Kupang', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_006', 'Advantage Lampung', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_007', 'Advantage Manado', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_008', 'Advantage Mataram', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_009', 'Advantage Medan', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_010', 'Advantage Padang', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_011', 'Advantage Palembang', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_012', 'Advantage Pekanbaru', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_013', 'Advantage Pontianak', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_014', 'Advantage Purwokerto', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_015', 'Advantage Samarinda', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_016', 'Advantage Semarang', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_017', 'Advantage Serang', NULL::bigint, true),
    ('ADVANTAGE', 'ADVANTAGE_018', 'Advantage Tegal', NULL::bigint, true),
    ('BIJAK', 'BIJAK_001', 'Bijak Jakarta', NULL::bigint, true),
    ('ROH', 'ROH_001', 'Aceh - Bireun', NULL::bigint, true),
    ('ROH', 'ROH_002', 'Ambon - Sam Ratulangi', NULL::bigint, true),
    ('ROH', 'ROH_003', 'Bali - Dewi Sartika', NULL::bigint, true),
    ('ROH', 'ROH_004', 'Bali - Kuta Graha', NULL::bigint, true),
    ('ROH', 'ROH_005', 'Bali - Melati', NULL::bigint, true),
    ('ROH', 'ROH_006', 'Bali - Nusa Dua', NULL::bigint, true),
    ('ROH', 'ROH_007', 'Bali - Sanur', NULL::bigint, true),
    ('ROH', 'ROH_008', 'Bali - Thamrin', NULL::bigint, true),
    ('ROH', 'ROH_009', 'Bali - Ubud', NULL::bigint, true),
    ('ROH', 'ROH_010', 'Balikpapan - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_011', 'Balikpapan - MT Haryono', NULL::bigint, true),
    ('ROH', 'ROH_012', 'Balikpapan - Ruko Baru', NULL::bigint, true),
    ('ROH', 'ROH_013', 'Banda Aceh - Peunayong', NULL::bigint, true),
    ('ROH', 'ROH_014', 'Bandung - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_015', 'Bandung - Asia Afrika', NULL::bigint, true),
    ('ROH', 'ROH_016', 'Bandung - Astana Anyar', NULL::bigint, true),
    ('ROH', 'ROH_017', 'Bandung - Buah Batu', NULL::bigint, true),
    ('ROH', 'ROH_018', 'Bandung - Dago', NULL::bigint, true),
    ('ROH', 'ROH_019', 'Bandung - Kopo Bihbul', NULL::bigint, true),
    ('ROH', 'ROH_020', 'Bandung - Kota Baru Parahyangan', NULL::bigint, true),
    ('ROH', 'ROH_021', 'Bandung - Lembong', NULL::bigint, true),
    ('ROH', 'ROH_022', 'Bandung - Lingkar Selatan', NULL::bigint, true),
    ('ROH', 'ROH_023', 'Bandung - Otista', NULL::bigint, true),
    ('ROH', 'ROH_024', 'Bandung - Pajajaran', NULL::bigint, true),
    ('ROH', 'ROH_025', 'Bandung - Riau', NULL::bigint, true),
    ('ROH', 'ROH_026', 'Bandung - Setiabudi', NULL::bigint, true),
    ('ROH', 'ROH_027', 'Bandung - Sumber Sari', NULL::bigint, true),
    ('ROH', 'ROH_028', 'Banjarmasin - Ahmad Yani 56', NULL::bigint, true),
    ('ROH', 'ROH_029', 'Banjarmasin - Ahmad Yani Mitramas', NULL::bigint, true),
    ('ROH', 'ROH_030', 'Banjarmasin - Pangeran Samudera', NULL::bigint, true),
    ('ROH', 'ROH_031', 'Banyuwangi - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_032', 'Batam - Batamindo', NULL::bigint, true),
    ('ROH', 'ROH_033', 'Batam - Botania', NULL::bigint, true),
    ('ROH', 'ROH_034', 'Batam - Mahkota Raya', NULL::bigint, true),
    ('ROH', 'ROH_035', 'Batam - Nagoya', NULL::bigint, true),
    ('ROH', 'ROH_036', 'Batam - Palm Spring', NULL::bigint, true),
    ('ROH', 'ROH_037', 'Batam - Penuin Centre', NULL::bigint, true),
    ('ROH', 'ROH_038', 'Batam - Sei Panas', NULL::bigint, true),
    ('ROH', 'ROH_039', 'Bekasi - Befa Square', NULL::bigint, true),
    ('ROH', 'ROH_040', 'Bekasi - Jababeka', NULL::bigint, true),
    ('ROH', 'ROH_041', 'Bekasi - LG Cibitung', NULL::bigint, true),
    ('ROH', 'ROH_042', 'Bekasi - Lippo Cikarang', NULL::bigint, true),
    ('ROH', 'ROH_043', 'Bekasi - Summarecon', NULL::bigint, true),
    ('ROH', 'ROH_044', 'Binjai - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_045', 'Blitar - Merdeka', NULL::bigint, true),
    ('ROH', 'ROH_046', 'Bogor - Cibubur Kota Wisata', NULL::bigint, true),
    ('ROH', 'ROH_047', 'Bogor - Cileungsi', NULL::bigint, true),
    ('ROH', 'ROH_048', 'Bogor - Cisalak', NULL::bigint, true),
    ('ROH', 'ROH_049', 'Bogor - Juanda', NULL::bigint, true),
    ('ROH', 'ROH_050', 'Bogor - Padjajaran', NULL::bigint, true),
    ('ROH', 'ROH_051', 'Bogor - Plaza Niaga Sentul', NULL::bigint, true),
    ('ROH', 'ROH_052', 'Bogor - V Point', NULL::bigint, true),
    ('ROH', 'ROH_053', 'Bojonegoro - Gajah Mada', NULL::bigint, true),
    ('ROH', 'ROH_054', 'Cianjur - Cokroaminoto', NULL::bigint, true),
    ('ROH', 'ROH_055', 'Cibinong - Mayor Oking', NULL::bigint, true),
    ('ROH', 'ROH_056', 'Cilacap - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_057', 'Cilegon - City Square', NULL::bigint, true),
    ('ROH', 'ROH_058', 'Cimahi - Raya Tagog', NULL::bigint, true),
    ('ROH', 'ROH_059', 'Cirebon - Siliwangi', NULL::bigint, true),
    ('ROH', 'ROH_060', 'Cirebon - Yos Sudarso', NULL::bigint, true),
    ('ROH', 'ROH_061', 'Depok - Margonda', NULL::bigint, true),
    ('ROH', 'ROH_062', 'Dumai - Duri', NULL::bigint, true),
    ('ROH', 'ROH_063', 'Dumai - Sultan Syarif Qasim', NULL::bigint, true),
    ('ROH', 'ROH_064', 'Garut - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_065', 'Gresik - Kartini', NULL::bigint, true),
    ('ROH', 'ROH_066', 'Gresik - Usman Sadar', NULL::bigint, true),
    ('ROH', 'ROH_067', 'JAKARTA - PURI INDAH', NULL::bigint, true),
    ('ROH', 'ROH_068', 'Jakarta - Bellagio', NULL::bigint, true),
    ('ROH', 'ROH_069', 'Jakarta - Bintaro Sektor I', NULL::bigint, true),
    ('ROH', 'ROH_070', 'Jakarta - Bukit Gading Indah', NULL::bigint, true),
    ('ROH', 'ROH_071', 'Jakarta - Cempaka Putih 68', NULL::bigint, true),
    ('ROH', 'ROH_072', 'Jakarta - Central Park', NULL::bigint, true),
    ('ROH', 'ROH_073', 'Jakarta - Cibubur Citra Grand', NULL::bigint, true),
    ('ROH', 'ROH_074', 'Jakarta - Cideng', NULL::bigint, true),
    ('ROH', 'ROH_075', 'Jakarta - Cikini', NULL::bigint, true),
    ('ROH', 'ROH_076', 'Jakarta - Cinere', NULL::bigint, true),
    ('ROH', 'ROH_077', 'Jakarta - Citra Garden 1', NULL::bigint, true),
    ('ROH', 'ROH_078', 'Jakarta - Daan Mogot', NULL::bigint, true),
    ('ROH', 'ROH_079', 'Jakarta - Fatmawati 20', NULL::bigint, true),
    ('ROH', 'ROH_080', 'Jakarta - Gajah Mada', NULL::bigint, true),
    ('ROH', 'ROH_081', 'Jakarta - Gambir', NULL::bigint, true),
    ('ROH', 'ROH_082', 'Jakarta - Graha CIMB Niaga', NULL::bigint, true),
    ('ROH', 'ROH_083', 'Jakarta - Green Garden', NULL::bigint, true),
    ('ROH', 'ROH_084', 'Jakarta - Hayam Wuruk', NULL::bigint, true),
    ('ROH', 'ROH_085', 'Jakarta - Jatinegara', NULL::bigint, true),
    ('ROH', 'ROH_086', 'Jakarta - Jayakarta', NULL::bigint, true),
    ('ROH', 'ROH_087', 'Jakarta - Jembatan Dua', NULL::bigint, true),
    ('ROH', 'ROH_088', 'Jakarta - Kalimalang', NULL::bigint, true),
    ('ROH', 'ROH_089', 'Jakarta - Kebon Jeruk Intercon', NULL::bigint, true),
    ('ROH', 'ROH_090', 'Jakarta - Kebon Sirih', NULL::bigint, true),
    ('ROH', 'ROH_091', 'Jakarta - Kelapa Gading LB', NULL::bigint, true),
    ('ROH', 'ROH_092', 'Jakarta - Kelapa Gading TN', NULL::bigint, true),
    ('ROH', 'ROH_093', 'Jakarta - Kemang Raya 1', NULL::bigint, true),
    ('ROH', 'ROH_094', 'Jakarta - Kota', NULL::bigint, true),
    ('ROH', 'ROH_095', 'Jakarta - Kuningan Plaza', NULL::bigint, true),
    ('ROH', 'ROH_096', 'Jakarta - Lindeteves Trade Center', NULL::bigint, true),
    ('ROH', 'ROH_097', 'Jakarta - Mall Taman Anggrek', NULL::bigint, true),
    ('ROH', 'ROH_098', 'Jakarta - Mangga Dua Rutex', NULL::bigint, true),
    ('ROH', 'ROH_099', 'Jakarta - Matraman', NULL::bigint, true),
    ('ROH', 'ROH_100', 'Jakarta - Melawai', NULL::bigint, true),
    ('ROH', 'ROH_101', 'Jakarta - Menara Satrio', NULL::bigint, true),
    ('ROH', 'ROH_102', 'Jakarta - Menara Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_103', 'Jakarta - Menteng', NULL::bigint, true),
    ('ROH', 'ROH_104', 'Jakarta - Metro Pondok Indah', NULL::bigint, true),
    ('ROH', 'ROH_105', 'Jakarta - Millenia', NULL::bigint, true),
    ('ROH', 'ROH_106', 'Jakarta - Muara Karang', NULL::bigint, true),
    ('ROH', 'ROH_107', 'Jakarta - Panglima Polim', NULL::bigint, true),
    ('ROH', 'ROH_108', 'Jakarta - Pantai Indah Kapuk', NULL::bigint, true),
    ('ROH', 'ROH_109', 'Jakarta - Pasar Induk Kramat Jati', NULL::bigint, true),
    ('ROH', 'ROH_110', 'Jakarta - Permata Hijau', NULL::bigint, true),
    ('ROH', 'ROH_111', 'Jakarta - Pintu Air', NULL::bigint, true),
    ('ROH', 'ROH_112', 'Jakarta - Pintu Kecil', NULL::bigint, true),
    ('ROH', 'ROH_113', 'Jakarta - Plaza Sinar Mas Land', NULL::bigint, true),
    ('ROH', 'ROH_114', 'Jakarta - Pluit', NULL::bigint, true),
    ('ROH', 'ROH_115', 'Jakarta - Pondok Gede', NULL::bigint, true),
    ('ROH', 'ROH_116', 'Jakarta - Pondok Indah Icon', NULL::bigint, true),
    ('ROH', 'ROH_117', 'Jakarta - Rawamangun Pratama', NULL::bigint, true),
    ('ROH', 'ROH_118', 'Jakarta - Roxy mas', NULL::bigint, true),
    ('ROH', 'ROH_119', 'Jakarta - Sawah Besar', NULL::bigint, true),
    ('ROH', 'ROH_120', 'Jakarta - Senayan City', NULL::bigint, true),
    ('ROH', 'ROH_121', 'Jakarta - Sentral Senayan II', NULL::bigint, true),
    ('ROH', 'ROH_122', 'Jakarta - SetiaBudi', NULL::bigint, true),
    ('ROH', 'ROH_123', 'Jakarta - Sunter', NULL::bigint, true),
    ('ROH', 'ROH_124', 'Jakarta - Tanjung Priok', NULL::bigint, true),
    ('ROH', 'ROH_125', 'Jakarta - Tebet', NULL::bigint, true),
    ('ROH', 'ROH_126', 'Jakarta - Teluk Gong', NULL::bigint, true),
    ('ROH', 'ROH_127', 'Jakarta - Tempo Scan', NULL::bigint, true),
    ('ROH', 'ROH_128', 'Jakarta - Tomang Tol', NULL::bigint, true),
    ('ROH', 'ROH_129', 'Jakarta - Wahid Hasyim', NULL::bigint, true),
    ('ROH', 'ROH_130', 'Jakarta - Warung Buncit', NULL::bigint, true),
    ('ROH', 'ROH_131', 'Jakarta - Wisma Metropolitan', NULL::bigint, true),
    ('ROH', 'ROH_132', 'Jakarta - Wisma Pondok Indah', NULL::bigint, true),
    ('ROH', 'ROH_133', 'Jambi Sutomo', NULL::bigint, true),
    ('ROH', 'ROH_134', 'Jayapura - Pasifik Permai', NULL::bigint, true),
    ('ROH', 'ROH_135', 'Jember - Diponegoro', NULL::bigint, true),
    ('ROH', 'ROH_136', 'Jepara - Diponegoro', NULL::bigint, true),
    ('ROH', 'ROH_137', 'Jombang - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_138', 'Karawang - Surya Cipta', NULL::bigint, true),
    ('ROH', 'ROH_139', 'Karawang - Tuparev', NULL::bigint, true),
    ('ROH', 'ROH_140', 'Kas Mobil - Batam', NULL::bigint, true),
    ('ROH', 'ROH_141', 'Kas Mobil - Cirebon', NULL::bigint, true),
    ('ROH', 'ROH_142', 'Kas Mobil - East', NULL::bigint, true),
    ('ROH', 'ROH_143', 'Kas Mobil - Jabar', NULL::bigint, true),
    ('ROH', 'ROH_144', 'Kas Mobil - Jakarta Central', NULL::bigint, true),
    ('ROH', 'ROH_145', 'Kas Mobil - Lembong', NULL::bigint, true),
    ('ROH', 'ROH_146', 'Kas Mobil - Makassar', NULL::bigint, true),
    ('ROH', 'ROH_147', 'Kas Mobil - Malang', NULL::bigint, true),
    ('ROH', 'ROH_148', 'Kas Mobil - Medan', NULL::bigint, true),
    ('ROH', 'ROH_149', 'Kas Mobil - Padang', NULL::bigint, true),
    ('ROH', 'ROH_150', 'Kas Mobil - Palembang', NULL::bigint, true),
    ('ROH', 'ROH_151', 'Kas Mobil - Samarinda', NULL::bigint, true),
    ('ROH', 'ROH_152', 'Kas Mobil - Semarang', NULL::bigint, true),
    ('ROH', 'ROH_153', 'Kas Mobil - South', NULL::bigint, true),
    ('ROH', 'ROH_154', 'Kas Mobil - Surabaya ', NULL::bigint, true),
    ('ROH', 'ROH_155', 'Kas Mobil - Surabaya 2', NULL::bigint, true),
    ('ROH', 'ROH_156', 'Kas Mobil - Tangerang', NULL::bigint, true),
    ('ROH', 'ROH_157', 'Kebumen - Pahlawan', NULL::bigint, true),
    ('ROH', 'ROH_158', 'Kediri - Diponegoro', NULL::bigint, true),
    ('ROH', 'ROH_159', 'Kelapa Gading LB', NULL::bigint, true),
    ('ROH', 'ROH_160', 'Kendari - Mandonga', NULL::bigint, true),
    ('ROH', 'ROH_161', 'Klaten - Pemuda', NULL::bigint, true),
    ('ROH', 'ROH_162', 'Kudus - Agil Kusumadya', NULL::bigint, true),
    ('ROH', 'ROH_163', 'Kudus - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_164', 'Kupang - Lalamentik', NULL::bigint, true),
    ('ROH', 'ROH_165', 'Lamongan - Lamongrejo', NULL::bigint, true),
    ('ROH', 'ROH_166', 'Lampung - Hasanudin', NULL::bigint, true),
    ('ROH', 'ROH_167', 'Lampung - Malahayati', NULL::bigint, true),
    ('ROH', 'ROH_168', 'Lampung - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_169', 'Lampung - Tanjung Karang', NULL::bigint, true),
    ('ROH', 'ROH_170', 'Lhokseumawe - Suka Ramai', NULL::bigint, true),
    ('ROH', 'ROH_171', 'Lumajang - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_172', 'Madiun - Pahlawan', NULL::bigint, true),
    ('ROH', 'ROH_173', 'Magelang - Rejotumoto', NULL::bigint, true),
    ('ROH', 'ROH_174', 'Makassar - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_175', 'Makassar - Bandang', NULL::bigint, true),
    ('ROH', 'ROH_176', 'Makassar - Panakukang', NULL::bigint, true),
    ('ROH', 'ROH_177', 'Malang - Basuki Rachmad', NULL::bigint, true),
    ('ROH', 'ROH_178', 'Malang - Galunggung', NULL::bigint, true),
    ('ROH', 'ROH_179', 'Malang - Kyai Tamin', NULL::bigint, true),
    ('ROH', 'ROH_180', 'Malang - Merdeka', NULL::bigint, true),
    ('ROH', 'ROH_181', 'Malang - Soekarno Hatta', NULL::bigint, true),
    ('ROH', 'ROH_182', 'Manado - Mega Mas', NULL::bigint, true),
    ('ROH', 'ROH_183', 'Manado - Walanda Maramis', NULL::bigint, true),
    ('ROH', 'ROH_184', 'Mataram - Pejanggik', NULL::bigint, true),
    ('ROH', 'ROH_185', 'Medan - AR Hakim', NULL::bigint, true),
    ('ROH', 'ROH_186', 'Medan - Asia', NULL::bigint, true),
    ('ROH', 'ROH_187', 'Medan - Bandung', NULL::bigint, true),
    ('ROH', 'ROH_188', 'Medan - Bukit Barisan', NULL::bigint, true),
    ('ROH', 'ROH_189', 'Medan - Cemara Asri', NULL::bigint, true),
    ('ROH', 'ROH_190', 'Medan - Gajah Mada', NULL::bigint, true),
    ('ROH', 'ROH_191', 'Medan - Gatot Subroto', NULL::bigint, true),
    ('ROH', 'ROH_192', 'Medan - Icon', NULL::bigint, true),
    ('ROH', 'ROH_193', 'Medan - Juanda', NULL::bigint, true),
    ('ROH', 'ROH_194', 'Medan - KS Tubun', NULL::bigint, true),
    ('ROH', 'ROH_195', 'Medan - M Yamin', NULL::bigint, true),
    ('ROH', 'ROH_196', 'Medan - Marelan', NULL::bigint, true),
    ('ROH', 'ROH_197', 'Medan - Pemuda', NULL::bigint, true),
    ('ROH', 'ROH_198', 'Medan - Sutomo Ujung', NULL::bigint, true),
    ('ROH', 'ROH_199', 'Medan - Syariah Ringroad', NULL::bigint, true),
    ('ROH', 'ROH_200', 'Medan - Yos Sudarso', NULL::bigint, true),
    ('ROH', 'ROH_201', 'Mimika - Budi Utomo', NULL::bigint, true),
    ('ROH', 'ROH_202', 'Mimika - Kuala Kencana', NULL::bigint, true),
    ('ROH', 'ROH_203', 'Mimika - Ridge Camp', NULL::bigint, true),
    ('ROH', 'ROH_204', 'Mimika - Tembagapura I', NULL::bigint, true),
    ('ROH', 'ROH_205', 'Mimika - Tembagapura II', NULL::bigint, true),
    ('ROH', 'ROH_206', 'Mojokerto - Mojopahit', NULL::bigint, true),
    ('ROH', 'ROH_207', 'Ngawi - Sultan Agung', NULL::bigint, true),
    ('ROH', 'ROH_208', 'Padang - M Yamin', NULL::bigint, true),
    ('ROH', 'ROH_209', 'Padang - Pondok', NULL::bigint, true),
    ('ROH', 'ROH_210', 'Padang - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_211', 'Palangkaraya - Murjani', NULL::bigint, true),
    ('ROH', 'ROH_212', 'Palembang - Kolonel Atmo', NULL::bigint, true),
    ('ROH', 'ROH_213', 'Palembang - Letkol Iskandar', NULL::bigint, true),
    ('ROH', 'ROH_214', 'Palembang - Soekamto', NULL::bigint, true),
    ('ROH', 'ROH_215', 'Palembang - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_216', 'Palembang - Sukamto', NULL::bigint, true),
    ('ROH', 'ROH_217', 'Pangkal Pinang - Masjid Jamik', NULL::bigint, true),
    ('ROH', 'ROH_218', 'Pasuruan - Pasar Besar', NULL::bigint, true),
    ('ROH', 'ROH_219', 'Pekalongan - Hayam Wuruk', NULL::bigint, true),
    ('ROH', 'ROH_220', 'Pekanbaru - Harapan Jaya', NULL::bigint, true),
    ('ROH', 'ROH_221', 'Pekanbaru - Panam', NULL::bigint, true),
    ('ROH', 'ROH_222', 'Pekanbaru - Riau', NULL::bigint, true),
    ('ROH', 'ROH_223', 'Pekanbaru - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_224', 'Pekanbaru - Tuanku Tambusai', NULL::bigint, true),
    ('ROH', 'ROH_225', 'Pematang Siantar - Merdeka', NULL::bigint, true),
    ('ROH', 'ROH_226', 'Ponorogo - Gajah Mada', NULL::bigint, true),
    ('ROH', 'ROH_227', 'Pontianak - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_228', 'Pontianak - Tanjungpura', NULL::bigint, true),
    ('ROH', 'ROH_229', 'Purbalingga - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_230', 'Purwakarta - Veteran', NULL::bigint, true),
    ('ROH', 'ROH_231', 'Purwokerto - Sudirman 417', NULL::bigint, true),
    ('ROH', 'ROH_232', 'Purwokerto - Sudirman 605', NULL::bigint, true),
    ('ROH', 'ROH_233', 'Rantau Prapat - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_234', 'Salatiga - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_235', 'Samarinda - Bung Tomo', NULL::bigint, true),
    ('ROH', 'ROH_236', 'Samarinda - Juanda', NULL::bigint, true),
    ('ROH', 'ROH_237', 'Samarinda - KH Khalid', NULL::bigint, true),
    ('ROH', 'ROH_238', 'Samarinda - Simpang Merak', NULL::bigint, true),
    ('ROH', 'ROH_239', 'Semarang - Candi', NULL::bigint, true),
    ('ROH', 'ROH_240', 'Semarang - Cendrawasih', NULL::bigint, true),
    ('ROH', 'ROH_241', 'Semarang - Gajah Mada', NULL::bigint, true),
    ('ROH', 'ROH_242', 'Semarang - Kaligawe', NULL::bigint, true),
    ('ROH', 'ROH_243', 'Semarang - Mataram', NULL::bigint, true),
    ('ROH', 'ROH_244', 'Semarang - Pemuda 102', NULL::bigint, true),
    ('ROH', 'ROH_245', 'Semarang - Siliwangi', NULL::bigint, true),
    ('ROH', 'ROH_246', 'Semarang - Syariah Pemuda 21B', NULL::bigint, true),
    ('ROH', 'ROH_247', 'Semarang - Univ Semarang', NULL::bigint, true),
    ('ROH', 'ROH_248', 'Sidoarjo - Ahmad Yani', NULL::bigint, true),
    ('ROH', 'ROH_249', 'Singkawang', NULL::bigint, true),
    ('ROH', 'ROH_250', 'Situbondo - Sepudi', NULL::bigint, true),
    ('ROH', 'ROH_251', 'Solo - Kartasura', NULL::bigint, true),
    ('ROH', 'ROH_252', 'Solo - Manahan', NULL::bigint, true),
    ('ROH', 'ROH_253', 'Solo - Mesen Square', NULL::bigint, true),
    ('ROH', 'ROH_254', 'Solo - Pasar Klewer', NULL::bigint, true),
    ('ROH', 'ROH_255', 'Solo - Slamet Riyadi 136', NULL::bigint, true),
    ('ROH', 'ROH_256', 'Solo - Slamet Riyadi 8', NULL::bigint, true),
    ('ROH', 'ROH_257', 'Solo - Solo Baru', NULL::bigint, true),
    ('ROH', 'ROH_258', 'Sukabumi - Martadinata', NULL::bigint, true),
    ('ROH', 'ROH_259', 'Surabaya - Andayani', NULL::bigint, true),
    ('ROH', 'ROH_260', 'Surabaya - Darmo', NULL::bigint, true),
    ('ROH', 'ROH_261', 'Surabaya - Dharmahusada', NULL::bigint, true),
    ('ROH', 'ROH_262', 'Surabaya - Diponegoro', NULL::bigint, true),
    ('ROH', 'ROH_263', 'Surabaya - Kapas Krampung', NULL::bigint, true),
    ('ROH', 'ROH_264', 'Surabaya - Kembang Jepun', NULL::bigint, true),
    ('ROH', 'ROH_265', 'Surabaya - Klampis', NULL::bigint, true),
    ('ROH', 'ROH_266', 'Surabaya - Manyar Kertoardjo', NULL::bigint, true),
    ('ROH', 'ROH_267', 'Surabaya - Manyar Mega Indah', NULL::bigint, true),
    ('ROH', 'ROH_268', 'Surabaya - Pakuwon City', NULL::bigint, true),
    ('ROH', 'ROH_269', 'Surabaya - Pasar Atom', NULL::bigint, true),
    ('ROH', 'ROH_270', 'Surabaya - Perak', NULL::bigint, true),
    ('ROH', 'ROH_271', 'Surabaya - Pucang Anom', NULL::bigint, true),
    ('ROH', 'ROH_272', 'Surabaya - Rungkut', NULL::bigint, true),
    ('ROH', 'ROH_273', 'Surabaya - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_274', 'Surabaya - Sukomanunggal', NULL::bigint, true),
    ('ROH', 'ROH_275', 'Surabaya - Sungkono', NULL::bigint, true),
    ('ROH', 'ROH_276', 'Surabaya - Tidar', NULL::bigint, true),
    ('ROH', 'ROH_277', 'Tangerang - Alam Sutera Icon', NULL::bigint, true),
    ('ROH', 'ROH_278', 'Tangerang - Bintaro Griya Niaga', NULL::bigint, true),
    ('ROH', 'ROH_279', 'Tangerang - Gading Serpong', NULL::bigint, true),
    ('ROH', 'ROH_280', 'Tangerang - Itc Bsd', NULL::bigint, true),
    ('ROH', 'ROH_281', 'Tangerang - Karawaci', NULL::bigint, true),
    ('ROH', 'ROH_282', 'Tangerang - Kisamaun', NULL::bigint, true),
    ('ROH', 'ROH_283', 'Tangerang - LG Cirarab', NULL::bigint, true),
    ('ROH', 'ROH_284', 'Tangerang - Pasar Modern BSD', NULL::bigint, true),
    ('ROH', 'ROH_285', 'Tangerang - Pinangsia', NULL::bigint, true),
    ('ROH', 'ROH_286', 'Tangerang - Serpong ', NULL::bigint, true),
    ('ROH', 'ROH_287', 'Tangerang - Tangerang City', NULL::bigint, true),
    ('ROH', 'ROH_288', 'Tanjung Pinang - Merdeka', NULL::bigint, true),
    ('ROH', 'ROH_289', 'Tarakan - Karang Anyar', NULL::bigint, true),
    ('ROH', 'ROH_290', 'Tasikmalaya - HZ Mustofa', NULL::bigint, true),
    ('ROH', 'ROH_291', 'Tasikmalaya - Yudanegara', NULL::bigint, true),
    ('ROH', 'ROH_292', 'Tebing Tinggi - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_293', 'Tegal - Slawi', NULL::bigint, true),
    ('ROH', 'ROH_294', 'Tegal - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_295', 'Tulungagung - Sudirman', NULL::bigint, true),
    ('ROH', 'ROH_296', 'Yogyakarta - Gejayan', NULL::bigint, true),
    ('ROH', 'ROH_297', 'Yogyakarta - Karangwaru', NULL::bigint, true),
    ('ROH', 'ROH_298', 'Yogyakarta - Parang Tritis', NULL::bigint, true),
    ('ROH', 'ROH_299', 'Yogyakarta - Sudirman 13', NULL::bigint, true),
    ('ROH', 'ROH_300', 'Yogyakarta - Sudirman 50', NULL::bigint, true),
    ('SSI', 'SSI_001', 'SSI Aceh', NULL::bigint, true),
    ('SSI', 'SSI_002', 'SSI Banjarmasin', NULL::bigint, true),
    ('SSI', 'SSI_003', 'SSI Palangkaraya', NULL::bigint, true),
    ('SSI', 'SSI_004', 'SSI Tarakan', NULL::bigint, true),
    ('TAG', 'TAG_001', 'TAG Ambon', NULL::bigint, true),
    ('TAG', 'TAG_002', 'TAG Bali', NULL::bigint, true),
    ('TAG', 'TAG_003', 'TAG Bandung', NULL::bigint, true),
    ('TAG', 'TAG_004', 'TAG Bekasi', NULL::bigint, true),
    ('TAG', 'TAG_005', 'TAG Cirebon', NULL::bigint, true),
    ('TAG', 'TAG_006', 'TAG Jember', NULL::bigint, true),
    ('TAG', 'TAG_007', 'TAG Kediri', NULL::bigint, true),
    ('TAG', 'TAG_008', 'TAG Kendari', NULL::bigint, true),
    ('TAG', 'TAG_009', 'TAG Madiun', NULL::bigint, true),
    ('TAG', 'TAG_010', 'TAG Makasar', NULL::bigint, true),
    ('TAG', 'TAG_011', 'TAG Malang', NULL::bigint, true),
    ('TAG', 'TAG_012', 'TAG Pangkal Pinang', NULL::bigint, true),
    ('TAG', 'TAG_013', 'TAG Semarang', NULL::bigint, true),
    ('TAG', 'TAG_014', 'TAG Solo', NULL::bigint, true),
    ('TAG', 'TAG_015', 'TAG Surabaya', NULL::bigint, true),
    ('TAG', 'TAG_016', 'TAG Tanjung Pinang', NULL::bigint, true),
    ('TAG', 'TAG_017', 'TAG Yogyakarta', NULL::bigint, true)
)
INSERT INTO public.vendor_branches (vendor_id, branch_code, branch_name, location_id, is_active)
SELECT v.id, s.branch_code, s.branch_name, s.location_id, s.is_active
FROM seed_vendor_branches s
JOIN public.vendors v ON v.code = s.vendor_code
ON CONFLICT (branch_code) DO UPDATE
SET
    vendor_id = EXCLUDED.vendor_id,
    branch_name = EXCLUDED.branch_name,
    location_id = EXCLUDED.location_id,
    is_active = EXCLUDED.is_active,
    updated_at = now();

COMMIT;