-- 007_branch_coverage_areas.sql
-- Cakupan kota per cabang vendor (many-to-many), sumber:
--   archives/vault dan cashpoint/vendor_vault_region_branch.csv
-- vendor_branches.region hanya menampung satu nilai, sedangkan satu cabang
-- melayani banyak kota dan satu kota dilayani banyak cabang.

BEGIN;

CREATE TABLE IF NOT EXISTS public.branch_coverage_areas (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    vendor_branch_id bigint      NOT NULL REFERENCES public.vendor_branches(id) ON DELETE CASCADE,
    city             text        NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_branch_coverage_areas UNIQUE (vendor_branch_id, city)
);

CREATE INDEX IF NOT EXISTS branch_coverage_areas_city_idx ON public.branch_coverage_areas (city);

COMMENT ON TABLE public.branch_coverage_areas IS
    'Kota yang dilayani sebuah cabang vendor. Many-to-many: satu cabang melayani banyak kota, satu kota dilayani banyak cabang vendor.';

-- Hub regional ROH: 8 kode di CSV tidak punya padanan di 300 baris ROH per-lokasi,
-- jadi dibuat sebagai cabang baru. vendor_branches_id_seq sudah di 461, id aman DEFAULT.
INSERT INTO public.vendor_branches (vendor_id, branch_code, branch_name, is_active, region) VALUES
    (5, 'ROH_H01', 'ROH Indonesia Timur & Kalimantan', true, 'Indonesia Timur dan Kalimantan'),
    (5, 'ROH_H02', 'ROH Jawa Barat', true, 'Jawa Barat'),
    (5, 'ROH_H03', 'ROH Jawa Tengah', true, 'Jawa Tengah'),
    (5, 'ROH_H04', 'ROH Jawa Timur & Bali Nusra', true, 'Jawa Timur'),
    (5, 'ROH_H05', 'ROH Jakarta Pusat & Selatan', true, 'Jakarta Pusat'),
    (5, 'ROH_H06', 'ROH Jakarta Timur', true, 'Jakarta Timur'),
    (5, 'ROH_H07', 'ROH Jakarta Utara & Barat', true, 'Jakarta Utara'),
    (5, 'ROH_H08', 'ROH Sumatera', true, 'Sumatera')
ON CONFLICT (branch_code) DO NOTHING;

INSERT INTO public.branch_coverage_areas (vendor_branch_id, city)
SELECT vb.id, v.city
FROM (VALUES
    ('ADVANTAGE_001', 'Balikpapan'),
    ('ADVANTAGE_002', 'Banjarmasin'),
    ('ADVANTAGE_003', 'Batam'),
    ('ADVANTAGE_017', 'Serang'),
    ('ADVANTAGE_004', 'Jambi'),
    ('ADVANTAGE_005', 'Kupang'),
    ('ADVANTAGE_006', 'Lampung'),
    ('ADVANTAGE_007', 'Manado'),
    ('ADVANTAGE_008', 'Mataram'),
    ('ADVANTAGE_009', 'Medan'),
    ('ADVANTAGE_010', 'Padang'),
    ('ADVANTAGE_011', 'Palembang'),
    ('ADVANTAGE_012', 'Pekanbaru'),
    ('ADVANTAGE_013', 'Pontianak'),
    ('ADVANTAGE_014', 'Purbalingga'),
    ('ADVANTAGE_014', 'Purwokerto'),
    ('ADVANTAGE_015', 'Samarinda'),
    ('ADVANTAGE_016', 'Semarang'),
    ('ADVANTAGE_018', 'Tegal'),
    ('ADVANTAGE_018', 'Semarang'),
    ('ADVANTAGE_018', 'Pemalang'),
    ('ADVANTAGE_018', 'Pekalongan'),
    ('ABACUS_001', 'Bali'),
    ('ABACUS_002', 'Bandung'),
    ('ABACUS_002', 'Purwakarta'),
    ('ABACUS_002', 'Karawang'),
    ('ABACUS_003', 'Tasikmalaya'),
    ('ABACUS_004', 'Medan'),
    ('ABACUS_005', 'Solo'),
    ('ABACUS_007', 'Cianjur'),
    ('ABACUS_007', 'Sukabumi'),
    ('ABACUS_008', 'Purworejo'),
    ('ABACUS_008', 'Yogyakarta'),
    ('BIJAK_001', 'Tangerang'),
    ('BIJAK_001', 'Bogor'),
    ('BIJAK_001', 'Jakarta Utara'),
    ('BIJAK_001', 'Bekasi'),
    ('BIJAK_001', 'Jakarta Selatan'),
    ('BIJAK_001', 'Jakarta Timur'),
    ('BIJAK_001', 'Jakarta Barat'),
    ('BIJAK_001', 'Depok'),
    ('BIJAK_001', 'Cikarang'),
    ('BIJAK_001', 'Jakarta Pusat'),
    ('BIJAK_001', 'Serang'),
    ('ROH_H01', 'Banjarmasin'),
    ('ROH_H01', 'Ambon'),
    ('ROH_H01', 'Balikpapan'),
    ('ROH_H01', 'Pontianak'),
    ('ROH_H01', 'Manado'),
    ('ROH_H01', 'Samarinda'),
    ('ROH_H01', 'Papua'),
    ('ROH_H01', 'Palangkaraya'),
    ('ROH_H01', 'Makasar'),
    ('ROH_H01', 'Kendari'),
    ('ROH_H01', 'Tarakan'),
    ('ROH_H01', 'Tembagapura'),
    ('ROH_H01', 'Jayapura'),
    ('ROH_H02', 'Bandung'),
    ('ROH_H02', 'Cianjur'),
    ('ROH_H02', 'Tasikmalaya'),
    ('ROH_H02', 'Cirebon'),
    ('ROH_H02', 'Purwakarta'),
    ('ROH_H02', 'Garut'),
    ('ROH_H02', 'Sukabumi'),
    ('ROH_H02', 'Bogor'),
    ('ROH_H03', 'Cilacap'),
    ('ROH_H03', 'Purbalingga'),
    ('ROH_H03', 'Tegal'),
    ('ROH_H03', 'Yogyakarta'),
    ('ROH_H03', 'Semarang'),
    ('ROH_H03', 'Kebumen'),
    ('ROH_H03', 'Kudus'),
    ('ROH_H03', 'Solo'),
    ('ROH_H03', 'Magelang'),
    ('ROH_H03', 'Salatiga'),
    ('ROH_H03', 'Pekalongan'),
    ('ROH_H03', 'Purwokerto'),
    ('ROH_H03', 'Slawi'),
    ('ROH_H03', 'Jepara'),
    ('ROH_H04', 'Mojokerto'),
    ('ROH_H04', 'Ponorogo'),
    ('ROH_H04', 'Surabaya'),
    ('ROH_H04', 'Jombang'),
    ('ROH_H04', 'Bali'),
    ('ROH_H04', 'Madiun'),
    ('ROH_H04', 'Jember'),
    ('ROH_H04', 'Kupang'),
    ('ROH_H04', 'Lamongan'),
    ('ROH_H04', 'Kediri'),
    ('ROH_H04', 'Banyuwangi'),
    ('ROH_H04', 'Pasuruan'),
    ('ROH_H04', 'Bojonegoro'),
    ('ROH_H04', 'Blitar'),
    ('ROH_H04', 'Lumajang'),
    ('ROH_H04', 'Malang'),
    ('ROH_H04', 'Sidoarjo'),
    ('ROH_H04', 'Mataram'),
    ('ROH_H04', 'Tulungagung'),
    ('ROH_H04', 'Jepara'),
    ('ROH_H04', 'Makasar'),
    ('ROH_H04', 'Gresik'),
    ('ROH_H04', 'Ngawi'),
    ('ROH_H05', 'Jakarta Pusat'),
    ('ROH_H05', 'Jakarta Selatan'),
    ('ROH_H05', 'Tangerang'),
    ('ROH_H05', 'Depok'),
    ('ROH_H05', 'Jakarta Utara'),
    ('ROH_H05', 'Jakarta Timur'),
    ('ROH_H06', 'Jakarta Utara'),
    ('ROH_H06', 'Bogor'),
    ('ROH_H06', 'Jakarta Timur'),
    ('ROH_H06', 'Cikarang'),
    ('ROH_H06', 'Jakarta Pusat'),
    ('ROH_H06', 'Karawang'),
    ('ROH_H06', 'Bekasi'),
    ('ROH_H07', 'Jakarta Utara'),
    ('ROH_H07', 'Jakarta Barat'),
    ('ROH_H07', 'Jakarta Pusat'),
    ('ROH_H07', 'Tangerang'),
    ('ROH_H07', 'Cilegon'),
    ('ROH_H08', 'Batam'),
    ('ROH_H08', 'Lampung'),
    ('ROH_H08', 'Medan'),
    ('ROH_H08', 'Jambi'),
    ('ROH_H08', 'Palembang'),
    ('ROH_H08', 'Pekanbaru'),
    ('ROH_H08', 'Pematang Siantar'),
    ('ROH_H08', 'Tanjung Pinang'),
    ('ROH_H08', 'Tebing Tinggi'),
    ('ROH_H08', 'Pangkal Pinang'),
    ('ROH_H08', 'Riau'),
    ('ROH_H08', 'Aceh'),
    ('ROH_H08', 'Padang'),
    ('SSI_001', 'Aceh'),
    ('SSI_002', 'Banjarmasin'),
    ('SSI_003', 'Palangkaraya'),
    ('SSI_003', 'Banjarmasin'),
    ('SSI_004', 'Tarakan'),
    ('TAG_001', 'Ambon'),
    ('TAG_002', 'Bali'),
    ('TAG_003', 'Bandung'),
    ('TAG_005', 'Cirebon'),
    ('TAG_005', 'Tegal'),
    ('TAG_004', 'Karawang'),
    ('TAG_004', 'Bekasi'),
    ('TAG_004', 'Tangerang'),
    ('TAG_004', 'Cikarang'),
    ('TAG_006', 'Bondowoso'),
    ('TAG_007', 'Kediri'),
    ('TAG_007', 'Surabaya'),
    ('TAG_008', 'Kendari'),
    ('TAG_009', 'Madiun'),
    ('TAG_010', 'Makasar'),
    ('TAG_011', 'Pasuruan'),
    ('TAG_011', 'Malang'),
    ('TAG_011', 'Probolinggo'),
    ('TAG_012', 'Pangkal Pinang'),
    ('TAG_013', 'Ambarawa'),
    ('TAG_013', 'Kudus'),
    ('TAG_013', 'Semarang'),
    ('TAG_013', 'Salatiga'),
    ('TAG_013', 'Jepara'),
    ('TAG_014', 'Solo'),
    ('TAG_014', 'Boyolali'),
    ('TAG_015', 'Surabaya'),
    ('TAG_015', 'Sidoarjo'),
    ('TAG_015', 'Mojokerto'),
    ('TAG_015', 'Gresik'),
    ('TAG_016', 'Tanjung Pinang'),
    ('TAG_017', 'Yogyakarta'),
    ('TAG_017', 'Magelang')
) AS v(branch_code, city)
JOIN public.vendor_branches vb ON vb.branch_code = v.branch_code
ON CONFLICT ON CONSTRAINT uq_branch_coverage_areas DO NOTHING;

COMMIT;
