-- 026_replenish_ticket_region.sql
-- Nomor tiket replenish per ATM + nomor request per region vendor cabang
-- (.claude/sdlc/replenish-ticket/spec.md, accepted 2026-10-08).
--
--   * vendor_branches.region_code: kode region bersih (seed dari teks region).
--   * vendor_requests.region_code: snapshot; NULL = format nomor lama.
--   * vendor_request_number_seq: counter per (vendor, region_code, tanggal).
--   * vendor_request_tickets: satu tiket aktif per (request, ATM),
--     <terminal_id>_<50K|100K|MIX>_<YYYYMMDD>_<NNN>, FK ke request_number.
--   * vendor_request_atm_results dipindah ke tiket lalu DROP.
--
-- SAFETY (Sec 4 #7, disetujui PO 2026-10-08):
--   * DROP TABLE vendor_request_atm_results setelah salin + guard jumlah.
--   * Seed master data hanya baris region_code NULL; teks region tidak diubah.
--   * Satu tx. Forward-only: no down migration (project convention).
BEGIN;

-- 1. vendor_branches.region_code + seed (FR11)
ALTER TABLE public.vendor_branches
    ADD COLUMN region_code text CONSTRAINT vendor_branches_region_code_chk CHECK (region_code ~ '^[A-Z0-9]{2,10}$');
COMMENT ON COLUMN public.vendor_branches.region_code IS
    'Kode region vendor cabang untuk nomor request REP-<vendor>-<region_code>-<YYYYMMDD>-<NNN>. NULL = request ditolak.';

UPDATE public.vendor_branches b
SET region_code = m.code
FROM (VALUES
    ('Jakarta', 'JKT'), ('Jakarta Barat', 'JKTBAR'), ('Jakarta Pusat', 'JKTPST'),
    ('Jakarta Selatan', 'JKTSEL'), ('Jakarta Timur', 'JKTTIM'), ('Jakarta Utara', 'JKTUTR'),
    ('Jawa Barat', 'JABAR'), ('Jawa barat', 'JABAR'), ('Jawa Tengah', 'JATENG'), ('Jawa Timur', 'JATIM'),
    ('Bali', 'BALI'), ('Bali Nusra', 'BALNUS'), ('Indonesia Timur dan Kalimantan', 'INDTIM'),
    ('Sumatera', 'SUMATERA'), ('Medan', 'MDN'),
    ('Aceh', 'ACEH'), ('Ambon', 'AMBON'), ('Jambi', 'JAMBI'), ('Jember', 'JEMBER'),
    ('Kupang', 'KUPANG'), ('Lampung', 'LAMPUNG'), ('Madiun', 'MADIUN'),
    ('Balikpapan', 'BPN'), ('Banjarmasin', 'BJM'), ('Kendari', 'KDI'), ('Makasar', 'MKS'),
    ('Manado', 'MDO'), ('Mataram', 'MTR'),
    ('Palangkaraya', 'PKY'), ('Palembang', 'PLG'), ('Pangkal Pinang', 'PGK'), ('Pekanbaru', 'PKU'),
    ('Pontianak', 'PNK'), ('Samarinda', 'SMD'), ('Tanjung Pinang', 'TNJ')
) AS m(region, code)
WHERE btrim(b.region, ' Â') = m.region   -- 'Jakarta UtaraÂ' (sisa encoding) ikut JKTUTR
  AND b.region_code IS NULL;

-- 2. vendor_requests.region_code (FR10.3)
ALTER TABLE public.vendor_requests ADD COLUMN region_code text;
COMMENT ON COLUMN public.vendor_requests.region_code IS
    'Snapshot kode region vendor cabang saat create. NULL = request format nomor lama.';

-- 3. Counter nomor request per (vendor, region_code, tanggal) (FR10.5, FR7.6)
ALTER TABLE public.vendor_request_number_seq ADD COLUMN region_code text;
ALTER TABLE public.vendor_request_number_seq DROP CONSTRAINT vendor_request_number_seq_pkey;
ALTER TABLE public.vendor_request_number_seq
    ADD CONSTRAINT vendor_request_number_seq_uq UNIQUE NULLS NOT DISTINCT (vendor_id, region_code, seq_date);

-- 4. Tiket per (request, ATM) (FR1–FR4, FR9)
CREATE TABLE public.vendor_request_tickets (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number    text NOT NULL REFERENCES public.vendor_requests(request_number) ON DELETE RESTRICT,
    terminal_id       text NOT NULL,
    denom_code        text NOT NULL CHECK (denom_code ~ '^([1-9][0-9]*K|MIX)$'),
    replenish_date    date NOT NULL,
    seq               smallint NOT NULL CONSTRAINT vendor_request_tickets_seq_chk CHECK (seq BETWEEN 1 AND 999),
    ticket_number     text NOT NULL,
    is_active         boolean NOT NULL DEFAULT true,
    created_at        timestamptz NOT NULL DEFAULT now(),
    deactivated_at    timestamptz,
    result            text CHECK (result IN ('success', 'failed')),
    result_updated_at timestamptz,
    CONSTRAINT vendor_request_tickets_number_uq UNIQUE (ticket_number),
    CONSTRAINT vendor_request_tickets_seq_uq UNIQUE (terminal_id, replenish_date, seq),
    CONSTRAINT vendor_request_tickets_code_uq UNIQUE (request_number, terminal_id, denom_code),
    CONSTRAINT vendor_request_tickets_inactive_chk CHECK (is_active OR (deactivated_at IS NOT NULL AND result IS NULL))
);
CREATE UNIQUE INDEX vendor_request_tickets_active_uq
    ON public.vendor_request_tickets (request_number, terminal_id) WHERE is_active;
COMMENT ON TABLE public.vendor_request_tickets IS
    'Tiket replenish: satu aktif per (request, ATM) = satu jalan. NNN global per (terminal_id, replenish_date), tidak dipakai ulang.';

-- Backfill (FR7.2, FR7.3): satu tiket aktif per (request, ATM) yang ada di item.
INSERT INTO public.vendor_request_tickets
    (request_number, terminal_id, denom_code, replenish_date, seq, ticket_number, created_at)
SELECT request_number, terminal_id, denom_code, rdate, seq,
       terminal_id || '_' || denom_code || '_' || to_char(rdate, 'YYYYMMDD') || '_' || lpad(seq::text, 3, '0'),
       created_at
FROM (
    SELECT vr.request_number, i.terminal_id,
           CASE WHEN count(DISTINCT i.denom) > 1 THEN 'MIX' ELSE (min(i.denom) / 1000)::text || 'K' END AS denom_code,
           COALESCE(vr.replenish_date, (vr.created_at AT TIME ZONE 'Asia/Jakarta')::date) AS rdate,
           vr.created_at,
           row_number() OVER (
               PARTITION BY i.terminal_id, COALESCE(vr.replenish_date, (vr.created_at AT TIME ZONE 'Asia/Jakarta')::date)
               ORDER BY vr.created_at, vr.id
           ) AS seq
    FROM public.vendor_request_items i
    JOIN public.vendor_requests vr ON vr.id = i.vendor_request_id
    GROUP BY vr.id, vr.request_number, i.terminal_id, vr.replenish_date, vr.created_at
) t;

-- 5. Pindahkan hasil laporan selesai ke tiket, lalu DROP (FR7.4)
UPDATE public.vendor_request_tickets t
SET result = r.result, result_updated_at = r.updated_at
FROM public.vendor_request_atm_results r
JOIN public.vendor_requests vr ON vr.id = r.vendor_request_id
WHERE t.request_number = vr.request_number
  AND t.terminal_id = r.terminal_id
  AND t.is_active;

DO $$
DECLARE
    old_n bigint;
    new_n bigint;
BEGIN
    SELECT count(*) INTO old_n FROM public.vendor_request_atm_results;
    SELECT count(*) INTO new_n FROM public.vendor_request_tickets WHERE result IS NOT NULL;
    IF old_n <> new_n THEN
        RAISE EXCEPTION '026: hasil laporan selesai tidak cocok (lama %, tiket %)', old_n, new_n;
    END IF;
END $$;

DROP TABLE public.vendor_request_atm_results;

COMMIT;
