-- 027_acm_vault_assignment.sql
-- Penetapan branch vault (penyedia uang) per ATM oleh tim ACM — Phase 2.2a
-- (.claude/sdlc/cit-acm-plan/spec.md + plan.md S1, accepted 2026-10-08).
--
--   * vendor_requests: status vault_assignment / vault_review / ready, vault_flow, vault_reviewed_*.
--   * dsr_daily_rows: flow 'saldo_akhir' (saldo akhir 00:00 per vault per denom, ETL S2).
--   * dsr_location_vault_maps: label lokasi DSR -> vendor_vaults (master data maker-checker).
--   * acm_areas / acm_area_branches / acm_area_members: Area ACM (ADMIN, langsung + audit).
--   * vendor_request_vault_plans: rekomendasi vault per (request, area).
--   * vendor_request_vault_assignments: satu branch vault per (request, ATM).
--   * Seed role ACM-USER / ACM-SPV + menu_features + role_permissions.
--
-- SAFETY (Sec 4 #7): additive kecuali dua CHECK yang di-drop+add dalam tx yang sama.
-- Satu tx. Forward-only: no down migration (project convention).
BEGIN;

-- 1. vendor_requests: status baru + penanda alur vault (spec FR4/FR5, plan P1)
ALTER TABLE public.vendor_requests DROP CONSTRAINT vendor_requests_status_chk;
ALTER TABLE public.vendor_requests ADD CONSTRAINT vendor_requests_status_chk CHECK (status = ANY (ARRAY[
    'draft'::text, 'pending_approval'::text, 'approved'::text, 'rejected'::text,
    'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text,
    'completion_pending'::text, 'vault_assignment'::text, 'vault_review'::text, 'ready'::text]));

ALTER TABLE public.vendor_requests
    ADD COLUMN vault_flow boolean NOT NULL DEFAULT false,
    ADD COLUMN vault_reviewed_by bigint REFERENCES public.users(id),
    ADD COLUMN vault_reviewed_at timestamptz,
    ADD COLUMN vault_rejection_reason text
        CONSTRAINT vendor_requests_vault_rejection_reason_chk CHECK (char_length(vault_rejection_reason) BETWEEN 1 AND 500);
COMMENT ON COLUMN public.vendor_requests.vault_flow IS
    'true = request di-approve setelah rilis 2.2a dan melewati penetapan vault ACM (laporan selesai ditolak -> ready). false = request lama (-> approved).';

-- 2. DSR: saldo akhir per vault per denom (spec FR1)
ALTER TABLE public.dsr_daily_rows DROP CONSTRAINT dsr_daily_rows_flow_chk;
ALTER TABLE public.dsr_daily_rows ADD CONSTRAINT dsr_daily_rows_flow_chk CHECK (flow = ANY (ARRAY[
    'saldo_awal'::text, 'penerimaan'::text, 'pengeluaran'::text, 'status_cadangan'::text, 'saldo_akhir'::text]));

-- 3. Mapping lokasi DSR -> vault (spec FR2)
CREATE TABLE public.dsr_location_vault_maps (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id       bigint NOT NULL REFERENCES public.vendors(id),
    dsr_location    text NOT NULL CONSTRAINT dsr_location_vault_maps_location_chk
                        CHECK (dsr_location = btrim(dsr_location) AND dsr_location <> ''),
    vendor_vault_id bigint NOT NULL REFERENCES public.vendor_vaults(id),
    is_active       boolean NOT NULL DEFAULT true,
    deleted_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX dsr_location_vault_maps_active_uq
    ON public.dsr_location_vault_maps (vendor_id, lower(dsr_location)) WHERE is_active;
CREATE INDEX dsr_location_vault_maps_vault_idx ON public.dsr_location_vault_maps (vendor_vault_id);
CREATE TRIGGER trg_dsr_location_vault_maps_set_updated_at BEFORE UPDATE ON public.dsr_location_vault_maps
    FOR EACH ROW WHEN (old.* IS DISTINCT FROM new.*) EXECUTE FUNCTION public.set_updated_at();
COMMENT ON TABLE public.dsr_location_vault_maps IS
    'Label lokasi blok DSR (dsr_daily_rows.location) per vendor -> vendor_vaults. DSR dikaitkan ke vendor via dsr_uploads.vendor = vendors.name.';

-- 4. Area ACM (spec FR7)
CREATE TABLE public.acm_areas (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL CONSTRAINT acm_areas_name_chk CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 100),
    is_active  boolean NOT NULL DEFAULT true,
    deleted_at timestamptz,
    created_by bigint NOT NULL REFERENCES public.users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX acm_areas_name_active_uq ON public.acm_areas (lower(name)) WHERE is_active;
CREATE TRIGGER trg_acm_areas_set_updated_at BEFORE UPDATE ON public.acm_areas
    FOR EACH ROW WHEN (old.* IS DISTINCT FROM new.*) EXECUTE FUNCTION public.set_updated_at();

-- Link table (tanpa soft-delete, seperti branch_coverage_areas); perubahan diaudit di service.
-- Satu branch hanya di satu area (FR7.2); menonaktifkan area melepas branch-nya di service.
CREATE TABLE public.acm_area_branches (
    acm_area_id      bigint NOT NULL REFERENCES public.acm_areas(id),
    vendor_branch_id bigint NOT NULL REFERENCES public.vendor_branches(id),
    created_by       bigint NOT NULL REFERENCES public.users(id),
    created_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (acm_area_id, vendor_branch_id),
    CONSTRAINT acm_area_branches_branch_uq UNIQUE (vendor_branch_id)
);

CREATE TABLE public.acm_area_members (
    acm_area_id bigint NOT NULL REFERENCES public.acm_areas(id),
    user_id     bigint NOT NULL REFERENCES public.users(id),
    created_by  bigint NOT NULL REFERENCES public.users(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (acm_area_id, user_id)
);
CREATE INDEX acm_area_members_user_idx ON public.acm_area_members (user_id);

-- 5. Rekomendasi vault per (request, area) (spec FR4)
CREATE TABLE public.vendor_request_vault_plans (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_request_id bigint NOT NULL REFERENCES public.vendor_requests(id),
    acm_area_id       bigint NOT NULL REFERENCES public.acm_areas(id),
    status            text NOT NULL DEFAULT 'draft' CONSTRAINT vendor_request_vault_plans_status_chk
                          CHECK (status IN ('draft', 'pending_acm_approval', 'acm_approved', 'cancelled')),
    submitted_by      bigint REFERENCES public.users(id),
    submitted_at      timestamptz,
    approved_by       bigint REFERENCES public.users(id),
    approved_at       timestamptz,
    rejected_by       bigint REFERENCES public.users(id),
    rejected_at       timestamptz,
    rejection_reason  text CONSTRAINT vendor_request_vault_plans_reason_chk CHECK (char_length(rejection_reason) BETWEEN 1 AND 500),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vendor_request_vault_plans_request_area_uq UNIQUE (vendor_request_id, acm_area_id)
);
CREATE INDEX vendor_request_vault_plans_area_status_idx ON public.vendor_request_vault_plans (acm_area_id, status);
CREATE TRIGGER trg_vendor_request_vault_plans_set_updated_at BEFORE UPDATE ON public.vendor_request_vault_plans
    FOR EACH ROW WHEN (old.* IS DISTINCT FROM new.*) EXECUTE FUNCTION public.set_updated_at();

-- 6. Satu branch vault per (request, ATM) (spec FR4.3). Baris draft di-replace (S1 spec: hard delete hanya saat draft, diaudit).
CREATE TABLE public.vendor_request_vault_assignments (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vault_plan_id       bigint NOT NULL REFERENCES public.vendor_request_vault_plans(id),
    vendor_request_id   bigint NOT NULL REFERENCES public.vendor_requests(id),
    terminal_id         text NOT NULL,
    replenish_branch_id bigint NOT NULL REFERENCES public.vendor_branches(id),
    vault_branch_id     bigint NOT NULL REFERENCES public.vendor_branches(id),
    tier                smallint NOT NULL CONSTRAINT vendor_request_vault_assignments_tier_chk CHECK (tier BETWEEN 1 AND 3),
    is_urgent           boolean NOT NULL DEFAULT false,
    urgent_reason       text,
    saldo_snapshot      jsonb,
    capacity_snapshot   jsonb,
    capacity_warning    boolean NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vendor_request_vault_assignments_atm_uq UNIQUE (vendor_request_id, terminal_id),
    CONSTRAINT vendor_request_vault_assignments_urgent_chk CHECK (
        (NOT is_urgent AND urgent_reason IS NULL)
        OR (is_urgent AND char_length(urgent_reason) BETWEEN 10 AND 500)),
    CONSTRAINT vendor_request_vault_assignments_tier3_chk CHECK (tier < 3 OR is_urgent)
);
CREATE INDEX vendor_request_vault_assignments_plan_idx ON public.vendor_request_vault_assignments (vault_plan_id);
CREATE INDEX vendor_request_vault_assignments_vault_idx ON public.vendor_request_vault_assignments (vault_branch_id);
CREATE TRIGGER trg_vendor_request_vault_assignments_set_updated_at BEFORE UPDATE ON public.vendor_request_vault_assignments
    FOR EACH ROW WHEN (old.* IS DISTINCT FROM new.*) EXECUTE FUNCTION public.set_updated_at();
COMMENT ON COLUMN public.vendor_request_vault_assignments.saldo_snapshot IS
    'Saldo branch vault per denom saat disimpan, {"100000": "123000000.00", ...}; null per denom = tidak diketahui.';

-- 7. Role + menu + permission (spec FR8). granted_by = ADMIN pertama (sama dengan seed baseline).
INSERT INTO public.roles (role, description) VALUES
    ('ACM-USER', 'ACM staff — menyusun penetapan branch vault per ATM'),
    ('ACM-SPV',  'ACM supervisor — approve penetapan branch vault area')
ON CONFLICT (role) DO NOTHING;

INSERT INTO public.menu_features (parent_id, key, label, kind, sort_order)
VALUES (NULL, 'cit', 'CIT', 'menu', 8)
ON CONFLICT (key) DO NOTHING;
INSERT INTO public.menu_features (parent_id, key, label, kind, sort_order)
SELECT id, 'cit.vault-plan', 'Penetapan Vault', 'feature', 0 FROM public.menu_features WHERE key = 'cit'
ON CONFLICT (key) DO NOTHING;
INSERT INTO public.menu_features (parent_id, key, label, kind, sort_order)
SELECT id, 'settings.acm-areas', 'Area ACM', 'feature', 1 FROM public.menu_features WHERE key = 'settings'
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.role_permissions (role_id, menu_feature_id, granted_by)
SELECT r.id, mf.id, (SELECT u.id FROM public.users u JOIN public.roles ar ON ar.id = u.role_id
                     WHERE ar.role = 'ADMIN' ORDER BY u.id LIMIT 1)
FROM public.roles r
JOIN public.menu_features mf ON mf.key = ANY (CASE r.role
        WHEN 'ADMIN'    THEN ARRAY['cit', 'cit.vault-plan', 'settings.acm-areas']
        WHEN 'ACM-USER' THEN ARRAY['cit', 'cit.vault-plan']
        WHEN 'ACM-SPV'  THEN ARRAY['cit', 'cit.vault-plan']
    END)
WHERE r.role IN ('ADMIN', 'ACM-USER', 'ACM-SPV')
ON CONFLICT (role_id, menu_feature_id) DO NOTHING;

COMMIT;
