-- vendor_requests / vendor_request_items: cash replenishment order to a CIT vendor,
-- composed from DMAA forecast rows (dmaa_atm_forecast), with a self-contained
-- maker-checker state machine (draft -> pending_approval -> approved/rejected -> ...).
-- See .kiro/specs/request-replenish-to-vendor/design.md for the full state machine,
-- API contract, and correctness properties.
--
-- WHY: DMAA forecast data already exists (dmaa_atm_forecast). This adds the two
-- tables that let ops staff turn selected forecast rows into an actionable,
-- auditable order for a CIT vendor.
--
-- SAFETY:
--   * New tables, no existing data affected.
--   * status uses TEXT + CHECK (no ENUM), consistent with the rest of the schema.
--   * The CHECK includes 'failed' even though requirements.md Req 1.3 lists a
--     shorter set without it -- Req 2.1's transition table defines
--     processing->failed, so the superset keeps the CHECK consistent with the
--     state machine actually implemented in the service layer (see design.md).
--   * created_by/approved_by/rejected_by FK users(id) ON DELETE RESTRICT: a
--     vendor request must always be traceable to real users; deleting a user
--     who created/approved/rejected a request is blocked rather than silently
--     orphaning the record.
--   * vendor_request_items FK vendor_request_id ON DELETE CASCADE: items have no
--     independent lifecycle outside their parent request.
--   * terminal_id is the actual identifier column name (matches dmaa_atm_forecast's
--     composite key), even though requirements.md calls it atm_id -- see design.md
--     "Terminology note". The API/frontend label it "ATM ID".
--   * Reuses the existing set_updated_at() trigger function (migration 014).

BEGIN;

CREATE TABLE IF NOT EXISTS public.vendor_requests
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    request_number    text        NOT NULL,
    forecast_date     date        NOT NULL,
    status            text        NOT NULL DEFAULT 'draft',
    notes             text,
    created_by        bigint      NOT NULL,
    approved_by       bigint,
    rejected_by       bigint,
    rejection_reason  text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    submitted_at      timestamptz,
    approved_at       timestamptz,
    rejected_at       timestamptz,
    CONSTRAINT vendor_requests_pkey PRIMARY KEY (id),
    CONSTRAINT vendor_requests_number_uq UNIQUE (request_number),
    CONSTRAINT vendor_requests_status_chk CHECK (status IN
        ('draft', 'pending_approval', 'approved', 'rejected', 'processing', 'completed', 'failed', 'cancelled')),
    CONSTRAINT vendor_requests_created_by_fk FOREIGN KEY (created_by)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT vendor_requests_approved_by_fk FOREIGN KEY (approved_by)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT,
    CONSTRAINT vendor_requests_rejected_by_fk FOREIGN KEY (rejected_by)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE RESTRICT
);

COMMENT ON TABLE public.vendor_requests
    IS 'Cash replenishment request to a CIT vendor, composed from DMAA forecast rows; state machine + maker-checker.';

COMMENT ON COLUMN public.vendor_requests.status
    IS 'draft | pending_approval | approved | rejected | processing | completed | failed | cancelled';

CREATE INDEX IF NOT EXISTS vendor_requests_status_idx
    ON public.vendor_requests (status);

CREATE INDEX IF NOT EXISTS vendor_requests_forecast_date_idx
    ON public.vendor_requests (forecast_date);

CREATE INDEX IF NOT EXISTS vendor_requests_created_by_idx
    ON public.vendor_requests (created_by);

CREATE TABLE IF NOT EXISTS public.vendor_request_items
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    vendor_request_id bigint      NOT NULL,
    terminal_id       text        NOT NULL,
    periode_pred      date        NOT NULL,
    denom             int         NOT NULL,
    amount_replenish  bigint      NOT NULL DEFAULT 0,
    amount_refund     bigint      NOT NULL DEFAULT 0,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vendor_request_items_pkey PRIMARY KEY (id),
    CONSTRAINT vendor_request_items_denom_chk CHECK (denom > 0),
    CONSTRAINT vendor_request_items_replenish_chk CHECK (amount_replenish >= 0),
    CONSTRAINT vendor_request_items_refund_chk CHECK (amount_refund >= 0),
    CONSTRAINT vendor_request_items_request_fk FOREIGN KEY (vendor_request_id)
        REFERENCES public.vendor_requests (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT vendor_request_items_uq UNIQUE (vendor_request_id, terminal_id, periode_pred, denom)
);

COMMENT ON TABLE public.vendor_request_items
    IS 'Line items of a vendor_request, each referencing an ATM/date/denom row from dmaa_atm_forecast.';

COMMENT ON COLUMN public.vendor_request_items.terminal_id
    IS 'ATM identifier; maps to requirements.md "atm_id" and dmaa_atm_forecast.terminal_id. Labeled "ATM ID" in the API/frontend.';

CREATE INDEX IF NOT EXISTS vendor_request_items_request_idx
    ON public.vendor_request_items (vendor_request_id);

CREATE INDEX IF NOT EXISTS vendor_request_items_terminal_idx
    ON public.vendor_request_items (terminal_id, periode_pred);

DROP TRIGGER IF EXISTS trg_vendor_requests_set_updated_at ON public.vendor_requests;
CREATE TRIGGER trg_vendor_requests_set_updated_at
    BEFORE UPDATE ON public.vendor_requests
    FOR EACH ROW
    WHEN (OLD.* IS DISTINCT FROM NEW.*)
    EXECUTE FUNCTION public.set_updated_at();

COMMIT;

-- ROLLBACK (forward-only shop, documented rather than shipped as a .down.sql -- a down
-- file in this directory would also be picked up by sqlc's schema glob):
--   DROP TRIGGER IF EXISTS trg_vendor_requests_set_updated_at ON public.vendor_requests;
--   DROP TABLE IF EXISTS public.vendor_request_items;
--   DROP TABLE IF EXISTS public.vendor_requests;
