-- 029_vendor_request_send.sql
-- Kirim Vendor Request ke vendor + terima/tolak di VendorPortal — Phase 2.2b
-- (.claude/sdlc/cit-send-vendor/spec.md + plan.md S1, accepted 2026-10-09).
--
--   * vendor_requests: status sent_to_vendor / vendor_accepted / vendor_rejected, vendor_sent, sent_at, vendor_accepted_at.
--   * vendor_request_vendor_parties: satu pihak per (request, branch, peran replenish|vault) + snapshot isi + keputusan.
--   * vendor_request_vendor_party_events: riwayat keputusan, append-only.
--
-- SAFETY (Sec 4 #7): additive kecuali CHECK status yang di-drop+add dalam tx yang sama. Tidak ada backfill:
-- request lama tetap ready/approved (spec S1). Satu tx. Forward-only: no down migration (project convention).
BEGIN;

-- 1. vendor_requests: status baru + penanda langkah vendor (spec FR2, FR4, FR6.3)
ALTER TABLE public.vendor_requests DROP CONSTRAINT vendor_requests_status_chk;
ALTER TABLE public.vendor_requests ADD CONSTRAINT vendor_requests_status_chk CHECK (status = ANY (ARRAY[
    'draft'::text, 'pending_approval'::text, 'approved'::text, 'rejected'::text,
    'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text,
    'completion_pending'::text, 'vault_assignment'::text, 'vault_review'::text, 'ready'::text,
    'sent_to_vendor'::text, 'vendor_accepted'::text, 'vendor_rejected'::text]));

ALTER TABLE public.vendor_requests
    ADD COLUMN vendor_sent boolean NOT NULL DEFAULT false,
    ADD COLUMN sent_at timestamptz,
    ADD COLUMN vendor_accepted_at timestamptz;
COMMENT ON COLUMN public.vendor_requests.vendor_sent IS
    'true = request pernah dikirim ke vendor (2.2b); laporan selesai ditolak -> vendor_accepted. false = ready/approved lama.';
COMMENT ON COLUMN public.vendor_requests.sent_at IS 'Waktu kirim (ulang) terakhir ke vendor.';

-- 2. Pihak vendor per request (spec FR1, FR4). Tidak pernah dihapus: pihak yang hilang -> withdrawn.
CREATE TABLE public.vendor_request_vendor_parties (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_request_id bigint NOT NULL REFERENCES public.vendor_requests(id),
    vendor_branch_id  bigint NOT NULL REFERENCES public.vendor_branches(id),
    role              text NOT NULL CONSTRAINT vendor_request_vendor_parties_role_chk CHECK (role IN ('replenish', 'vault')),
    status            text NOT NULL DEFAULT 'pending' CONSTRAINT vendor_request_vendor_parties_status_chk
                          CHECK (status IN ('pending', 'accepted', 'rejected', 'withdrawn')),
    content           jsonb NOT NULL,
    sent_at           timestamptz NOT NULL DEFAULT now(),
    decided_by        bigint REFERENCES public.users(id),
    decided_at        timestamptz,
    rejection_reason  text CONSTRAINT vendor_request_vendor_parties_reason_chk CHECK (char_length(rejection_reason) BETWEEN 10 AND 500),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT vendor_request_vendor_parties_uq UNIQUE (vendor_request_id, vendor_branch_id, role),
    CONSTRAINT vendor_request_vendor_parties_decision_chk CHECK (
        (status IN ('accepted', 'rejected')) = (decided_by IS NOT NULL AND decided_at IS NOT NULL)),
    CONSTRAINT vendor_request_vendor_parties_rejected_chk CHECK ((status = 'rejected') = (rejection_reason IS NOT NULL))
);
CREATE INDEX vendor_request_vendor_parties_branch_status_idx ON public.vendor_request_vendor_parties (vendor_branch_id, status);
CREATE TRIGGER trg_vendor_request_vendor_parties_set_updated_at BEFORE UPDATE ON public.vendor_request_vendor_parties
    FOR EACH ROW WHEN (old.* IS DISTINCT FROM new.*) EXECUTE FUNCTION public.set_updated_at();
COMMENT ON COLUMN public.vendor_request_vendor_parties.content IS
    'Snapshot isi yang dilihat vendor saat dikirim (ATM, nominal per denom, pihak lawan). Tidak memuat data internal (saldo, tier, urgent, harga).';

-- 3. Riwayat keputusan (spec FR8.2). Append-only.
CREATE TABLE public.vendor_request_vendor_party_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id   bigint NOT NULL REFERENCES public.vendor_request_vendor_parties(id),
    event      text NOT NULL CONSTRAINT vendor_request_vendor_party_events_event_chk
                   CHECK (event IN ('sent', 'resent', 'accepted', 'rejected', 'withdrawn', 'cancelled')),
    actor_id   bigint NOT NULL REFERENCES public.users(id),
    reason     text,
    content    jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX vendor_request_vendor_party_events_party_idx ON public.vendor_request_vendor_party_events (party_id, created_at);

COMMIT;
