"""Generate migrations 031 (vendor_packages) and 032 (atm_vendor_packages +
backfills) from document/MASTER_ATM_ESQ.csv.xlsx.

One-off generator (not runtime code). Re-run to regenerate the SQL if the source
file changes. Emits set-based, idempotent SQL that joins to already-seeded
vendors / vendor_branches / atms by natural key (never hardcodes IDENTITY ids).

Decisions applied (see .kiro/specs/update-cit-forecast-browser/
seed-proposal-atm-vendor-packages.md):
  1C  vendor_packages keyed (vendor_branch, PAKET); code='PAKET N';
      priority_class='ALL' sentinel (real per-ATM value goes on atms.priority_class,
      migration 030). PriorityClass + PAKET are per-ATM.
  2B  vendor_packages.price = 0  (placeholder, ESQ has no price; flagged TODO).
  D3  atm_vendor_packages effective_start_date = 2026-01-01, is_active = true,
      effective_end_date = NULL.
  Skip rows with null/blank vendor, branch, or PAKET (no atm_vendor_packages link).
"""

import openpyxl
from collections import OrderedDict

SRC = r"document/MASTER_ATM_ESQ.csv.xlsx"
OUT_031 = r"backend/migrations/031_seed_vendor_packages.sql"
OUT_032 = r"backend/migrations/032_seed_atm_vendor_packages.sql"
EFFECTIVE_START = "2026-01-01"


def sql_str(v):
    """Single-quote a string for SQL, escaping embedded quotes. None -> NULL."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def norm_vendor(v):
    if v is None:
        return None
    v = str(v).strip()
    if not v or v.upper() == "NULL":
        return None
    return v.upper()  # vendors.code is uppercase for every vendor (e.g. Abacus -> ABACUS)


def norm_text(v):
    if v is None:
        return None
    v = str(v).strip()
    return None if not v or v.upper() == "NULL" else v


def norm_paket(v):
    v = norm_text(v)
    if v is None:
        return None
    return v.upper()  # 'Paket 5' -> 'PAKET 5'


def load_rows():
    wb = openpyxl.load_workbook(SRC, read_only=True, data_only=True)
    ws = wb[wb.sheetnames[0]]
    it = ws.iter_rows(values_only=True)
    header = list(next(it))
    idx = {h: i for i, h in enumerate(header)}
    rows = []
    for r in it:
        if not any(c is not None for c in r):
            continue
        rows.append({
            "term": norm_text(r[idx["TermId"]]),      # coerce numeric -> text via str()
            "vendor": norm_vendor(r[idx["FLMVendor"]]),
            "branch": norm_text(r[idx["FLMVendorSubRegion"]]),
            "region": norm_text(r[idx["FLMVendorRegion"]]),
            "paket": norm_paket(r[idx["PAKET"]]),
            "prio": norm_text(r[idx["PriorityClass"]]),
            "escrow": norm_text(r[idx["Escrow"]]),
        })
    return rows


def main():
    rows = load_rows()

    # ---- 031: distinct (vendor, branch, paket) packages ------------------
    packages = OrderedDict()  # (vendor, branch, paket) -> True
    for r in rows:
        if r["vendor"] and r["branch"] and r["paket"]:
            packages[(r["vendor"], r["branch"], r["paket"])] = True

    pkg_values = ",\n".join(
        f"    ({sql_str(v)}, {sql_str(b)}, {sql_str(p)})"
        for (v, b, p) in packages
    )

    sql031 = f"""-- Seed vendor_packages from MASTER_ATM_ESQ (decision 1C + 2B).
--
-- WHY: vendor_packages was never seeded (only an archived dummy insert existed with
-- fake VND001/VND002 codes). This seeds one package per (vendor_branch, PAKET) combo
-- observed in document/MASTER_ATM_ESQ.csv.xlsx, so atm_vendor_packages (migration 032)
-- has real rows to link ATMs to. Generated by scripts/gen_master_atm_esq_seed.py.
--
-- MODEL (1C):
--   * code           = the PAKET label ('PAKET 3' | 'PAKET 4' | 'PAKET 5').
--   * priority_class = 'ALL' sentinel. PriorityClass is per-ATM (varies within a branch),
--     so the real value lives on atms.priority_class (migration 030), NOT here. The column
--     is NOT NULL, hence the sentinel rather than leaving it blank.
--   * price          = 0 PLACEHOLDER (2B). ESQ carries no price. TODO: backfill real
--     per-PAKET prices when a price source (contract/invoice) is available.
--
-- SAFETY:
--   * Idempotent: WHERE NOT EXISTS on the (vendor_branch_id, code) unique key.
--   * Joins to seeded vendors (005) + vendor_branches (006) by natural key
--     (vendor.code, branch_name) -- never hardcodes IDENTITY ids.
--   * Rows whose vendor/branch did not seed are silently skipped by the INNER JOINs.
--
-- ROLLBACK (documented, forward-only): DELETE FROM public.vendor_packages
--   WHERE code IN ('PAKET 3','PAKET 4','PAKET 5') AND priority_class = 'ALL';

BEGIN;

INSERT INTO public.vendor_packages (vendor_branch_id, code, priority_class, price)
SELECT vb.id, s.paket_code, 'ALL', 0
FROM (
    VALUES
{pkg_values}
) AS s(vendor_code, branch_name, paket_code)
JOIN public.vendors v         ON v.code = s.vendor_code
JOIN public.vendor_branches vb ON vb.vendor_id = v.id AND vb.branch_name = s.branch_name
WHERE NOT EXISTS (
    SELECT 1 FROM public.vendor_packages vp
    WHERE vp.vendor_branch_id = vb.id AND vp.code = s.paket_code
);

COMMIT;
"""

    # ---- 032: per-ATM backfills + atm_vendor_packages links --------------
    # branch region: one region per (vendor, branch); flag conflicts
    branch_region = {}
    conflicts = {}
    for r in rows:
        if r["vendor"] and r["branch"] and r["region"]:
            key = (r["vendor"], r["branch"])
            prev = branch_region.get(key)
            if prev is None:
                branch_region[key] = r["region"]
            elif prev != r["region"]:
                conflicts.setdefault(key, {prev}).add(r["region"])

    region_values = ",\n".join(
        f"    ({sql_str(v)}, {sql_str(b)}, {sql_str(reg)})"
        for (v, b), reg in branch_region.items()
    )

    # per-ATM escrow + priority + its package link (last-wins per terminal)
    atm_rows = OrderedDict()  # term -> (vendor, branch, paket, prio, escrow)
    for r in rows:
        if not r["term"]:
            continue
        atm_rows[r["term"]] = (r["vendor"], r["branch"], r["paket"], r["prio"], r["escrow"])

    atm_attr_values = ",\n".join(
        f"    ({sql_str(t)}, {sql_str(prio)}, {sql_str(esc)})"
        for t, (v, b, p, prio, esc) in atm_rows.items()
        if prio is not None or esc is not None
    )

    link_values = ",\n".join(
        f"    ({sql_str(t)}, {sql_str(v)}, {sql_str(b)}, {sql_str(p)})"
        for t, (v, b, p, prio, esc) in atm_rows.items()
        if v and b and p
    )

    conflict_note = ""
    if conflicts:
        lines = "\n".join(
            f"--   {v} / {b}: {sorted(regs)}" for (v, b), regs in conflicts.items()
        )
        conflict_note = (
            "--\n-- REGION CONFLICTS (branch had >1 FLMVendorRegion; first-seen kept, review):\n"
            + lines + "\n"
        )

    sql032 = f"""-- Backfill vendor_branches.region, atms.escrow_account, atms.priority_class and
-- seed atm_vendor_packages from MASTER_ATM_ESQ. Depends on migrations 030 (columns)
-- and 031 (vendor_packages). Generated by scripts/gen_master_atm_esq_seed.py.
--
-- WHY: migration 030 added the columns; 031 seeded the packages. This populates the
-- per-ATM values and the ATM->package link that powers "FLM Vendor" / "FLM Vendor
-- Region" (forecast browser) and future assignment/reconciliation features.
--
-- MODEL / DECISIONS: effective_start_date = {EFFECTIVE_START} (D3; ESQ has no date),
-- is_active = true, effective_end_date = NULL. priority_class per ATM (1C).
--
-- SAFETY:
--   * All idempotent: backfills only overwrite when the source has a value; the link
--     INSERT uses WHERE NOT EXISTS on (atm_id, vendor_package_id, effective_start_date).
--   * Natural-key joins only (terminal_id, vendor.code, branch_name, package code).
--   * ATMs/branches that did not seed are skipped by INNER JOINs; ATMs with null PAKET
--     get no link row (they render "-" in the UI -- honest, per proposal).
{conflict_note}--
-- ROLLBACK (documented, forward-only):
--   DELETE FROM public.atm_vendor_packages WHERE effective_start_date = DATE '{EFFECTIVE_START}';
--   UPDATE public.vendor_branches SET region = NULL;
--   UPDATE public.atms SET escrow_account = NULL, priority_class = NULL;

BEGIN;

-- 1) vendor_branches.region  <- FLMVendorRegion (one per branch)
UPDATE public.vendor_branches vb
SET region = s.region
FROM (
    VALUES
{region_values}
) AS s(vendor_code, branch_name, region),
    public.vendors v
WHERE v.code = s.vendor_code
  AND vb.vendor_id = v.id
  AND vb.branch_name = s.branch_name;

-- 2) atms.priority_class + atms.escrow_account  <- per-ATM source values
UPDATE public.atms a
SET priority_class = COALESCE(s.priority_class, a.priority_class),
    escrow_account = COALESCE(s.escrow_account, a.escrow_account)
FROM (
    VALUES
{atm_attr_values}
) AS s(terminal_id, priority_class, escrow_account)
WHERE a.terminal_id = s.terminal_id;

-- 3) atm_vendor_packages  <- link each ATM to its (branch, PAKET) package
INSERT INTO public.atm_vendor_packages
    (atm_id, vendor_package_id, effective_start_date, effective_end_date, is_active)
SELECT a.id, vp.id, DATE '{EFFECTIVE_START}', NULL, true
FROM (
    VALUES
{link_values}
) AS s(terminal_id, vendor_code, branch_name, paket_code)
JOIN public.atms a             ON a.terminal_id = s.terminal_id
JOIN public.vendors v          ON v.code = s.vendor_code
JOIN public.vendor_branches vb ON vb.vendor_id = v.id AND vb.branch_name = s.branch_name
JOIN public.vendor_packages vp ON vp.vendor_branch_id = vb.id AND vp.code = s.paket_code
WHERE NOT EXISTS (
    SELECT 1 FROM public.atm_vendor_packages avp
    WHERE avp.atm_id = a.id AND avp.vendor_package_id = vp.id
      AND avp.effective_start_date = DATE '{EFFECTIVE_START}'
);

COMMIT;
"""

    with open(OUT_031, "w", encoding="utf-8", newline="\n") as f:
        f.write(sql031)
    with open(OUT_032, "w", encoding="utf-8", newline="\n") as f:
        f.write(sql032)

    print(f"packages (031 rows): {len(packages)}")
    print(f"branch region backfills: {len(branch_region)}")
    print(f"atm attr backfills: {sum(1 for _, (v,b,p,prio,esc) in atm_rows.items() if prio or esc)}")
    print(f"atm_vendor_packages links (032): {sum(1 for _, (v,b,p,prio,esc) in atm_rows.items() if v and b and p)}")
    print(f"region conflicts: {len(conflicts)} {list(conflicts.keys())}")
    print(f"wrote {OUT_031} and {OUT_032}")


if __name__ == "__main__":
    main()
