// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atm_portal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countATMsWithCashPos = `-- name: CountATMsWithCashPos :one
WITH sub AS (
    SELECT
        a.terminal_id,
        l.name AS location_name,
        a.machine_type,
        a.brand,
        a.deployment_type,
        r.region,
        lcp.replenish_date AS last_replenish_date,
        CASE
            WHEN a.low_threshold_amount IS NULL THEN 'unconfigured'
            WHEN lcp.refund_total IS NULL THEN 'no_data'
            WHEN a.critical_threshold_amount IS NOT NULL
                 AND lcp.refund_total <= a.critical_threshold_amount THEN 'critical'
            WHEN lcp.refund_total <= a.low_threshold_amount THEN 'low'
            ELSE 'normal'
        END AS status
    FROM atms a
    JOIN locations l ON l.id = a.location_id
    JOIN regions r ON r.id = l.region_id
    LEFT JOIN LATERAL (
        SELECT cp.replenish_date, cp.replenish_time, cp.refund_total
        FROM itm_replenish cp
        WHERE cp.terminal_id = a.terminal_id
        ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
        LIMIT 1
    ) lcp ON true
    WHERE a.is_active = true
      AND a.deleted_at IS NULL
)
SELECT COUNT(*)
FROM sub
WHERE
    ($1::text = ''
        OR sub.terminal_id ILIKE '%' || $1::text || '%'
        OR sub.location_name ILIKE '%' || $1::text || '%')
    AND ($2::text = 'all'
        OR sub.status = ANY(string_to_array($2::text, ',')))
    AND ($3::text = ''
        OR sub.machine_type = ANY(string_to_array($3::text, ',')))
    AND ($4::text = ''
        OR sub.brand = ANY(string_to_array($4::text, ',')))
    AND ($5::text = '' OR sub.deployment_type = $5::text)
    AND ($6::text = '' OR sub.region ILIKE '%' || $6::text || '%')
    AND ($7::text = '' OR sub.last_replenish_date >= $7::date)
    AND ($8::text = '' OR sub.last_replenish_date <= $8::date)
`

type CountATMsWithCashPosParams struct {
	Search         string `json:"search"`
	Status         string `json:"status"`
	MachineType    string `json:"machine_type"`
	Brand          string `json:"brand"`
	DeploymentType string `json:"deployment_type"`
	Region         string `json:"region"`
	DateFrom       string `json:"date_from"`
	DateTo         string `json:"date_to"`
}

// Mirrors ListATMsWithCashPos's FROM/JOIN/WHERE (including all dynamic
// filters) exactly, minus ORDER BY/LIMIT/OFFSET, so the count matches the
// filtered result set for pagination math (Property 6).
func (q *Queries) CountATMsWithCashPos(ctx context.Context, arg CountATMsWithCashPosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countATMsWithCashPos,
		arg.Search,
		arg.Status,
		arg.MachineType,
		arg.Brand,
		arg.DeploymentType,
		arg.Region,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCashposByTerminal = `-- name: CountCashposByTerminal :one
SELECT COUNT(*)
FROM itm_cashpos
WHERE terminal_id = $1::text
  AND ($2::text = '' OR cashpos_date >= $2::date)
  AND ($3::text = '' OR cashpos_date <= $3::date)
`

type CountCashposByTerminalParams struct {
	TerminalID string `json:"terminal_id"`
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
}

// Mirrors ListCashposByTerminal filters for pagination total.
func (q *Queries) CountCashposByTerminal(ctx context.Context, arg CountCashposByTerminalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCashposByTerminal, arg.TerminalID, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItmCashpos = `-- name: CountItmCashpos :one
SELECT COUNT(*)
FROM itm_cashpos c
WHERE
    ($1::text = ''
        OR c.terminal_id ILIKE '%' || $1::text || '%'
        OR c.branch_code ILIKE '%' || $1::text || '%'
        OR c.teller_id ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR c.cashpos_date >= $2::date)
    AND ($3::text = '' OR c.cashpos_date <= $3::date)
`

type CountItmCashposParams struct {
	Search   string `json:"search"`
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

// Mirrors ListItmCashpos filters for pagination total.
func (q *Queries) CountItmCashpos(ctx context.Context, arg CountItmCashposParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItmCashpos, arg.Search, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReplenishByTerminal = `-- name: CountReplenishByTerminal :one
SELECT COUNT(*)
FROM itm_replenish
WHERE terminal_id = $1::text
  AND ($2::text = '' OR replenish_date >= $2::date)
  AND ($3::text = '' OR replenish_date <= $3::date)
`

type CountReplenishByTerminalParams struct {
	TerminalID string `json:"terminal_id"`
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
}

// Mirrors ListReplenishByTerminal filters for pagination total.
func (q *Queries) CountReplenishByTerminal(ctx context.Context, arg CountReplenishByTerminalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReplenishByTerminal, arg.TerminalID, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getATMByTerminalID = `-- name: GetATMByTerminalID :one
SELECT
    a.terminal_id,
    l.name AS location_name,
    l.address_line1 AS address,
    a.machine_type,
    a.brand,
    a.model,
    a.deployment_type,
    a.operation_hours,
    a.capacity_amount,
    a.low_threshold_amount,
    a.critical_threshold_amount,
    a.is_active
FROM atms a
JOIN locations l ON l.id = a.location_id
WHERE a.terminal_id = $1::text
  AND a.is_active = true
  AND a.deleted_at IS NULL
`

type GetATMByTerminalIDRow struct {
	TerminalID              string         `json:"terminal_id"`
	LocationName            string         `json:"location_name"`
	Address                 string         `json:"address"`
	MachineType             string         `json:"machine_type"`
	Brand                   string         `json:"brand"`
	Model                   string         `json:"model"`
	DeploymentType          string         `json:"deployment_type"`
	OperationHours          string         `json:"operation_hours"`
	CapacityAmount          pgtype.Numeric `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric `json:"critical_threshold_amount"`
	IsActive                bool           `json:"is_active"`
}

// ATM Profile master data (atm-profile spec). Only active, non-deleted ATMs
// are visible — matches ListATMsWithCashPos's WHERE clause so a terminal
// absent from the list is also absent here (consistent 404).
func (q *Queries) GetATMByTerminalID(ctx context.Context, terminalID string) (GetATMByTerminalIDRow, error) {
	row := q.db.QueryRow(ctx, getATMByTerminalID, terminalID)
	var i GetATMByTerminalIDRow
	err := row.Scan(
		&i.TerminalID,
		&i.LocationName,
		&i.Address,
		&i.MachineType,
		&i.Brand,
		&i.Model,
		&i.DeploymentType,
		&i.OperationHours,
		&i.CapacityAmount,
		&i.LowThresholdAmount,
		&i.CriticalThresholdAmount,
		&i.IsActive,
	)
	return i, err
}

const getATMSummary = `-- name: GetATMSummary :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE sub.status = 'critical') AS critical,
    COUNT(*) FILTER (WHERE sub.status = 'low') AS low,
    COUNT(*) FILTER (WHERE sub.status = 'normal') AS normal,
    COUNT(*) FILTER (WHERE sub.status = 'unconfigured') AS unconfigured,
    COUNT(*) FILTER (WHERE sub.status = 'no_data') AS no_data
FROM (
    SELECT
        CASE
            WHEN a.low_threshold_amount IS NULL THEN 'unconfigured'
            WHEN lcp.refund_total IS NULL THEN 'no_data'
            WHEN a.critical_threshold_amount IS NOT NULL
                 AND lcp.refund_total <= a.critical_threshold_amount THEN 'critical'
            WHEN lcp.refund_total <= a.low_threshold_amount THEN 'low'
            ELSE 'normal'
        END AS status
    FROM atms a
    LEFT JOIN LATERAL (
        SELECT cp.refund_total
        FROM itm_replenish cp
        WHERE cp.terminal_id = a.terminal_id
        ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
        LIMIT 1
    ) lcp ON true
    WHERE a.is_active = true
      AND a.deleted_at IS NULL
) sub
`

type GetATMSummaryRow struct {
	Total        int64 `json:"total"`
	Critical     int64 `json:"critical"`
	Low          int64 `json:"low"`
	Normal       int64 `json:"normal"`
	Unconfigured int64 `json:"unconfigured"`
	NoData       int64 `json:"no_data"`
}

// Global status counts across all active ATMs, independent of any list
// filters (Property 10). Does not join locations/regions since it only
// aggregates status, and does not accept filter args.
func (q *Queries) GetATMSummary(ctx context.Context) (GetATMSummaryRow, error) {
	row := q.db.QueryRow(ctx, getATMSummary)
	var i GetATMSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Critical,
		&i.Low,
		&i.Normal,
		&i.Unconfigured,
		&i.NoData,
	)
	return i, err
}

const getLastUpdated = `-- name: GetLastUpdated :one
SELECT
    (replenish_date + replenish_time)::timestamp AS last_updated
FROM itm_replenish
ORDER BY replenish_date DESC, replenish_time DESC
LIMIT 1
`

// Most recent replenish_date + replenish_time across all itm_replenish
// records, used for the data-freshness indicator. Returns NULL when no
// cashpos records exist yet.
func (q *Queries) GetLastUpdated(ctx context.Context) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getLastUpdated)
	var last_updated pgtype.Timestamp
	err := row.Scan(&last_updated)
	return last_updated, err
}

const getLatestReplenishForTerminal = `-- name: GetLatestReplenishForTerminal :one
SELECT refund_total
FROM itm_replenish
WHERE terminal_id = $1::text
ORDER BY replenish_date DESC, replenish_time DESC
LIMIT 1
`

// Latest itm_replenish record's refund_total for the profile header's
// status computation (same precedence CASE as ListATMsWithCashPos, applied
// in the service layer). Returns pgx.ErrNoRows when the terminal has no
// replenish history yet (status = "no_data").
func (q *Queries) GetLatestReplenishForTerminal(ctx context.Context, terminalID string) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLatestReplenishForTerminal, terminalID)
	var refund_total pgtype.Numeric
	err := row.Scan(&refund_total)
	return refund_total, err
}

const listATMsWithCashPos = `-- name: ListATMsWithCashPos :many
WITH sub AS (
    SELECT
        a.terminal_id,
        l.name AS location_name,
        l.address_line1 AS address,
        a.machine_type,
        a.brand,
        a.deployment_type,
        r.region,
        a.low_threshold_amount,
        a.critical_threshold_amount,
        lcp.replenish_date AS last_replenish_date,
        lcp.replenish_time AS last_replenish_time,
        lcp.refund_total,
        lcp.replenish_total,
        lcp.escrow,
        CASE
            WHEN a.low_threshold_amount IS NULL THEN 'unconfigured'
            WHEN lcp.refund_total IS NULL THEN 'no_data'
            WHEN a.critical_threshold_amount IS NOT NULL
                 AND lcp.refund_total <= a.critical_threshold_amount THEN 'critical'
            WHEN lcp.refund_total <= a.low_threshold_amount THEN 'low'
            ELSE 'normal'
        END AS status
    FROM atms a
    JOIN locations l ON l.id = a.location_id
    JOIN regions r ON r.id = l.region_id
    LEFT JOIN LATERAL (
        SELECT
            cp.replenish_date,
            cp.replenish_time,
            cp.refund_total,
            cp.replenish_total,
            cp.escrow
        FROM itm_replenish cp
        WHERE cp.terminal_id = a.terminal_id
        ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
        LIMIT 1
    ) lcp ON true
    WHERE a.is_active = true
      AND a.deleted_at IS NULL
)
SELECT
    sub.terminal_id,
    sub.location_name,
    sub.address,
    sub.machine_type,
    sub.brand,
    sub.deployment_type,
    sub.low_threshold_amount,
    sub.critical_threshold_amount,
    sub.last_replenish_date,
    sub.last_replenish_time,
    sub.refund_total,
    sub.replenish_total,
    sub.escrow,
    sub.status
FROM sub
WHERE
    ($1::text = ''
        OR sub.terminal_id ILIKE '%' || $1::text || '%'
        OR sub.location_name ILIKE '%' || $1::text || '%')
    AND ($2::text = 'all'
        OR sub.status = ANY(string_to_array($2::text, ',')))
    AND ($3::text = ''
        OR sub.machine_type = ANY(string_to_array($3::text, ',')))
    AND ($4::text = ''
        OR sub.brand = ANY(string_to_array($4::text, ',')))
    AND ($5::text = '' OR sub.deployment_type = $5::text)
    AND ($6::text = '' OR sub.region ILIKE '%' || $6::text || '%')
    AND ($7::text = '' OR sub.last_replenish_date >= $7::date)
    AND ($8::text = '' OR sub.last_replenish_date <= $8::date)
ORDER BY
    CASE WHEN $9::text = 'terminal_id' AND $10::text = 'asc' THEN sub.terminal_id END ASC,
    CASE WHEN $9::text = 'terminal_id' AND $10::text = 'desc' THEN sub.terminal_id END DESC,
    CASE WHEN $9::text = 'location' AND $10::text = 'asc' THEN sub.location_name END ASC,
    CASE WHEN $9::text = 'location' AND $10::text = 'desc' THEN sub.location_name END DESC,
    CASE WHEN $9::text = 'last_replenish_date' AND $10::text = 'asc' THEN sub.last_replenish_date END ASC,
    CASE WHEN $9::text = 'last_replenish_date' AND $10::text = 'desc' THEN sub.last_replenish_date END DESC,
    CASE WHEN $9::text = 'refund_total' AND $10::text = 'asc' THEN sub.refund_total END ASC,
    CASE WHEN $9::text = 'refund_total' AND $10::text = 'desc' THEN sub.refund_total END DESC,
    CASE WHEN $9::text = 'replenish_total' AND $10::text = 'asc' THEN sub.replenish_total END ASC,
    CASE WHEN $9::text = 'replenish_total' AND $10::text = 'desc' THEN sub.replenish_total END DESC,
    CASE WHEN $9::text = 'status' AND $10::text = 'asc' THEN sub.status END ASC,
    CASE WHEN $9::text = 'status' AND $10::text = 'desc' THEN sub.status END DESC,
    sub.terminal_id ASC
LIMIT $12::int OFFSET ($11::int - 1) * $12::int
`

type ListATMsWithCashPosParams struct {
	Search         string `json:"search"`
	Status         string `json:"status"`
	MachineType    string `json:"machine_type"`
	Brand          string `json:"brand"`
	DeploymentType string `json:"deployment_type"`
	Region         string `json:"region"`
	DateFrom       string `json:"date_from"`
	DateTo         string `json:"date_to"`
	SortBy         string `json:"sort_by"`
	SortOrder      string `json:"sort_order"`
	Page           int32  `json:"page"`
	PageSize       int32  `json:"page_size"`
}

type ListATMsWithCashPosRow struct {
	TerminalID              string         `json:"terminal_id"`
	LocationName            string         `json:"location_name"`
	Address                 string         `json:"address"`
	MachineType             string         `json:"machine_type"`
	Brand                   string         `json:"brand"`
	DeploymentType          string         `json:"deployment_type"`
	LowThresholdAmount      pgtype.Numeric `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric `json:"critical_threshold_amount"`
	LastReplenishDate       pgtype.Date    `json:"last_replenish_date"`
	LastReplenishTime       pgtype.Time    `json:"last_replenish_time"`
	RefundTotal             pgtype.Numeric `json:"refund_total"`
	ReplenishTotal          pgtype.Numeric `json:"replenish_total"`
	Escrow                  pgtype.Numeric `json:"escrow"`
	Status                  string         `json:"status"`
}

// Paginated, filtered, sorted ATM list joined with the latest itm_replenish
// record per terminal. location_name/address/region are NOT columns on
// atms — they require joining locations (via atms.location_id) and
// regions (via locations.region_id). Status is computed here via a CASE
// expression (Property 1 precedence: unconfigured > no_data > critical >
// low > normal) inside the `sub` subquery so it can be filtered on and
// sorted by in the outer query — a SELECT-list alias cannot be referenced
// directly in the WHERE clause that produced it.
//
// All filter args are plain (non-nullable) strings matching
// ListATMsParams in design.md: an empty string ("") or "all" (for status)
// means "no filter applied", so callers always pass concrete values,
// never NULL. status is comma-separated multi-select (requirements.md Req
// 89.3), same pattern as machine_type/brand — corrects an earlier
// single-value assumption carried over from design.md's API contract table.
func (q *Queries) ListATMsWithCashPos(ctx context.Context, arg ListATMsWithCashPosParams) ([]ListATMsWithCashPosRow, error) {
	rows, err := q.db.Query(ctx, listATMsWithCashPos,
		arg.Search,
		arg.Status,
		arg.MachineType,
		arg.Brand,
		arg.DeploymentType,
		arg.Region,
		arg.DateFrom,
		arg.DateTo,
		arg.SortBy,
		arg.SortOrder,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListATMsWithCashPosRow{}
	for rows.Next() {
		var i ListATMsWithCashPosRow
		if err := rows.Scan(
			&i.TerminalID,
			&i.LocationName,
			&i.Address,
			&i.MachineType,
			&i.Brand,
			&i.DeploymentType,
			&i.LowThresholdAmount,
			&i.CriticalThresholdAmount,
			&i.LastReplenishDate,
			&i.LastReplenishTime,
			&i.RefundTotal,
			&i.ReplenishTotal,
			&i.Escrow,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashposByTerminal = `-- name: ListCashposByTerminal :many
SELECT
    id, file_id, cashpos_date, terminal_id, machine_type, teller_id, branch_code,
    starting_cash_10k, cash_in_10k, cash_out_10k, cash_position_10k,
    starting_cash_20k, cash_in_20k, cash_out_20k, cash_position_20k,
    starting_cash_50k, cash_in_50k, cash_out_50k, cash_position_50k,
    starting_cash_100k, cash_in_100k, cash_out_100k, cash_position_100k,
    position_source, created_at
FROM itm_cashpos
WHERE terminal_id = $1::text
  AND ($2::text = '' OR cashpos_date >= $2::date)
  AND ($3::text = '' OR cashpos_date <= $3::date)
ORDER BY cashpos_date DESC, id DESC
LIMIT $5::int
OFFSET ($4::int - 1) * $5::int
`

type ListCashposByTerminalParams struct {
	TerminalID string `json:"terminal_id"`
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
	Page       int32  `json:"page"`
	PageSize   int32  `json:"page_size"`
}

// Paginated cash position history for a single ATM (atm-profile spec),
// optional inclusive date_from/date_to filtering, newest first.
func (q *Queries) ListCashposByTerminal(ctx context.Context, arg ListCashposByTerminalParams) ([]ItmCashpo, error) {
	rows, err := q.db.Query(ctx, listCashposByTerminal,
		arg.TerminalID,
		arg.DateFrom,
		arg.DateTo,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItmCashpo{}
	for rows.Next() {
		var i ItmCashpo
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.CashposDate,
			&i.TerminalID,
			&i.MachineType,
			&i.TellerID,
			&i.BranchCode,
			&i.StartingCash10k,
			&i.CashIn10k,
			&i.CashOut10k,
			&i.CashPosition10k,
			&i.StartingCash20k,
			&i.CashIn20k,
			&i.CashOut20k,
			&i.CashPosition20k,
			&i.StartingCash50k,
			&i.CashIn50k,
			&i.CashOut50k,
			&i.CashPosition50k,
			&i.StartingCash100k,
			&i.CashIn100k,
			&i.CashOut100k,
			&i.CashPosition100k,
			&i.PositionSource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItmCashpos = `-- name: ListItmCashpos :many
SELECT
    c.id,
    c.file_id,
    c.cashpos_date,
    c.terminal_id,
    c.machine_type,
    c.teller_id,
    c.branch_code,
    c.starting_cash_10k,
    c.cash_in_10k,
    c.cash_out_10k,
    c.cash_position_10k,
    c.starting_cash_20k,
    c.cash_in_20k,
    c.cash_out_20k,
    c.cash_position_20k,
    c.starting_cash_50k,
    c.cash_in_50k,
    c.cash_out_50k,
    c.cash_position_50k,
    c.starting_cash_100k,
    c.cash_in_100k,
    c.cash_out_100k,
    c.cash_position_100k,
    c.position_source,
    c.created_at
FROM itm_cashpos c
WHERE
    ($1::text = ''
        OR c.terminal_id ILIKE '%' || $1::text || '%'
        OR c.branch_code ILIKE '%' || $1::text || '%'
        OR c.teller_id ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR c.cashpos_date >= $2::date)
    AND ($3::text = '' OR c.cashpos_date <= $3::date)
ORDER BY
    CASE WHEN $4::text = 'cashpos_date' AND $5::text = 'asc' THEN c.cashpos_date END ASC,
    CASE WHEN $4::text = 'cashpos_date' AND $5::text = 'desc' THEN c.cashpos_date END DESC,
    CASE WHEN $4::text = 'terminal_id' AND $5::text = 'asc' THEN c.terminal_id END ASC,
    CASE WHEN $4::text = 'terminal_id' AND $5::text = 'desc' THEN c.terminal_id END DESC,
    CASE WHEN $4::text = 'machine_type' AND $5::text = 'asc' THEN c.machine_type END ASC,
    CASE WHEN $4::text = 'machine_type' AND $5::text = 'desc' THEN c.machine_type END DESC,
    CASE WHEN $4::text = 'branch_code' AND $5::text = 'asc' THEN c.branch_code END ASC,
    CASE WHEN $4::text = 'branch_code' AND $5::text = 'desc' THEN c.branch_code END DESC,
    CASE WHEN $4::text = 'created_at' AND $5::text = 'asc' THEN c.created_at END ASC,
    CASE WHEN $4::text = 'created_at' AND $5::text = 'desc' THEN c.created_at END DESC,
    CASE WHEN $4::text = 'id' AND $5::text = 'asc' THEN c.id END ASC,
    CASE WHEN $4::text = 'id' AND $5::text = 'desc' THEN c.id END DESC,
    c.cashpos_date DESC,
    c.id DESC
LIMIT $7::int OFFSET ($6::int - 1) * $7::int
`

type ListItmCashposParams struct {
	Search    string `json:"search"`
	DateFrom  string `json:"date_from"`
	DateTo    string `json:"date_to"`
	SortBy    string `json:"sort_by"`
	SortOrder string `json:"sort_order"`
	Page      int32  `json:"page"`
	PageSize  int32  `json:"page_size"`
}

// Paginated raw itm_cashpos rows for ATM Portal Cashpos view. Explicit
// column list (never SELECT *) so schema drift is visible. Empty-string
// filters mean "no filter". Sort keys are allowlisted in the service.
func (q *Queries) ListItmCashpos(ctx context.Context, arg ListItmCashposParams) ([]ItmCashpo, error) {
	rows, err := q.db.Query(ctx, listItmCashpos,
		arg.Search,
		arg.DateFrom,
		arg.DateTo,
		arg.SortBy,
		arg.SortOrder,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItmCashpo{}
	for rows.Next() {
		var i ItmCashpo
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.CashposDate,
			&i.TerminalID,
			&i.MachineType,
			&i.TellerID,
			&i.BranchCode,
			&i.StartingCash10k,
			&i.CashIn10k,
			&i.CashOut10k,
			&i.CashPosition10k,
			&i.StartingCash20k,
			&i.CashIn20k,
			&i.CashOut20k,
			&i.CashPosition20k,
			&i.StartingCash50k,
			&i.CashIn50k,
			&i.CashOut50k,
			&i.CashPosition50k,
			&i.StartingCash100k,
			&i.CashIn100k,
			&i.CashOut100k,
			&i.CashPosition100k,
			&i.PositionSource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplenishByTerminal = `-- name: ListReplenishByTerminal :many
SELECT
    replenish_date, replenish_time, terminal_id, machine_type,
    teller_id, branch_code, escrow,
    refund_denom_10k, refund_denom_20k, refund_denom_50k, refund_denom_100k, refund_total,
    replenish_denom_10k, replenish_denom_20k, replenish_denom_50k, replenish_denom_100k, replenish_total
FROM itm_replenish
WHERE terminal_id = $1::text
  AND ($2::text = '' OR replenish_date >= $2::date)
  AND ($3::text = '' OR replenish_date <= $3::date)
ORDER BY replenish_date DESC, replenish_time DESC
LIMIT $5::int
OFFSET ($4::int - 1) * $5::int
`

type ListReplenishByTerminalParams struct {
	TerminalID string `json:"terminal_id"`
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
	Page       int32  `json:"page"`
	PageSize   int32  `json:"page_size"`
}

type ListReplenishByTerminalRow struct {
	ReplenishDate      pgtype.Date    `json:"replenish_date"`
	ReplenishTime      pgtype.Time    `json:"replenish_time"`
	TerminalID         string         `json:"terminal_id"`
	MachineType        string         `json:"machine_type"`
	TellerID           string         `json:"teller_id"`
	BranchCode         string         `json:"branch_code"`
	Escrow             pgtype.Numeric `json:"escrow"`
	RefundDenom10k     pgtype.Numeric `json:"refund_denom_10k"`
	RefundDenom20k     pgtype.Numeric `json:"refund_denom_20k"`
	RefundDenom50k     pgtype.Numeric `json:"refund_denom_50k"`
	RefundDenom100k    pgtype.Numeric `json:"refund_denom_100k"`
	RefundTotal        pgtype.Numeric `json:"refund_total"`
	ReplenishDenom10k  pgtype.Numeric `json:"replenish_denom_10k"`
	ReplenishDenom20k  pgtype.Numeric `json:"replenish_denom_20k"`
	ReplenishDenom50k  pgtype.Numeric `json:"replenish_denom_50k"`
	ReplenishDenom100k pgtype.Numeric `json:"replenish_denom_100k"`
	ReplenishTotal     pgtype.Numeric `json:"replenish_total"`
}

// Paginated replenishment history for a single ATM (atm-profile spec),
// optional inclusive date_from/date_to filtering, newest first.
func (q *Queries) ListReplenishByTerminal(ctx context.Context, arg ListReplenishByTerminalParams) ([]ListReplenishByTerminalRow, error) {
	rows, err := q.db.Query(ctx, listReplenishByTerminal,
		arg.TerminalID,
		arg.DateFrom,
		arg.DateTo,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplenishByTerminalRow{}
	for rows.Next() {
		var i ListReplenishByTerminalRow
		if err := rows.Scan(
			&i.ReplenishDate,
			&i.ReplenishTime,
			&i.TerminalID,
			&i.MachineType,
			&i.TellerID,
			&i.BranchCode,
			&i.Escrow,
			&i.RefundDenom10k,
			&i.RefundDenom20k,
			&i.RefundDenom50k,
			&i.RefundDenom100k,
			&i.RefundTotal,
			&i.ReplenishDenom10k,
			&i.ReplenishDenom20k,
			&i.ReplenishDenom50k,
			&i.ReplenishDenom100k,
			&i.ReplenishTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
