// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atm_visit_quota.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustAtmVisitQuota = `-- name: AdjustAtmVisitQuota :one
UPDATE atm_visit_quotas
SET remaining = remaining + $1::int
WHERE atm_id = $2::bigint
RETURNING atm_id, package_code, quota_total, remaining, reset_at, reset_by, updated_at
`

type AdjustAtmVisitQuotaParams struct {
	Delta int32 `json:"delta"`
	AtmID int64 `json:"atm_id"`
}

// delta = -1 for a visit, +1 for a cancelled visit.
func (q *Queries) AdjustAtmVisitQuota(ctx context.Context, arg AdjustAtmVisitQuotaParams) (AtmVisitQuota, error) {
	row := q.db.QueryRow(ctx, adjustAtmVisitQuota, arg.Delta, arg.AtmID)
	var i AtmVisitQuota
	err := row.Scan(
		&i.AtmID,
		&i.PackageCode,
		&i.QuotaTotal,
		&i.Remaining,
		&i.ResetAt,
		&i.ResetBy,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelAtmVisit = `-- name: CancelAtmVisit :one
UPDATE atm_visits
SET cancelled_at = now(),
    cancelled_by = $1::bigint,
    cancel_reason = $2::text
WHERE id = $3::bigint AND cancelled_at IS NULL
RETURNING id, atm_id, vendor_request_id, quota_known, is_over_quota, created_at, cancelled_at, cancelled_by, cancel_reason
`

type CancelAtmVisitParams struct {
	CancelledBy  int64  `json:"cancelled_by"`
	CancelReason string `json:"cancel_reason"`
	ID           int64  `json:"id"`
}

func (q *Queries) CancelAtmVisit(ctx context.Context, arg CancelAtmVisitParams) (AtmVisit, error) {
	row := q.db.QueryRow(ctx, cancelAtmVisit, arg.CancelledBy, arg.CancelReason, arg.ID)
	var i AtmVisit
	err := row.Scan(
		&i.ID,
		&i.AtmID,
		&i.VendorRequestID,
		&i.QuotaKnown,
		&i.IsOverQuota,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
	)
	return i, err
}

const ensureAtmVisitQuota = `-- name: EnsureAtmVisitQuota :exec
INSERT INTO atm_visit_quotas (atm_id, package_code, quota_total, remaining, reset_at)
VALUES ($1::bigint, $2::text, $3::int,
        $3::int, clock_timestamp())
ON CONFLICT (atm_id) DO NOTHING
`

type EnsureAtmVisitQuotaParams struct {
	AtmID       int64  `json:"atm_id"`
	PackageCode string `json:"package_code"`
	QuotaTotal  int32  `json:"quota_total"`
}

// First visit of an ATM with a known kuota creates its row full
// (remaining = quota_total, reset_by NULL = otomatis); the caller then locks
// and decrements it like any other row. DO NOTHING keeps an existing row
// (and its snapshot) untouched, and two concurrent first visits can't fail
// on the primary key.
func (q *Queries) EnsureAtmVisitQuota(ctx context.Context, arg EnsureAtmVisitQuotaParams) error {
	_, err := q.db.Exec(ctx, ensureAtmVisitQuota, arg.AtmID, arg.PackageCode, arg.QuotaTotal)
	return err
}

const getAtmVisitForUpdate = `-- name: GetAtmVisitForUpdate :one
SELECT id, atm_id, vendor_request_id, quota_known, is_over_quota, created_at, cancelled_at, cancelled_by, cancel_reason FROM atm_visits WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAtmVisitForUpdate(ctx context.Context, id int64) (AtmVisit, error) {
	row := q.db.QueryRow(ctx, getAtmVisitForUpdate, id)
	var i AtmVisit
	err := row.Scan(
		&i.ID,
		&i.AtmID,
		&i.VendorRequestID,
		&i.QuotaKnown,
		&i.IsOverQuota,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
	)
	return i, err
}

const getAtmVisitQuotaByAtm = `-- name: GetAtmVisitQuotaByAtm :one
SELECT q.atm_id, q.package_code, q.quota_total, q.remaining, q.reset_at, q.reset_by, q.updated_at, u.full_name AS reset_by_name
FROM atm_visit_quotas q
LEFT JOIN users u ON u.id = q.reset_by
WHERE q.atm_id = $1
`

type GetAtmVisitQuotaByAtmRow struct {
	AtmID       int64              `json:"atm_id"`
	PackageCode string             `json:"package_code"`
	QuotaTotal  int32              `json:"quota_total"`
	Remaining   int32              `json:"remaining"`
	ResetAt     pgtype.Timestamptz `json:"reset_at"`
	ResetBy     *int64             `json:"reset_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ResetByName *string            `json:"reset_by_name"`
}

func (q *Queries) GetAtmVisitQuotaByAtm(ctx context.Context, atmID int64) (GetAtmVisitQuotaByAtmRow, error) {
	row := q.db.QueryRow(ctx, getAtmVisitQuotaByAtm, atmID)
	var i GetAtmVisitQuotaByAtmRow
	err := row.Scan(
		&i.AtmID,
		&i.PackageCode,
		&i.QuotaTotal,
		&i.Remaining,
		&i.ResetAt,
		&i.ResetBy,
		&i.UpdatedAt,
		&i.ResetByName,
	)
	return i, err
}

const getAtmVisitQuotaForUpdate = `-- name: GetAtmVisitQuotaForUpdate :one
SELECT atm_id, package_code, quota_total, remaining, reset_at, reset_by, updated_at FROM atm_visit_quotas WHERE atm_id = $1 FOR UPDATE
`

// Row lock: serializes concurrent visits/resets/cancels on one ATM so the
// remaining counter never loses an update.
func (q *Queries) GetAtmVisitQuotaForUpdate(ctx context.Context, atmID int64) (AtmVisitQuota, error) {
	row := q.db.QueryRow(ctx, getAtmVisitQuotaForUpdate, atmID)
	var i AtmVisitQuota
	err := row.Scan(
		&i.AtmID,
		&i.PackageCode,
		&i.QuotaTotal,
		&i.Remaining,
		&i.ResetAt,
		&i.ResetBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAtmVisit = `-- name: InsertAtmVisit :one
INSERT INTO atm_visits (atm_id, vendor_request_id, quota_known, created_at)
VALUES ($1::bigint, $2::bigint, $3::boolean, clock_timestamp())
ON CONFLICT (vendor_request_id, atm_id) DO NOTHING
RETURNING id, atm_id, vendor_request_id, quota_known, is_over_quota, created_at, cancelled_at, cancelled_by, cancel_reason
`

type InsertAtmVisitParams struct {
	AtmID           int64 `json:"atm_id"`
	VendorRequestID int64 `json:"vendor_request_id"`
	QuotaKnown      bool  `json:"quota_known"`
}

// ON CONFLICT DO NOTHING: a second approve of the same request for the same
// ATM returns no row (pgx.ErrNoRows) and must not touch the quota (FR3.1).
func (q *Queries) InsertAtmVisit(ctx context.Context, arg InsertAtmVisitParams) (AtmVisit, error) {
	row := q.db.QueryRow(ctx, insertAtmVisit, arg.AtmID, arg.VendorRequestID, arg.QuotaKnown)
	var i AtmVisit
	err := row.Scan(
		&i.ID,
		&i.AtmID,
		&i.VendorRequestID,
		&i.QuotaKnown,
		&i.IsOverQuota,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
	)
	return i, err
}

const listAtmVisitsSince = `-- name: ListAtmVisitsSince :many
SELECT av.id, av.vendor_request_id, vr.request_number, av.quota_known, av.is_over_quota,
       av.created_at, av.cancelled_at, av.cancel_reason, cu.full_name AS cancelled_by_name
FROM atm_visits av
JOIN vendor_requests vr ON vr.id = av.vendor_request_id
LEFT JOIN users cu ON cu.id = av.cancelled_by
WHERE av.atm_id = $1::bigint
  AND av.created_at >= $2::timestamptz
ORDER BY av.created_at DESC, av.id DESC
`

type ListAtmVisitsSinceParams struct {
	AtmID int64              `json:"atm_id"`
	Since pgtype.Timestamptz `json:"since"`
}

type ListAtmVisitsSinceRow struct {
	ID              int64              `json:"id"`
	VendorRequestID int64              `json:"vendor_request_id"`
	RequestNumber   string             `json:"request_number"`
	QuotaKnown      bool               `json:"quota_known"`
	IsOverQuota     bool               `json:"is_over_quota"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CancelReason    *string            `json:"cancel_reason"`
	CancelledByName *string            `json:"cancelled_by_name"`
}

// Visits of the current period (since the last reset), newest first,
// cancelled ones included so the screen can show them struck through.
func (q *Queries) ListAtmVisitsSince(ctx context.Context, arg ListAtmVisitsSinceParams) ([]ListAtmVisitsSinceRow, error) {
	rows, err := q.db.Query(ctx, listAtmVisitsSince, arg.AtmID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAtmVisitsSinceRow{}
	for rows.Next() {
		var i ListAtmVisitsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorRequestID,
			&i.RequestNumber,
			&i.QuotaKnown,
			&i.IsOverQuota,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.CancelReason,
			&i.CancelledByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtmsForVendorQuotaReset = `-- name: ListAtmsForVendorQuotaReset :many
SELECT a.id AS atm_id,
       a.terminal_id,
       pkg.package_code AS package_code,
       active_pkg.package AS vendor_package_label, -- vendor-wide label (migration 023); NULL for a branch package
       pf.cr_frequency  AS cr_frequency
FROM atms a
JOIN LATERAL (
    SELECT avp.vendor_package_id, avp.package AS package, avp.vendor_branch_id AS vendor_branch_id
    FROM atm_vendor_packages avp
    WHERE avp.atm_id = a.id
      AND avp.is_active = true
      AND avp.effective_start_date <= $1::date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= $1::date)
    ORDER BY avp.effective_start_date DESC, avp.id DESC
    LIMIT 1
) active_pkg ON true
LEFT JOIN vendor_packages_branch pkg ON pkg.id = active_pkg.vendor_package_id
JOIN vendor_branches vb ON vb.id = COALESCE(pkg.vendor_branch_id, active_pkg.vendor_branch_id)
LEFT JOIN package_frequencies pf
       ON pf.package_code = COALESCE(pkg.package_code, active_pkg.package) AND pf.machine_group = a.price_machine_group
WHERE vb.vendor_id = $2::bigint
ORDER BY a.terminal_id
`

type ListAtmsForVendorQuotaResetParams struct {
	AsOfDate pgtype.Date `json:"as_of_date"`
	VendorID int64       `json:"vendor_id"`
}

type ListAtmsForVendorQuotaResetRow struct {
	AtmID              int64   `json:"atm_id"`
	TerminalID         string  `json:"terminal_id"`
	PackageCode        *string `json:"package_code"`
	VendorPackageLabel *string `json:"vendor_package_label"`
	CrFrequency        *int32  `json:"cr_frequency"`
}

// Every ATM whose active package belongs to the vendor, with its kuota
// (cr_frequency NULL = tidak diketahui -> skipped by the caller).
func (q *Queries) ListAtmsForVendorQuotaReset(ctx context.Context, arg ListAtmsForVendorQuotaResetParams) ([]ListAtmsForVendorQuotaResetRow, error) {
	rows, err := q.db.Query(ctx, listAtmsForVendorQuotaReset, arg.AsOfDate, arg.VendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAtmsForVendorQuotaResetRow{}
	for rows.Next() {
		var i ListAtmsForVendorQuotaResetRow
		if err := rows.Scan(
			&i.AtmID,
			&i.TerminalID,
			&i.PackageCode,
			&i.VendorPackageLabel,
			&i.CrFrequency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAtmVisitOverQuota = `-- name: MarkAtmVisitOverQuota :exec
UPDATE atm_visits SET is_over_quota = true WHERE id = $1
`

func (q *Queries) MarkAtmVisitOverQuota(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAtmVisitOverQuota, id)
	return err
}

const resetAtmVisitQuota = `-- name: ResetAtmVisitQuota :one
INSERT INTO atm_visit_quotas (atm_id, package_code, quota_total, remaining, reset_at, reset_by)
VALUES ($1::bigint, $2::text, $3::int,
        $3::int, clock_timestamp(), $4::bigint)
ON CONFLICT (atm_id) DO UPDATE
SET package_code = EXCLUDED.package_code,
    quota_total  = EXCLUDED.quota_total,
    remaining    = EXCLUDED.quota_total,
    reset_at     = clock_timestamp(),
    reset_by     = EXCLUDED.reset_by
RETURNING atm_id, package_code, quota_total, remaining, reset_at, reset_by, updated_at
`

type ResetAtmVisitQuotaParams struct {
	AtmID       int64  `json:"atm_id"`
	PackageCode string `json:"package_code"`
	QuotaTotal  int32  `json:"quota_total"`
	ResetBy     int64  `json:"reset_by"`
}

// reset_at / atm_visits.created_at use clock_timestamp(), not now(): they
// define the period boundary (visit belongs to the period iff created_at >=
// reset_at), so they must order correctly even within one transaction.
func (q *Queries) ResetAtmVisitQuota(ctx context.Context, arg ResetAtmVisitQuotaParams) (AtmVisitQuota, error) {
	row := q.db.QueryRow(ctx, resetAtmVisitQuota,
		arg.AtmID,
		arg.PackageCode,
		arg.QuotaTotal,
		arg.ResetBy,
	)
	var i AtmVisitQuota
	err := row.Scan(
		&i.AtmID,
		&i.PackageCode,
		&i.QuotaTotal,
		&i.Remaining,
		&i.ResetAt,
		&i.ResetBy,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveAtmQuota = `-- name: ResolveAtmQuota :one

SELECT a.id AS atm_id,
       a.terminal_id,
       pkg.package_code AS package_code,
       active_pkg.package AS vendor_package_label, -- vendor-wide label (migration 023); NULL for a branch package
       pf.cr_frequency  AS cr_frequency
FROM atms a
LEFT JOIN LATERAL (
    SELECT avp.vendor_package_id, avp.package AS package, avp.vendor_branch_id AS vendor_branch_id
    FROM atm_vendor_packages avp
    WHERE avp.atm_id = a.id
      AND avp.is_active = true
      AND avp.effective_start_date <= $1::date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= $1::date)
    ORDER BY avp.effective_start_date DESC, avp.id DESC
    LIMIT 1
) active_pkg ON true
LEFT JOIN vendor_packages_branch pkg ON pkg.id = active_pkg.vendor_package_id
LEFT JOIN package_frequencies pf
       ON pf.package_code = COALESCE(pkg.package_code, active_pkg.package) AND pf.machine_group = a.price_machine_group
WHERE a.terminal_id = $2::text
`

type ResolveAtmQuotaParams struct {
	AsOfDate   pgtype.Date `json:"as_of_date"`
	TerminalID string      `json:"terminal_id"`
}

type ResolveAtmQuotaRow struct {
	AtmID              int64   `json:"atm_id"`
	TerminalID         string  `json:"terminal_id"`
	PackageCode        *string `json:"package_code"`
	VendorPackageLabel *string `json:"vendor_package_label"`
	CrFrequency        *int32  `json:"cr_frequency"`
}

// atm-visit-quota (.claude/sdlc/atm-visit-quota/spec.md): kuota kunjungan
// replenish per ATM. Kuota = package_frequencies.cr_frequency (read-only) of
// the ATM's active package; sisa lives in atm_visit_quotas, each counted
// visit in atm_visits.
// One terminal's atm id + active package (same LATERAL + avp.id DESC
// tie-breaker as ListForecastForDate) + its cr_frequency. package_code /
// cr_frequency are NULL when there is no active package, the ATM has no
// price_machine_group, or the label has no package_frequencies row: the
// caller treats that as "kuota tidak diketahui", never a guess.
func (q *Queries) ResolveAtmQuota(ctx context.Context, arg ResolveAtmQuotaParams) (ResolveAtmQuotaRow, error) {
	row := q.db.QueryRow(ctx, resolveAtmQuota, arg.AsOfDate, arg.TerminalID)
	var i ResolveAtmQuotaRow
	err := row.Scan(
		&i.AtmID,
		&i.TerminalID,
		&i.PackageCode,
		&i.VendorPackageLabel,
		&i.CrFrequency,
	)
	return i, err
}
