// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atm_assignments_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aTMActiveForAssignment = `-- name: ATMActiveForAssignment :one
SELECT id FROM atms WHERE id = $1 AND deleted_at IS NULL
`

// Submit-time check that the ATM exists and is not soft-deleted.
func (q *Queries) ATMActiveForAssignment(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, aTMActiveForAssignment, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const countATMAssignmentsAdmin = `-- name: CountATMAssignmentsAdmin :one
SELECT COUNT(*)
FROM atm_vendor_packages a
WHERE a.atm_id = $1
  AND (
        $2::text = 'all'
        OR ($2::text = 'active' AND a.is_active)
        OR ($2::text = 'disabled' AND NOT a.is_active)
      )
`

type CountATMAssignmentsAdminParams struct {
	AtmID  int64  `json:"atm_id"`
	Status string `json:"status"`
}

func (q *Queries) CountATMAssignmentsAdmin(ctx context.Context, arg CountATMAssignmentsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countATMAssignmentsAdmin, arg.AtmID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createATMAssignmentAdmin = `-- name: CreateATMAssignmentAdmin :one
INSERT INTO atm_vendor_packages (atm_id, vendor_package_id, effective_start_date, effective_end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, atm_id, vendor_package_id, effective_start_date, effective_end_date, is_active
`

type CreateATMAssignmentAdminParams struct {
	AtmID              int64       `json:"atm_id"`
	VendorPackageID    int64       `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date `json:"effective_end_date"`
}

type CreateATMAssignmentAdminRow struct {
	ID                 int64       `json:"id"`
	AtmID              int64       `json:"atm_id"`
	VendorPackageID    int64       `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date `json:"effective_end_date"`
	IsActive           bool        `json:"is_active"`
}

func (q *Queries) CreateATMAssignmentAdmin(ctx context.Context, arg CreateATMAssignmentAdminParams) (CreateATMAssignmentAdminRow, error) {
	row := q.db.QueryRow(ctx, createATMAssignmentAdmin,
		arg.AtmID,
		arg.VendorPackageID,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
	)
	var i CreateATMAssignmentAdminRow
	err := row.Scan(
		&i.ID,
		&i.AtmID,
		&i.VendorPackageID,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.IsActive,
	)
	return i, err
}

const disableATMAssignment = `-- name: DisableATMAssignment :exec
UPDATE atm_vendor_packages SET is_active = false WHERE id = $1
`

// Soft-disable only; releases the period from the exclusion constraint.
func (q *Queries) DisableATMAssignment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableATMAssignment, id)
	return err
}

const enableATMAssignment = `-- name: EnableATMAssignment :exec
UPDATE atm_vendor_packages SET is_active = true WHERE id = $1
`

// May raise the exclusion violation if the period was re-assigned meanwhile.
func (q *Queries) EnableATMAssignment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableATMAssignment, id)
	return err
}

const findOverlappingATMAssignment = `-- name: FindOverlappingATMAssignment :one
SELECT id FROM atm_vendor_packages
WHERE atm_id = $1
  AND is_active
  AND id <> $2
  AND daterange(effective_start_date, effective_end_date, '[]')
      && daterange($3::date, $4::date, '[]')
LIMIT 1
`

type FindOverlappingATMAssignmentParams struct {
	AtmID     int64       `json:"atm_id"`
	ExcludeID int64       `json:"exclude_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// Same predicate as the exclusion constraint: active rows of the same ATM whose
// inclusive daterange overlaps [start, end] (NULL end = unbounded). exclude_id
// lets an update ignore its own row (pass 0 for create).
func (q *Queries) FindOverlappingATMAssignment(ctx context.Context, arg FindOverlappingATMAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, findOverlappingATMAssignment,
		arg.AtmID,
		arg.ExcludeID,
		arg.StartDate,
		arg.EndDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getATMAssignmentAdminByID = `-- name: GetATMAssignmentAdminByID :one
SELECT a.id, a.atm_id, a.vendor_package_id, p.code AS package_code,
       a.effective_start_date, a.effective_end_date, a.is_active
FROM atm_vendor_packages a
JOIN vendor_packages_branch p ON p.id = a.vendor_package_id
WHERE a.id = $1
`

type GetATMAssignmentAdminByIDRow struct {
	ID                 int64       `json:"id"`
	AtmID              int64       `json:"atm_id"`
	VendorPackageID    int64       `json:"vendor_package_id"`
	PackageCode        string      `json:"package_code"`
	EffectiveStartDate pgtype.Date `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date `json:"effective_end_date"`
	IsActive           bool        `json:"is_active"`
}

// Doubles as the "before" snapshot / CurrentState (T2.5).
func (q *Queries) GetATMAssignmentAdminByID(ctx context.Context, id int64) (GetATMAssignmentAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getATMAssignmentAdminByID, id)
	var i GetATMAssignmentAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.AtmID,
		&i.VendorPackageID,
		&i.PackageCode,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.IsActive,
	)
	return i, err
}

const listATMAssignmentsAdmin = `-- name: ListATMAssignmentsAdmin :many

SELECT a.id, a.atm_id, a.vendor_package_id, p.code AS package_code,
       a.effective_start_date, a.effective_end_date, a.is_active
FROM atm_vendor_packages a
JOIN vendor_packages_branch p ON p.id = a.vendor_package_id
WHERE a.atm_id = $1
  AND (
        $2::text = 'all'
        OR ($2::text = 'active' AND a.is_active)
        OR ($2::text = 'disabled' AND NOT a.is_active)
      )
ORDER BY a.effective_start_date DESC, a.id DESC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListATMAssignmentsAdminParams struct {
	AtmID      int64  `json:"atm_id"`
	Status     string `json:"status"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

type ListATMAssignmentsAdminRow struct {
	ID                 int64       `json:"id"`
	AtmID              int64       `json:"atm_id"`
	VendorPackageID    int64       `json:"vendor_package_id"`
	PackageCode        string      `json:"package_code"`
	EffectiveStartDate pgtype.Date `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date `json:"effective_end_date"`
	IsActive           bool        `json:"is_active"`
}

// Admin ATM assignment (kelolaan ATM) management (plan.md Fase 3, T3.5): an
// assignment is an atm_vendor_packages row -- one ATM under one vendor
// package for an effective period. Mutations route through the master-data
// maker-checker engine (Fase 2, D1): create/update/disable/enable below are
// only run by ATMAssignmentApplier inside the apply-on-approve transaction.
// The exclusion constraint atm_vendor_packages_no_overlap (T1.6) is the
// authoritative overlap guard; FindOverlappingATMAssignment is only the
// early, friendly submit-time check.
// status: 'active'|'disabled'|'all' on is_active (the table has no deleted_at;
// is_active=false is what releases the period from the exclusion constraint).
// No priority_class here since migration 010 dropped vendor_packages_branch.priority_class.
func (q *Queries) ListATMAssignmentsAdmin(ctx context.Context, arg ListATMAssignmentsAdminParams) ([]ListATMAssignmentsAdminRow, error) {
	rows, err := q.db.Query(ctx, listATMAssignmentsAdmin,
		arg.AtmID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListATMAssignmentsAdminRow{}
	for rows.Next() {
		var i ListATMAssignmentsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AtmID,
			&i.VendorPackageID,
			&i.PackageCode,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateATMAssignmentAdmin = `-- name: UpdateATMAssignmentAdmin :one
UPDATE atm_vendor_packages
SET vendor_package_id = $1,
    effective_start_date = $2,
    effective_end_date = $3,
    updated_at = now()
WHERE id = $4 AND is_active
RETURNING id, atm_id, vendor_package_id, effective_start_date, effective_end_date, is_active
`

type UpdateATMAssignmentAdminParams struct {
	VendorPackageID    int64       `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date `json:"effective_end_date"`
	ID                 int64       `json:"id"`
}

type UpdateATMAssignmentAdminRow struct {
	ID                 int64       `json:"id"`
	AtmID              int64       `json:"atm_id"`
	VendorPackageID    int64       `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date `json:"effective_end_date"`
	IsActive           bool        `json:"is_active"`
}

// atm_id is immutable. Only an active row can be edited (a disabled one is
// re-enabled first, which re-runs the overlap guard).
func (q *Queries) UpdateATMAssignmentAdmin(ctx context.Context, arg UpdateATMAssignmentAdminParams) (UpdateATMAssignmentAdminRow, error) {
	row := q.db.QueryRow(ctx, updateATMAssignmentAdmin,
		arg.VendorPackageID,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
		arg.ID,
	)
	var i UpdateATMAssignmentAdminRow
	err := row.Scan(
		&i.ID,
		&i.AtmID,
		&i.VendorPackageID,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.IsActive,
	)
	return i, err
}
