// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atm_portal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countATMsWithCashPos = `-- name: CountATMsWithCashPos :one
WITH sub AS (
    SELECT
        a.terminal_id,
        l.name AS location_name,
        a.machine_type,
        a.brand,
        a.deployment_type,
        r.region,
        lcp.replenish_date AS last_replenish_date,
        CASE
            WHEN a.low_threshold_amount IS NULL THEN 'unconfigured'
            WHEN lcp.refund_total IS NULL THEN 'no_data'
            WHEN a.critical_threshold_amount IS NOT NULL
                 AND lcp.refund_total <= a.critical_threshold_amount THEN 'critical'
            WHEN lcp.refund_total <= a.low_threshold_amount THEN 'low'
            ELSE 'normal'
        END AS status
    FROM atms a
    JOIN locations l ON l.id = a.location_id
    JOIN regions r ON r.id = l.region_id
    LEFT JOIN LATERAL (
        SELECT cp.replenish_date, cp.replenish_time, cp.refund_total
        FROM itm_cashpos cp
        WHERE cp.terminal_id = a.terminal_id
        ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
        LIMIT 1
    ) lcp ON true
    WHERE a.is_active = true
      AND a.deleted_at IS NULL
)
SELECT COUNT(*)
FROM sub
WHERE
    ($1::text = ''
        OR sub.terminal_id ILIKE '%' || $1::text || '%'
        OR sub.location_name ILIKE '%' || $1::text || '%')
    AND ($2::text = 'all'
        OR sub.status = ANY(string_to_array($2::text, ',')))
    AND ($3::text = ''
        OR sub.machine_type = ANY(string_to_array($3::text, ',')))
    AND ($4::text = ''
        OR sub.brand = ANY(string_to_array($4::text, ',')))
    AND ($5::text = '' OR sub.deployment_type = $5::text)
    AND ($6::text = '' OR sub.region ILIKE '%' || $6::text || '%')
    AND ($7::text = '' OR sub.last_replenish_date >= $7::date)
    AND ($8::text = '' OR sub.last_replenish_date <= $8::date)
`

type CountATMsWithCashPosParams struct {
	Search         string `json:"search"`
	Status         string `json:"status"`
	MachineType    string `json:"machine_type"`
	Brand          string `json:"brand"`
	DeploymentType string `json:"deployment_type"`
	Region         string `json:"region"`
	DateFrom       string `json:"date_from"`
	DateTo         string `json:"date_to"`
}

// Mirrors ListATMsWithCashPos's FROM/JOIN/WHERE (including all dynamic
// filters) exactly, minus ORDER BY/LIMIT/OFFSET, so the count matches the
// filtered result set for pagination math (Property 6).
func (q *Queries) CountATMsWithCashPos(ctx context.Context, arg CountATMsWithCashPosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countATMsWithCashPos,
		arg.Search,
		arg.Status,
		arg.MachineType,
		arg.Brand,
		arg.DeploymentType,
		arg.Region,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getATMSummary = `-- name: GetATMSummary :one
SELECT
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE sub.status = 'critical') AS critical,
    COUNT(*) FILTER (WHERE sub.status = 'low') AS low,
    COUNT(*) FILTER (WHERE sub.status = 'normal') AS normal,
    COUNT(*) FILTER (WHERE sub.status = 'unconfigured') AS unconfigured,
    COUNT(*) FILTER (WHERE sub.status = 'no_data') AS no_data
FROM (
    SELECT
        CASE
            WHEN a.low_threshold_amount IS NULL THEN 'unconfigured'
            WHEN lcp.refund_total IS NULL THEN 'no_data'
            WHEN a.critical_threshold_amount IS NOT NULL
                 AND lcp.refund_total <= a.critical_threshold_amount THEN 'critical'
            WHEN lcp.refund_total <= a.low_threshold_amount THEN 'low'
            ELSE 'normal'
        END AS status
    FROM atms a
    LEFT JOIN LATERAL (
        SELECT cp.refund_total
        FROM itm_cashpos cp
        WHERE cp.terminal_id = a.terminal_id
        ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
        LIMIT 1
    ) lcp ON true
    WHERE a.is_active = true
      AND a.deleted_at IS NULL
) sub
`

type GetATMSummaryRow struct {
	Total        int64 `json:"total"`
	Critical     int64 `json:"critical"`
	Low          int64 `json:"low"`
	Normal       int64 `json:"normal"`
	Unconfigured int64 `json:"unconfigured"`
	NoData       int64 `json:"no_data"`
}

// Global status counts across all active ATMs, independent of any list
// filters (Property 10). Does not join locations/regions since it only
// aggregates status, and does not accept filter args.
func (q *Queries) GetATMSummary(ctx context.Context) (GetATMSummaryRow, error) {
	row := q.db.QueryRow(ctx, getATMSummary)
	var i GetATMSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Critical,
		&i.Low,
		&i.Normal,
		&i.Unconfigured,
		&i.NoData,
	)
	return i, err
}

const getLastUpdated = `-- name: GetLastUpdated :one
SELECT
    (replenish_date + replenish_time)::timestamp AS last_updated
FROM itm_cashpos
ORDER BY replenish_date DESC, replenish_time DESC
LIMIT 1
`

// Most recent replenish_date + replenish_time across all itm_cashpos
// records, used for the data-freshness indicator. Returns NULL when no
// cashpos records exist yet.
func (q *Queries) GetLastUpdated(ctx context.Context) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getLastUpdated)
	var last_updated pgtype.Timestamp
	err := row.Scan(&last_updated)
	return last_updated, err
}

const listATMsWithCashPos = `-- name: ListATMsWithCashPos :many
WITH sub AS (
    SELECT
        a.terminal_id,
        l.name AS location_name,
        l.address_line1 AS address,
        a.machine_type,
        a.brand,
        a.deployment_type,
        r.region,
        a.low_threshold_amount,
        a.critical_threshold_amount,
        lcp.replenish_date AS last_replenish_date,
        lcp.replenish_time AS last_replenish_time,
        lcp.refund_total,
        lcp.replenish_total,
        lcp.escrow,
        CASE
            WHEN a.low_threshold_amount IS NULL THEN 'unconfigured'
            WHEN lcp.refund_total IS NULL THEN 'no_data'
            WHEN a.critical_threshold_amount IS NOT NULL
                 AND lcp.refund_total <= a.critical_threshold_amount THEN 'critical'
            WHEN lcp.refund_total <= a.low_threshold_amount THEN 'low'
            ELSE 'normal'
        END AS status
    FROM atms a
    JOIN locations l ON l.id = a.location_id
    JOIN regions r ON r.id = l.region_id
    LEFT JOIN LATERAL (
        SELECT
            cp.replenish_date,
            cp.replenish_time,
            cp.refund_total,
            cp.replenish_total,
            cp.escrow
        FROM itm_cashpos cp
        WHERE cp.terminal_id = a.terminal_id
        ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
        LIMIT 1
    ) lcp ON true
    WHERE a.is_active = true
      AND a.deleted_at IS NULL
)
SELECT
    sub.terminal_id,
    sub.location_name,
    sub.address,
    sub.machine_type,
    sub.brand,
    sub.deployment_type,
    sub.low_threshold_amount,
    sub.critical_threshold_amount,
    sub.last_replenish_date,
    sub.last_replenish_time,
    sub.refund_total,
    sub.replenish_total,
    sub.escrow,
    sub.status
FROM sub
WHERE
    ($1::text = ''
        OR sub.terminal_id ILIKE '%' || $1::text || '%'
        OR sub.location_name ILIKE '%' || $1::text || '%')
    AND ($2::text = 'all'
        OR sub.status = ANY(string_to_array($2::text, ',')))
    AND ($3::text = ''
        OR sub.machine_type = ANY(string_to_array($3::text, ',')))
    AND ($4::text = ''
        OR sub.brand = ANY(string_to_array($4::text, ',')))
    AND ($5::text = '' OR sub.deployment_type = $5::text)
    AND ($6::text = '' OR sub.region ILIKE '%' || $6::text || '%')
    AND ($7::text = '' OR sub.last_replenish_date >= $7::date)
    AND ($8::text = '' OR sub.last_replenish_date <= $8::date)
ORDER BY
    CASE WHEN $9::text = 'terminal_id' AND $10::text = 'asc' THEN sub.terminal_id END ASC,
    CASE WHEN $9::text = 'terminal_id' AND $10::text = 'desc' THEN sub.terminal_id END DESC,
    CASE WHEN $9::text = 'location' AND $10::text = 'asc' THEN sub.location_name END ASC,
    CASE WHEN $9::text = 'location' AND $10::text = 'desc' THEN sub.location_name END DESC,
    CASE WHEN $9::text = 'last_replenish_date' AND $10::text = 'asc' THEN sub.last_replenish_date END ASC,
    CASE WHEN $9::text = 'last_replenish_date' AND $10::text = 'desc' THEN sub.last_replenish_date END DESC,
    CASE WHEN $9::text = 'refund_total' AND $10::text = 'asc' THEN sub.refund_total END ASC,
    CASE WHEN $9::text = 'refund_total' AND $10::text = 'desc' THEN sub.refund_total END DESC,
    CASE WHEN $9::text = 'replenish_total' AND $10::text = 'asc' THEN sub.replenish_total END ASC,
    CASE WHEN $9::text = 'replenish_total' AND $10::text = 'desc' THEN sub.replenish_total END DESC,
    CASE WHEN $9::text = 'status' AND $10::text = 'asc' THEN sub.status END ASC,
    CASE WHEN $9::text = 'status' AND $10::text = 'desc' THEN sub.status END DESC,
    sub.terminal_id ASC
LIMIT $12::int OFFSET ($11::int - 1) * $12::int
`

type ListATMsWithCashPosParams struct {
	Search         string `json:"search"`
	Status         string `json:"status"`
	MachineType    string `json:"machine_type"`
	Brand          string `json:"brand"`
	DeploymentType string `json:"deployment_type"`
	Region         string `json:"region"`
	DateFrom       string `json:"date_from"`
	DateTo         string `json:"date_to"`
	SortBy         string `json:"sort_by"`
	SortOrder      string `json:"sort_order"`
	Page           int32  `json:"page"`
	PageSize       int32  `json:"page_size"`
}

type ListATMsWithCashPosRow struct {
	TerminalID              string         `json:"terminal_id"`
	LocationName            string         `json:"location_name"`
	Address                 string         `json:"address"`
	MachineType             string         `json:"machine_type"`
	Brand                   string         `json:"brand"`
	DeploymentType          string         `json:"deployment_type"`
	LowThresholdAmount      pgtype.Numeric `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric `json:"critical_threshold_amount"`
	LastReplenishDate       pgtype.Date    `json:"last_replenish_date"`
	LastReplenishTime       pgtype.Time    `json:"last_replenish_time"`
	RefundTotal             pgtype.Numeric `json:"refund_total"`
	ReplenishTotal          pgtype.Numeric `json:"replenish_total"`
	Escrow                  pgtype.Numeric `json:"escrow"`
	Status                  string         `json:"status"`
}

// Paginated, filtered, sorted ATM list joined with the latest itm_cashpos
// record per terminal. location_name/address/region are NOT columns on
// atms — they require joining locations (via atms.location_id) and
// regions (via locations.region_id). Status is computed here via a CASE
// expression (Property 1 precedence: unconfigured > no_data > critical >
// low > normal) inside the `sub` subquery so it can be filtered on and
// sorted by in the outer query — a SELECT-list alias cannot be referenced
// directly in the WHERE clause that produced it.
//
// All filter args are plain (non-nullable) strings matching
// ListATMsParams in design.md: an empty string ("") or "all" (for status)
// means "no filter applied", so callers always pass concrete values,
// never NULL. status is comma-separated multi-select (requirements.md Req
// 89.3), same pattern as machine_type/brand — corrects an earlier
// single-value assumption carried over from design.md's API contract table.
func (q *Queries) ListATMsWithCashPos(ctx context.Context, arg ListATMsWithCashPosParams) ([]ListATMsWithCashPosRow, error) {
	rows, err := q.db.Query(ctx, listATMsWithCashPos,
		arg.Search,
		arg.Status,
		arg.MachineType,
		arg.Brand,
		arg.DeploymentType,
		arg.Region,
		arg.DateFrom,
		arg.DateTo,
		arg.SortBy,
		arg.SortOrder,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListATMsWithCashPosRow{}
	for rows.Next() {
		var i ListATMsWithCashPosRow
		if err := rows.Scan(
			&i.TerminalID,
			&i.LocationName,
			&i.Address,
			&i.MachineType,
			&i.Brand,
			&i.DeploymentType,
			&i.LowThresholdAmount,
			&i.CriticalThresholdAmount,
			&i.LastReplenishDate,
			&i.LastReplenishTime,
			&i.RefundTotal,
			&i.ReplenishTotal,
			&i.Escrow,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
