// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atms_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countATMsAdmin = `-- name: CountATMsAdmin :one
SELECT COUNT(*)
FROM atms a
WHERE ($1::text IS NULL
        OR a.terminal_id ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR a.brand = $2::text)
  AND ($3::text IS NULL OR a.machine_type = $3::text)
  AND ($4::text IS NULL OR a.deployment_type = $4::text)
  AND ($5::text IS NULL OR a.priority_class = $5::text)
  AND ($6::bigint IS NULL OR a.location_id = $6::bigint)
  AND (
        $7::text = 'all'
        OR ($7::text = 'active' AND a.deleted_at IS NULL)
        OR ($7::text = 'disabled' AND a.deleted_at IS NOT NULL)
      )
`

type CountATMsAdminParams struct {
	Q              *string `json:"q"`
	Brand          *string `json:"brand"`
	MachineType    *string `json:"machine_type"`
	DeploymentType *string `json:"deployment_type"`
	PriorityClass  *string `json:"priority_class"`
	LocationID     *int64  `json:"location_id"`
	Status         string  `json:"status"`
}

// Same filters as ListATMsAdmin, no LIMIT/OFFSET -- pagination total.
func (q *Queries) CountATMsAdmin(ctx context.Context, arg CountATMsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countATMsAdmin,
		arg.Q,
		arg.Brand,
		arg.MachineType,
		arg.DeploymentType,
		arg.PriorityClass,
		arg.LocationID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createATMAdmin = `-- name: CreateATMAdmin :one
INSERT INTO atms (terminal_id, location_id, machine_type, brand, model,
                   operation_hours, deployment_type, capacity_amount,
                   low_threshold_amount, critical_threshold_amount,
                   blacklisted, escrow_account, priority_class)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8,
        $9, $10,
        $11, $12, $13)
RETURNING id, terminal_id, location_id, machine_type, brand, model,
          operation_hours, deployment_type, capacity_amount,
          low_threshold_amount, critical_threshold_amount, blacklisted,
          escrow_account, priority_class, is_active, created_at, updated_at, deleted_at
`

type CreateATMAdminParams struct {
	TerminalID              string         `json:"terminal_id"`
	LocationID              int64          `json:"location_id"`
	MachineType             string         `json:"machine_type"`
	Brand                   string         `json:"brand"`
	Model                   string         `json:"model"`
	OperationHours          string         `json:"operation_hours"`
	DeploymentType          string         `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric `json:"critical_threshold_amount"`
	Blacklisted             bool           `json:"blacklisted"`
	EscrowAccount           *string        `json:"escrow_account"`
	PriorityClass           *string        `json:"priority_class"`
}

type CreateATMAdminRow struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	EscrowAccount           *string            `json:"escrow_account"`
	PriorityClass           *string            `json:"priority_class"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateATMAdmin(ctx context.Context, arg CreateATMAdminParams) (CreateATMAdminRow, error) {
	row := q.db.QueryRow(ctx, createATMAdmin,
		arg.TerminalID,
		arg.LocationID,
		arg.MachineType,
		arg.Brand,
		arg.Model,
		arg.OperationHours,
		arg.DeploymentType,
		arg.CapacityAmount,
		arg.LowThresholdAmount,
		arg.CriticalThresholdAmount,
		arg.Blacklisted,
		arg.EscrowAccount,
		arg.PriorityClass,
	)
	var i CreateATMAdminRow
	err := row.Scan(
		&i.ID,
		&i.TerminalID,
		&i.LocationID,
		&i.MachineType,
		&i.Brand,
		&i.Model,
		&i.OperationHours,
		&i.DeploymentType,
		&i.CapacityAmount,
		&i.LowThresholdAmount,
		&i.CriticalThresholdAmount,
		&i.Blacklisted,
		&i.EscrowAccount,
		&i.PriorityClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const disableATM = `-- name: DisableATM :exec
UPDATE atms SET is_active = false, deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

// Soft-disable only: is_active=false, deleted_at=now(). No hard DELETE on
// atms anywhere in this codebase (guard test extended in Task 5).
func (q *Queries) DisableATM(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableATM, id)
	return err
}

const enableATM = `-- name: EnableATM :exec
UPDATE atms SET is_active = true, deleted_at = NULL WHERE id = $1
`

// Reverses DisableATM: is_active=true, deleted_at=NULL.
func (q *Queries) EnableATM(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableATM, id)
	return err
}

const findATMByTerminalID = `-- name: FindATMByTerminalID :one
SELECT id FROM atms WHERE terminal_id = $1
`

// Uniqueness pre-check (incl. soft-deleted) for create/update (Req 3.4, 4.3).
func (q *Queries) FindATMByTerminalID(ctx context.Context, terminalID string) (int64, error) {
	row := q.db.QueryRow(ctx, findATMByTerminalID, terminalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getATMAdminByID = `-- name: GetATMAdminByID :one
SELECT a.id, a.terminal_id, a.location_id, l.name AS location_name,
       a.machine_type, a.brand, a.model, a.operation_hours, a.deployment_type,
       a.capacity_amount, a.low_threshold_amount, a.critical_threshold_amount,
       a.blacklisted, a.escrow_account, a.priority_class, a.is_active,
       a.created_at, a.updated_at, a.deleted_at
FROM atms a
LEFT JOIN locations l ON l.id = a.location_id
WHERE a.id = $1
`

type GetATMAdminByIDRow struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	LocationName            *string            `json:"location_name"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	EscrowAccount           *string            `json:"escrow_account"`
	PriorityClass           *string            `json:"priority_class"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

// Includes soft-deleted rows -- 404 pre-checks on update/disable/enable
// treat a soft-disabled ATM as not-found for edit, same convention as
// GetVendorAdminByID/GetUserAdminByID.
func (q *Queries) GetATMAdminByID(ctx context.Context, id int64) (GetATMAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getATMAdminByID, id)
	var i GetATMAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.TerminalID,
		&i.LocationID,
		&i.LocationName,
		&i.MachineType,
		&i.Brand,
		&i.Model,
		&i.OperationHours,
		&i.DeploymentType,
		&i.CapacityAmount,
		&i.LowThresholdAmount,
		&i.CriticalThresholdAmount,
		&i.Blacklisted,
		&i.EscrowAccount,
		&i.PriorityClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listATMsAdmin = `-- name: ListATMsAdmin :many

SELECT a.id, a.terminal_id, a.location_id, l.name AS location_name,
       a.machine_type, a.brand, a.model, a.operation_hours, a.deployment_type,
       a.capacity_amount, a.low_threshold_amount, a.critical_threshold_amount,
       a.blacklisted, a.escrow_account, a.priority_class, a.is_active,
       a.created_at, a.updated_at, a.deleted_at
FROM atms a
LEFT JOIN locations l ON l.id = a.location_id
WHERE ($1::text IS NULL
        OR a.terminal_id ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR a.brand = $2::text)
  AND ($3::text IS NULL OR a.machine_type = $3::text)
  AND ($4::text IS NULL OR a.deployment_type = $4::text)
  AND ($5::text IS NULL OR a.priority_class = $5::text)
  AND ($6::bigint IS NULL OR a.location_id = $6::bigint)
  AND (
        $7::text = 'all'
        OR ($7::text = 'active' AND a.deleted_at IS NULL)
        OR ($7::text = 'disabled' AND a.deleted_at IS NOT NULL)
      )
ORDER BY a.terminal_id ASC, a.id ASC
LIMIT $9::bigint OFFSET $8::bigint
`

type ListATMsAdminParams struct {
	Q              *string `json:"q"`
	Brand          *string `json:"brand"`
	MachineType    *string `json:"machine_type"`
	DeploymentType *string `json:"deployment_type"`
	PriorityClass  *string `json:"priority_class"`
	LocationID     *int64  `json:"location_id"`
	Status         string  `json:"status"`
	PageOffset     int64   `json:"page_offset"`
	PageLimit      int64   `json:"page_limit"`
}

type ListATMsAdminRow struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	LocationName            *string            `json:"location_name"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	EscrowAccount           *string            `json:"escrow_account"`
	PriorityClass           *string            `json:"priority_class"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

// Admin ATM Management (Task 2): sqlc queries for the admin ATM CRUD
// endpoints (.kiro/specs/admin-atm-management). No new tables -- all columns
// already exist on atms (002, 030). Kept separate from the atm-portal
// read-only queries (atm_portal.sql).
// Admin ATM list. Filters: q (ILIKE on terminal_id), brand, machine_type,
// deployment_type, priority_class, location_id (all sqlc.narg, NULL = no
// filter) and status -- the caller resolves absent status to 'active'
// before calling (same convention as ListVendorsAdmin), so this query only
// ever sees 'active' | 'disabled' | 'all'. LEFT JOIN locations for
// location_name. Ordered terminal_id ASC, id ASC.
func (q *Queries) ListATMsAdmin(ctx context.Context, arg ListATMsAdminParams) ([]ListATMsAdminRow, error) {
	rows, err := q.db.Query(ctx, listATMsAdmin,
		arg.Q,
		arg.Brand,
		arg.MachineType,
		arg.DeploymentType,
		arg.PriorityClass,
		arg.LocationID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListATMsAdminRow{}
	for rows.Next() {
		var i ListATMsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TerminalID,
			&i.LocationID,
			&i.LocationName,
			&i.MachineType,
			&i.Brand,
			&i.Model,
			&i.OperationHours,
			&i.DeploymentType,
			&i.CapacityAmount,
			&i.LowThresholdAmount,
			&i.CriticalThresholdAmount,
			&i.Blacklisted,
			&i.EscrowAccount,
			&i.PriorityClass,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsForSelect = `-- name: ListLocationsForSelect :many
SELECT id, name, city_or_regency, province FROM locations ORDER BY name ASC
`

type ListLocationsForSelectRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	CityOrRegency string `json:"city_or_regency"`
	Province      string `json:"province"`
}

// Backs the Location select on the ATM form (Req 6). Ordered by name.
func (q *Queries) ListLocationsForSelect(ctx context.Context) ([]ListLocationsForSelectRow, error) {
	rows, err := q.db.Query(ctx, listLocationsForSelect)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationsForSelectRow{}
	for rows.Next() {
		var i ListLocationsForSelectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CityOrRegency,
			&i.Province,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locationExists = `-- name: LocationExists :one
SELECT EXISTS(SELECT 1 FROM locations WHERE id = $1)
`

// Existence check for location_id references (400 invalid_reference if false).
func (q *Queries) LocationExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, locationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateATMAdmin = `-- name: UpdateATMAdmin :one
UPDATE atms
SET location_id = $1,
    machine_type = $2,
    brand = $3,
    model = $4,
    operation_hours = $5,
    deployment_type = $6,
    capacity_amount = $7,
    low_threshold_amount = $8,
    critical_threshold_amount = $9,
    blacklisted = $10,
    escrow_account = $11,
    priority_class = $12,
    updated_at = now()
WHERE id = $13 AND deleted_at IS NULL
RETURNING id, terminal_id, location_id, machine_type, brand, model,
          operation_hours, deployment_type, capacity_amount,
          low_threshold_amount, critical_threshold_amount, blacklisted,
          escrow_account, priority_class, is_active, created_at, updated_at, deleted_at
`

type UpdateATMAdminParams struct {
	LocationID              int64          `json:"location_id"`
	MachineType             string         `json:"machine_type"`
	Brand                   string         `json:"brand"`
	Model                   string         `json:"model"`
	OperationHours          string         `json:"operation_hours"`
	DeploymentType          string         `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric `json:"critical_threshold_amount"`
	Blacklisted             bool           `json:"blacklisted"`
	EscrowAccount           *string        `json:"escrow_account"`
	PriorityClass           *string        `json:"priority_class"`
	ID                      int64          `json:"id"`
}

type UpdateATMAdminRow struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	EscrowAccount           *string            `json:"escrow_account"`
	PriorityClass           *string            `json:"priority_class"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

// Editable fields only; terminal_id is never touched here (immutable on
// update, Req 5.6). `AND deleted_at IS NULL` makes a soft-disabled target
// update as 0 rows affected, mapped to "not found" by the repository.
func (q *Queries) UpdateATMAdmin(ctx context.Context, arg UpdateATMAdminParams) (UpdateATMAdminRow, error) {
	row := q.db.QueryRow(ctx, updateATMAdmin,
		arg.LocationID,
		arg.MachineType,
		arg.Brand,
		arg.Model,
		arg.OperationHours,
		arg.DeploymentType,
		arg.CapacityAmount,
		arg.LowThresholdAmount,
		arg.CriticalThresholdAmount,
		arg.Blacklisted,
		arg.EscrowAccount,
		arg.PriorityClass,
		arg.ID,
	)
	var i UpdateATMAdminRow
	err := row.Scan(
		&i.ID,
		&i.TerminalID,
		&i.LocationID,
		&i.MachineType,
		&i.Brand,
		&i.Model,
		&i.OperationHours,
		&i.DeploymentType,
		&i.CapacityAmount,
		&i.LowThresholdAmount,
		&i.CriticalThresholdAmount,
		&i.Blacklisted,
		&i.EscrowAccount,
		&i.PriorityClass,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
