// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*)
FROM audit_logs
WHERE ($1::bigint       IS NULL OR actor_id    = $1)
  AND ($2::text           IS NULL OR action      = $2)
  AND ($3::text      IS NULL OR entity_type = $3)
  AND ($4::bigint      IS NULL OR entity_id   = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz   IS NULL OR created_at <= $6)
`

type CountAuditLogsParams struct {
	ActorID    *int64             `json:"actor_id"`
	Action     *string            `json:"action"`
	EntityType *string            `json:"entity_type"`
	EntityID   *int64             `json:"entity_id"`
	DateFrom   pgtype.Timestamptz `json:"date_from"`
	DateTo     pgtype.Timestamptz `json:"date_to"`
}

// Mirrors ListAuditLogs' WHERE exactly (minus ORDER BY/LIMIT/OFFSET) so the
// count matches the filtered result set for pagination math.
func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, actor_id, action, entity_type, entity_id, before, after, ip, created_at
FROM audit_logs
WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.IP,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many

SELECT id, actor_id, action, entity_type, entity_id, before, after, ip, created_at
FROM audit_logs
WHERE ($1::bigint       IS NULL OR actor_id    = $1)
  AND ($2::text           IS NULL OR action      = $2)
  AND ($3::text      IS NULL OR entity_type = $3)
  AND ($4::bigint      IS NULL OR entity_id   = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz   IS NULL OR created_at <= $6)
ORDER BY created_at DESC, id DESC
LIMIT $8::int OFFSET $7::int
`

type ListAuditLogsParams struct {
	ActorID    *int64             `json:"actor_id"`
	Action     *string            `json:"action"`
	EntityType *string            `json:"entity_type"`
	EntityID   *int64             `json:"entity_id"`
	DateFrom   pgtype.Timestamptz `json:"date_from"`
	DateTo     pgtype.Timestamptz `json:"date_to"`
	Offset     int32              `json:"offset"`
	Limit      int32              `json:"limit"`
}

// Read-path queries for the Audit Log Viewer (audit-log-viewer spec, Task 2).
// Separate from queries/audit.sql (the writer's CreateAuditLog + the
// entity-scoped ListAuditLogsByEntity) to keep the read/list/paginate surface
// for the admin viewer distinct from the generic per-entity trail helper.
//
// All filters are optional (sqlc.narg): NULL means "no filter on this field".
// limit/offset are named args (not positional) so they mix cleanly with the
// narg filters under one sqlc version.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.DateFrom,
		arg.DateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.IP,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
