// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_id, action, entity_type, entity_id, before, after, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_id, action, entity_type, entity_id, before, after, ip, created_at
`

type CreateAuditLogParams struct {
	ActorID    int64   `json:"actor_id"`
	Action     string  `json:"action"`
	EntityType string  `json:"entity_type"`
	EntityID   int64   `json:"entity_id"`
	Before     []byte  `json:"before"`
	After      []byte  `json:"after"`
	IP         *string `json:"ip"`
}

// Appends one audit trail row. Append-only: no update/delete query is defined here.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.IP,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.IP,
		&i.CreatedAt,
	)
	return i, err
}
