// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dmaa_forecast.sql

package db

import (
	"context"
)

const countDmaaForecast = `-- name: CountDmaaForecast :one
SELECT count(*)
FROM dmaa_atm_forecast
WHERE
    ($1::text = '' OR periode_pred >= $1::date)
    AND ($2::text = '' OR periode_pred <= $2::date)
    AND ($3::text = '' OR terminal_id ILIKE '%' || $3::text || '%')
`

type CountDmaaForecastParams struct {
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
	TerminalID string `json:"terminal_id"`
}

// Mirrors ListDmaaForecast's WHERE exactly (minus ORDER BY/LIMIT/OFFSET) so
// the count matches the filtered result set for pagination math.
func (q *Queries) CountDmaaForecast(ctx context.Context, arg CountDmaaForecastParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDmaaForecast, arg.DateFrom, arg.DateTo, arg.TerminalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDmaaForecast = `-- name: ListDmaaForecast :many
SELECT
    terminal_id,
    dmaa_file_id,
    periode_pred,
    denom,
    amount_replenish,
    amount_refund,
    created_at
FROM dmaa_atm_forecast
WHERE
    ($1::text = '' OR periode_pred >= $1::date)
    AND ($2::text = '' OR periode_pred <= $2::date)
    AND ($3::text = '' OR terminal_id ILIKE '%' || $3::text || '%')
ORDER BY
    CASE WHEN $4::text = 'terminal_id' AND $5::text = 'asc' THEN terminal_id END ASC,
    CASE WHEN $4::text = 'terminal_id' AND $5::text = 'desc' THEN terminal_id END DESC,
    CASE WHEN $4::text = 'dmaa_file_id' AND $5::text = 'asc' THEN dmaa_file_id END ASC,
    CASE WHEN $4::text = 'dmaa_file_id' AND $5::text = 'desc' THEN dmaa_file_id END DESC,
    CASE WHEN $4::text = 'periode_pred' AND $5::text = 'asc' THEN periode_pred END ASC,
    CASE WHEN $4::text = 'periode_pred' AND $5::text = 'desc' THEN periode_pred END DESC,
    CASE WHEN $4::text = 'denom' AND $5::text = 'asc' THEN denom END ASC,
    CASE WHEN $4::text = 'denom' AND $5::text = 'desc' THEN denom END DESC,
    CASE WHEN $4::text = 'amount_replenish' AND $5::text = 'asc' THEN amount_replenish END ASC,
    CASE WHEN $4::text = 'amount_replenish' AND $5::text = 'desc' THEN amount_replenish END DESC,
    CASE WHEN $4::text = 'amount_refund' AND $5::text = 'asc' THEN amount_refund END ASC,
    CASE WHEN $4::text = 'amount_refund' AND $5::text = 'desc' THEN amount_refund END DESC,
    CASE WHEN $4::text = 'created_at' AND $5::text = 'asc' THEN created_at END ASC,
    CASE WHEN $4::text = 'created_at' AND $5::text = 'desc' THEN created_at END DESC,
    dmaa_file_id ASC,
    terminal_id ASC,
    periode_pred ASC,
    denom ASC
LIMIT $7::int OFFSET ($6::int - 1) * $7::int
`

type ListDmaaForecastParams struct {
	DateFrom   string `json:"date_from"`
	DateTo     string `json:"date_to"`
	TerminalID string `json:"terminal_id"`
	SortBy     string `json:"sort_by"`
	SortOrder  string `json:"sort_order"`
	Page       int32  `json:"page"`
	PageSize   int32  `json:"page_size"`
}

// Paginated, filtered, sorted dmaa_atm_forecast rows for the DMAA Forecast
// Viewer. Empty-string filters mean "no filter applied" (same convention as
// ListItmCashpos). Sort keys are allowlisted in the service layer. The
// trailing composite-PK tiebreaker keeps pagination deterministic when the
// chosen sort column has ties.
func (q *Queries) ListDmaaForecast(ctx context.Context, arg ListDmaaForecastParams) ([]DmaaAtmForecast, error) {
	rows, err := q.db.Query(ctx, listDmaaForecast,
		arg.DateFrom,
		arg.DateTo,
		arg.TerminalID,
		arg.SortBy,
		arg.SortOrder,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmaaAtmForecast{}
	for rows.Next() {
		var i DmaaAtmForecast
		if err := rows.Scan(
			&i.TerminalID,
			&i.DmaaFileID,
			&i.PeriodePred,
			&i.Denom,
			&i.AmountReplenish,
			&i.AmountRefund,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
