// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: master_data.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMasterDataChangeRequests = `-- name: CountMasterDataChangeRequests :one
SELECT COUNT(*) FROM master_data_change_requests
WHERE ($1::text IS NULL OR entity_type = $1::text)
  AND ($2::bigint IS NULL OR entity_id = $2::bigint)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountMasterDataChangeRequestsParams struct {
	EntityType *string `json:"entity_type"`
	EntityID   *int64  `json:"entity_id"`
	Status     *string `json:"status"`
}

// Same filters as ListMasterDataChangeRequests, for pagination total.
func (q *Queries) CountMasterDataChangeRequests(ctx context.Context, arg CountMasterDataChangeRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMasterDataChangeRequests, arg.EntityType, arg.EntityID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMasterDataChangeRequest = `-- name: CreateMasterDataChangeRequest :one

INSERT INTO master_data_change_requests (entity_type, entity_id, op, payload, before, maker_id, batch_id)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, entity_type, entity_id, op, payload, before, status, maker_id, approval_request_id, batch_id, error, created_at, updated_at
`

type CreateMasterDataChangeRequestParams struct {
	EntityType string `json:"entity_type"`
	EntityID   *int64 `json:"entity_id"`
	Op         string `json:"op"`
	Payload    []byte `json:"payload"`
	Before     []byte `json:"before"`
	MakerID    int64  `json:"maker_id"`
	BatchID    *int64 `json:"batch_id"`
}

// Master data maker-checker (plan.md Fase 1/2): sqlc queries for
// master_data_change_requests, the generic staging table every master-data
// create/update/disable/enable goes through before being applied.
// Submit (T2.1). entity_id is NULL for op='create'.
func (q *Queries) CreateMasterDataChangeRequest(ctx context.Context, arg CreateMasterDataChangeRequestParams) (MasterDataChangeRequest, error) {
	row := q.db.QueryRow(ctx, createMasterDataChangeRequest,
		arg.EntityType,
		arg.EntityID,
		arg.Op,
		arg.Payload,
		arg.Before,
		arg.MakerID,
		arg.BatchID,
	)
	var i MasterDataChangeRequest
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Op,
		&i.Payload,
		&i.Before,
		&i.Status,
		&i.MakerID,
		&i.ApprovalRequestID,
		&i.BatchID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMasterDataImportBatch = `-- name: CreateMasterDataImportBatch :one
INSERT INTO master_data_import_batches (entity, file_hash, maker_id, row_count)
VALUES ($1, $2, $3, $4)
RETURNING id, entity, file_hash, maker_id, row_count, created_at
`

type CreateMasterDataImportBatchParams struct {
	Entity   string `json:"entity"`
	FileHash string `json:"file_hash"`
	MakerID  int64  `json:"maker_id"`
	RowCount int32  `json:"row_count"`
}

// Import confirm (T5.4). Runs in the same transaction as the change-request inserts.
func (q *Queries) CreateMasterDataImportBatch(ctx context.Context, arg CreateMasterDataImportBatchParams) (MasterDataImportBatch, error) {
	row := q.db.QueryRow(ctx, createMasterDataImportBatch,
		arg.Entity,
		arg.FileHash,
		arg.MakerID,
		arg.RowCount,
	)
	var i MasterDataImportBatch
	err := row.Scan(
		&i.ID,
		&i.Entity,
		&i.FileHash,
		&i.MakerID,
		&i.RowCount,
		&i.CreatedAt,
	)
	return i, err
}

const findOpenMasterDataImportBatch = `-- name: FindOpenMasterDataImportBatch :one
SELECT b.id, b.entity, b.file_hash, b.maker_id, b.row_count, b.created_at,
       h.id AS head_id, h.approval_request_id, h.status AS head_status
FROM master_data_import_batches b
JOIN LATERAL (
    SELECT c.id, c.approval_request_id, c.status
    FROM master_data_change_requests c
    WHERE c.batch_id = b.id
    ORDER BY c.id
    LIMIT 1
) h ON true
WHERE b.entity = $1 AND b.file_hash = $2
  AND h.status NOT IN ('rejected', 'stale')
ORDER BY b.id DESC
LIMIT 1
`

type FindOpenMasterDataImportBatchParams struct {
	Entity   string `json:"entity"`
	FileHash string `json:"file_hash"`
}

type FindOpenMasterDataImportBatchRow struct {
	ID                int64              `json:"id"`
	Entity            string             `json:"entity"`
	FileHash          string             `json:"file_hash"`
	MakerID           int64              `json:"maker_id"`
	RowCount          int32              `json:"row_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	HeadID            int64              `json:"head_id"`
	ApprovalRequestID *int64             `json:"approval_request_id"`
	HeadStatus        string             `json:"head_status"`
}

// Idempotency lookup (T5.4): the latest batch of this file whose changes were
// not rejected/stale (a rejected/stale file may be uploaded again). head_id is
// the first change request, the approval's document_id.
func (q *Queries) FindOpenMasterDataImportBatch(ctx context.Context, arg FindOpenMasterDataImportBatchParams) (FindOpenMasterDataImportBatchRow, error) {
	row := q.db.QueryRow(ctx, findOpenMasterDataImportBatch, arg.Entity, arg.FileHash)
	var i FindOpenMasterDataImportBatchRow
	err := row.Scan(
		&i.ID,
		&i.Entity,
		&i.FileHash,
		&i.MakerID,
		&i.RowCount,
		&i.CreatedAt,
		&i.HeadID,
		&i.ApprovalRequestID,
		&i.HeadStatus,
	)
	return i, err
}

const findPendingMasterDataChangeRequest = `-- name: FindPendingMasterDataChangeRequest :one
SELECT id, status FROM master_data_change_requests
WHERE entity_type = $1
  AND entity_id IS NOT DISTINCT FROM $2
  AND status = 'pending'
`

type FindPendingMasterDataChangeRequestParams struct {
	EntityType string `json:"entity_type"`
	EntityID   *int64 `json:"entity_id"`
}

type FindPendingMasterDataChangeRequestRow struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

// Idempotency guard (T2.2): reject a second submit while one is already
// pending for this entity. entity_type/entity_id pair matches the table's
// partial unique index.
func (q *Queries) FindPendingMasterDataChangeRequest(ctx context.Context, arg FindPendingMasterDataChangeRequestParams) (FindPendingMasterDataChangeRequestRow, error) {
	row := q.db.QueryRow(ctx, findPendingMasterDataChangeRequest, arg.EntityType, arg.EntityID)
	var i FindPendingMasterDataChangeRequestRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getMasterDataChangeRequestByID = `-- name: GetMasterDataChangeRequestByID :one
SELECT id, entity_type, entity_id, op, payload, before, status, maker_id, approval_request_id, batch_id, error, created_at, updated_at
FROM master_data_change_requests WHERE id = $1
`

func (q *Queries) GetMasterDataChangeRequestByID(ctx context.Context, id int64) (MasterDataChangeRequest, error) {
	row := q.db.QueryRow(ctx, getMasterDataChangeRequestByID, id)
	var i MasterDataChangeRequest
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Op,
		&i.Payload,
		&i.Before,
		&i.Status,
		&i.MakerID,
		&i.ApprovalRequestID,
		&i.BatchID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMasterDataChangeRequests = `-- name: ListMasterDataChangeRequests :many
SELECT id, entity_type, entity_id, op, payload, before, status, maker_id, approval_request_id, batch_id, error, created_at, updated_at
FROM master_data_change_requests
WHERE ($1::text IS NULL OR entity_type = $1::text)
  AND ($2::bigint IS NULL OR entity_id = $2::bigint)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListMasterDataChangeRequestsParams struct {
	EntityType *string `json:"entity_type"`
	EntityID   *int64  `json:"entity_id"`
	Status     *string `json:"status"`
	PageOffset int64   `json:"page_offset"`
	PageLimit  int64   `json:"page_limit"`
}

// Read endpoint (T2.7): filter by entity_type, entity_id, and/or status, all
// optional. entity_id lets a caller look up the pending/applied change
// history for one specific row (e.g. a per-row "pending approval" badge).
func (q *Queries) ListMasterDataChangeRequests(ctx context.Context, arg ListMasterDataChangeRequestsParams) ([]MasterDataChangeRequest, error) {
	rows, err := q.db.Query(ctx, listMasterDataChangeRequests,
		arg.EntityType,
		arg.EntityID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterDataChangeRequest{}
	for rows.Next() {
		var i MasterDataChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Op,
			&i.Payload,
			&i.Before,
			&i.Status,
			&i.MakerID,
			&i.ApprovalRequestID,
			&i.BatchID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterDataChangeRequestsByBatch = `-- name: ListMasterDataChangeRequestsByBatch :many
SELECT id, entity_type, entity_id, op, payload, before, status, maker_id, approval_request_id, batch_id, error, created_at, updated_at
FROM master_data_change_requests
WHERE batch_id = $1
ORDER BY id
`

func (q *Queries) ListMasterDataChangeRequestsByBatch(ctx context.Context, batchID *int64) ([]MasterDataChangeRequest, error) {
	rows, err := q.db.Query(ctx, listMasterDataChangeRequestsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterDataChangeRequest{}
	for rows.Next() {
		var i MasterDataChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Op,
			&i.Payload,
			&i.Before,
			&i.Status,
			&i.MakerID,
			&i.ApprovalRequestID,
			&i.BatchID,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMasterDataChangeRequestApplied = `-- name: MarkMasterDataChangeRequestApplied :exec
UPDATE master_data_change_requests SET status = 'applied', error = NULL
WHERE id = $1
`

// Apply-on-approve success path (T2.4), same transaction as the entity mutation.
func (q *Queries) MarkMasterDataChangeRequestApplied(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMasterDataChangeRequestApplied, id)
	return err
}

const markMasterDataChangeRequestApplyFailed = `-- name: MarkMasterDataChangeRequestApplyFailed :exec
UPDATE master_data_change_requests SET error = $1
WHERE id = $2
`

type MarkMasterDataChangeRequestApplyFailedParams struct {
	Error *string `json:"error"`
	ID    int64   `json:"id"`
}

// Apply failed and rolled back (T2.4): stays approved, not applied, error recorded for retry/diagnosis.
func (q *Queries) MarkMasterDataChangeRequestApplyFailed(ctx context.Context, arg MarkMasterDataChangeRequestApplyFailedParams) error {
	_, err := q.db.Exec(ctx, markMasterDataChangeRequestApplyFailed, arg.Error, arg.ID)
	return err
}

const markMasterDataChangeRequestApproved = `-- name: MarkMasterDataChangeRequestApproved :exec
UPDATE master_data_change_requests SET status = 'approved'
WHERE id = $1
`

// Approval reached its final step (T2.4): status flips to 'approved' before
// the apply attempt is made, durably and independent of whether apply then
// succeeds -- if apply fails and its own transaction rolls back, this
// status persists as the documented "approved-but-not-applied" state.
func (q *Queries) MarkMasterDataChangeRequestApproved(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMasterDataChangeRequestApproved, id)
	return err
}

const markMasterDataChangeRequestRejected = `-- name: MarkMasterDataChangeRequestRejected :exec
UPDATE master_data_change_requests SET status = 'rejected'
WHERE id = $1
`

// Reject path (T2.6): no entity mutation, just the status transition.
func (q *Queries) MarkMasterDataChangeRequestRejected(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMasterDataChangeRequestRejected, id)
	return err
}

const markMasterDataChangeRequestStale = `-- name: MarkMasterDataChangeRequestStale :exec
UPDATE master_data_change_requests SET status = 'stale', error = $1
WHERE id = $2
`

type MarkMasterDataChangeRequestStaleParams struct {
	Error *string `json:"error"`
	ID    int64   `json:"id"`
}

// Staleness detected at apply time (T2.5): current entity state no longer matches `before`.
func (q *Queries) MarkMasterDataChangeRequestStale(ctx context.Context, arg MarkMasterDataChangeRequestStaleParams) error {
	_, err := q.db.Exec(ctx, markMasterDataChangeRequestStale, arg.Error, arg.ID)
	return err
}

const setMasterDataBatchApprovalID = `-- name: SetMasterDataBatchApprovalID :exec
UPDATE master_data_change_requests SET approval_request_id = $1
WHERE batch_id = $2
`

type SetMasterDataBatchApprovalIDParams struct {
	ApprovalRequestID *int64 `json:"approval_request_id"`
	BatchID           *int64 `json:"batch_id"`
}

// Links every change request of the batch to the batch's single approval request.
func (q *Queries) SetMasterDataBatchApprovalID(ctx context.Context, arg SetMasterDataBatchApprovalIDParams) error {
	_, err := q.db.Exec(ctx, setMasterDataBatchApprovalID, arg.ApprovalRequestID, arg.BatchID)
	return err
}

const setMasterDataChangeRequestApprovalID = `-- name: SetMasterDataChangeRequestApprovalID :exec
UPDATE master_data_change_requests SET approval_request_id = $1
WHERE id = $2
`

type SetMasterDataChangeRequestApprovalIDParams struct {
	ApprovalRequestID *int64 `json:"approval_request_id"`
	ID                int64  `json:"id"`
}

// Links the staged row to the approval_requests row Orchestrator.SubmitForApproval created (T2.1).
func (q *Queries) SetMasterDataChangeRequestApprovalID(ctx context.Context, arg SetMasterDataChangeRequestApprovalIDParams) error {
	_, err := q.db.Exec(ctx, setMasterDataChangeRequestApprovalID, arg.ApprovalRequestID, arg.ID)
	return err
}
