// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Explicit fallback: while from_user_id cannot act (see user_leaves), to_user_id acts in their place. Overlap-range rejection is enforced at the admin endpoint layer (Task 8), not here.
type ApprovalDelegation struct {
	ID         int64              `json:"id"`
	FromUserID int64              `json:"from_user_id"`
	ToUserID   int64              `json:"to_user_id"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
	Reason     *string            `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Threshold config: (document_type, amount range) -> required_level for maker-checker approval routing.
type ApprovalPolicy struct {
	ID           int64  `json:"id"`
	DocumentType string `json:"document_type"`
	// Inclusive lower bound of the amount range this policy covers.
	MinAmount pgtype.Numeric `json:"min_amount"`
	// Exclusive upper bound of the amount range this policy covers.
	MaxAmount pgtype.Numeric `json:"max_amount"`
	// Approval level (matches users.approval_level) the request must climb to when it falls in this range.
	RequiredLevel int32              `json:"required_level"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// One row per document under approval. Idempotent per (document_type, document_id).
type ApprovalRequest struct {
	ID            int64          `json:"id"`
	MakerID       int64          `json:"maker_id"`
	DocumentType  string         `json:"document_type"`
	DocumentID    int64          `json:"document_id"`
	Amount        pgtype.Numeric `json:"amount"`
	RequiredLevel int32          `json:"required_level"`
	// draft | pending | approved | rejected
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One row per approval level a request must pass through. acted_by_id may differ from assigned_approver_id (delegate acted instead).
type ApprovalStep struct {
	ID                 int64 `json:"id"`
	RequestID          int64 `json:"request_id"`
	StepLevel          int32 `json:"step_level"`
	AssignedApproverID int64 `json:"assigned_approver_id"`
	// Who actually acted on this step — the assigned approver, or their delegate if on leave. NULL until acted.
	ActedByID *int64 `json:"acted_by_id"`
	// pending | approved | rejected
	Status    string             `json:"status"`
	ActedAt   pgtype.Timestamptz `json:"acted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Atm struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	// Escrow account number per ATM from MASTER_ATM_ESQ.Escrow (12-digit identifier, stored as text). See migration 030.
	EscrowAccount *string `json:"escrow_account"`
	// ATM priority tier from MASTER_ATM_ESQ.PriorityClass: VIP | Non VIP | Industri. Per-ATM (varies within a vendor branch), so stored on atms not vendor_packages. See migration 030.
	PriorityClass *string `json:"priority_class"`
}

type AtmDenom struct {
	ID      int64 `json:"id"`
	AtmID   int64 `json:"atm_id"`
	DenomID int64 `json:"denom_id"`
}

type AtmVendorPackage struct {
	ID                 int64              `json:"id"`
	AtmID              int64              `json:"atm_id"`
	VendorPackageID    int64              `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date        `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date        `json:"effective_end_date"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Append-only audit trail: who (actor_id) did what (action) to which entity, before/after state, from where (ip). No update/delete query exists in code.
type AuditLog struct {
	ID      int64 `json:"id"`
	ActorID int64 `json:"actor_id"`
	// Free-form verb, e.g. submit | approve | reject | create | update.
	Action string `json:"action"`
	// Domain entity the action targets, e.g. approval_request, invoice.
	EntityType string             `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	IP         *string            `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Currency struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Denom struct {
	ID        int64              `json:"id"`
	CurrID    int64              `json:"curr_id"`
	Denom     pgtype.Numeric     `json:"denom"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DmaaAtmForecast struct {
	TerminalID      string             `json:"terminal_id"`
	DmaaFileID      int64              `json:"dmaa_file_id"`
	PeriodePred     pgtype.Date        `json:"periode_pred"`
	Denom           int32              `json:"denom"`
	AmountReplenish int64              `json:"amount_replenish"`
	AmountRefund    int64              `json:"amount_refund"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DmaaFile struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	IsValid      bool               `json:"is_valid"`
	FileDate     pgtype.Date        `json:"file_date"`
	SourceSystem *string            `json:"source_system"`
	Checksum     *string            `json:"checksum"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DsrDailyRow struct {
	ID       int64 `json:"id"`
	UploadID int64 `json:"upload_id"`
	// Sheet line order (1..n) across both sections, excluding headers and derived subtotal/saldo rows. Stable ordering key for reproducing the statement.
	RowNo int32 `json:"row_no"`
	// Vault/site block header the row belongs to (e.g. LENTENG AGUNG, BINTARO). NULL for single-vault workbooks like BIJAK, which print one block.
	Location *string `json:"location"`
	// d0 = section 1 (report_date, settled, sampai pukul 00:00). d1 = section 2 (daily_status_date, status sementara).
	Section string `json:"section"`
	// saldo_awal = opening balance (d0 only). penerimaan / pengeluaran = receipt / disbursement line, sign stored verbatim as printed. status_cadangan = STATUS UANG CADANGAN ATM lines (Layak Edar / Rusak), d1 only.
	Flow string `json:"flow"`
	// Uraian text verbatim, e.g. Dari CIMB Niaga CIT, Untuk Cartridge Replenishment ATM & CRM.
	LineLabel string `json:"line_label"`
	// Memo/reference embedded in a line label, e.g. 313/ATM/BIJAK/VII/2026. NULL when the line carries none.
	MemoNo *string `json:"memo_no"`
	// Value attributable to the 100,000 denomination, verbatim as printed (the sheet labels this block "Denom (lembar)" but prints money). NULL when the source cell was an Excel error -- counts into daily_error_count.
	Denom100kIdr pgtype.Numeric `json:"denom_100k_idr"`
	Denom50kIdr  pgtype.Numeric `json:"denom_50k_idr"`
	Denom20kIdr  pgtype.Numeric `json:"denom_20k_idr"`
	Denom10kIdr  pgtype.Numeric `json:"denom_10k_idr"`
	Denom5kIdr   pgtype.Numeric `json:"denom_5k_idr"`
	Denom2kIdr   pgtype.Numeric `json:"denom_2k_idr"`
	Denom1kIdr   pgtype.Numeric `json:"denom_1k_idr"`
	// Total Rupiah x1.000 column, verbatim as printed. Cross-check: equals SUM(denom_*_idr) when no denom cell is NULL.
	LineTotalIdr pgtype.Numeric     `json:"line_total_idr"`
	Remarks      *string            `json:"remarks"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DsrRencanaIsiRow struct {
	ID       int64 `json:"id"`
	UploadID int64 `json:"upload_id"`
	RowNo    int32 `json:"row_no"`
	// ATM ID column as sent by the vendor (e.g. 2440, A353, ZZVX). Verbatim, never overwritten -- this is the evidence of what the vendor claimed.
	AtmTerminalID string `json:"atm_terminal_id"`
	// Resolved at ingest from atm_terminal_id. NULL = ATM not in master data; the file still ingests (counts into rencana_isi_error_count). Find unresolved rows WHERE atm_id IS NULL.
	AtmID *int64 `json:"atm_id"`
	// Lokasi ATM column verbatim, e.g. JKT.AMBASADOR 1.
	AtmLocation *string `json:"atm_location"`
	// Denom (x 1.000) column as printed: 50 | 100 | TST. TST rows are recyclers and carry both fill_100k_idr and fill_50k_idr.
	DenomConfig *string        `json:"denom_config"`
	Fill100kIdr pgtype.Numeric `json:"fill_100k_idr"`
	Fill50kIdr  pgtype.Numeric `json:"fill_50k_idr"`
	// Saldo Splank Pukul 08:00 column, verbatim as printed. 0 on TST/recycler rows in the sample.
	SplankBalance0800Idr pgtype.Numeric `json:"splank_balance_0800_idr"`
	// Keterangan column verbatim, e.g. PENDING DSR TGL 16/07/2026.
	Remarks   *string            `json:"remarks"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One row per ingested DSR workbook. Idempotent per checksum; re-ingest = delete this row, both sheets child rows cascade.
type DsrUpload struct {
	ID       int64   `json:"id"`
	Filename string  `json:"filename"`
	Checksum *string `json:"checksum"`
	// Vendor label as printed (e.g. BIJAK JAKARTA). Not yet FK to vendors.code.
	Vendor string `json:"vendor"`
	// Daily sheet Tanggal cell (e.g. 2026-07-15). Cross-checked against the filename.
	ReportDate pgtype.Date `json:"report_date"`
	// users.id of the vendor user who uploaded, resolved server-side from the JWT. NULL for manual backfill.
	UploadedByUserID     *int64  `json:"uploaded_by_user_id"`
	Bank                 *string `json:"bank"`
	Company              *string `json:"company"`
	Recipient            *string `json:"recipient"`
	Sender               *string `json:"sender"`
	Subject              *string `json:"subject"`
	PreparedBy           *string `json:"prepared_by"`
	CheckedBy            *string `json:"checked_by"`
	ApprovedBy           *string `json:"approved_by"`
	Currency             string  `json:"currency"`
	DailyStatus          string  `json:"daily_status"`
	DailyRowCount        *int32  `json:"daily_row_count"`
	DailyErrorCount      *int32  `json:"daily_error_count"`
	RencanaIsiStatus     string  `json:"rencana_isi_status"`
	RencanaIsiRowCount   *int32  `json:"rencana_isi_row_count"`
	RencanaIsiErrorCount *int32  `json:"rencana_isi_error_count"`
	ErrorMessage         *string `json:"error_message"`
	// Section-2 provisional date on Daily (STATUS SALDO SEMENTARA), normally report_date + 1.
	DailyStatusDate pgtype.Date `json:"daily_status_date"`
	// Tanggal cell on Rencana Isi: the day being planned, normally report_date + 1.
	RencanaIsiPlanDate    pgtype.Date    `json:"rencana_isi_plan_date"`
	SaldoAkhir0000Idr     pgtype.Numeric `json:"saldo_akhir_0000_idr"`
	SaldoSementara0900Idr pgtype.Numeric `json:"saldo_sementara_0900_idr"`
	StatusCadanganIdr     pgtype.Numeric `json:"status_cadangan_idr"`
	SaldoGabunganIdr      pgtype.Numeric `json:"saldo_gabungan_idr"`
	// Vendor-stated Sub Total of the fill plan. Must equal the Daily d1 Subtotal Pengeluaran total -- the one cross-sheet tie in the workbook.
	RencanaIsiSubtotalIdr pgtype.Numeric     `json:"rencana_isi_subtotal_idr"`
	ProcessedAt           pgtype.Timestamptz `json:"processed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ItmCashpo struct {
	ID     int64 `json:"id"`
	FileID int64 `json:"file_id"`
	// Business date parsed from the source filename
	CashposDate pgtype.Date `json:"cashpos_date"`
	TerminalID  string      `json:"terminal_id"`
	// ATM50K | ATM100K | CRM
	MachineType      string         `json:"machine_type"`
	TellerID         string         `json:"teller_id"`
	BranchCode       string         `json:"branch_code"`
	StartingCash10k  pgtype.Numeric `json:"starting_cash_10k"`
	CashIn10k        pgtype.Numeric `json:"cash_in_10k"`
	CashOut10k       pgtype.Numeric `json:"cash_out_10k"`
	CashPosition10k  pgtype.Numeric `json:"cash_position_10k"`
	StartingCash20k  pgtype.Numeric `json:"starting_cash_20k"`
	CashIn20k        pgtype.Numeric `json:"cash_in_20k"`
	CashOut20k       pgtype.Numeric `json:"cash_out_20k"`
	CashPosition20k  pgtype.Numeric `json:"cash_position_20k"`
	StartingCash50k  pgtype.Numeric `json:"starting_cash_50k"`
	CashIn50k        pgtype.Numeric `json:"cash_in_50k"`
	CashOut50k       pgtype.Numeric `json:"cash_out_50k"`
	CashPosition50k  pgtype.Numeric `json:"cash_position_50k"`
	StartingCash100k pgtype.Numeric `json:"starting_cash_100k"`
	CashIn100k       pgtype.Numeric `json:"cash_in_100k"`
	CashOut100k      pgtype.Numeric `json:"cash_out_100k"`
	CashPosition100k pgtype.Numeric `json:"cash_position_100k"`
	// Source indicator from POSITION_SOURCE, for example CURRENT or REPLENISH
	PositionSource string             `json:"position_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ItmCashposFile struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Business date parsed from the source filename
	FileDate pgtype.Date `json:"file_date"`
	Checksum *string     `json:"checksum"`
	// pending | processing | completed | failed
	Status       string             `json:"status"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ItmReplenish struct {
	ID     int64 `json:"id"`
	FileID int64 `json:"file_id"`
	// Parsed from TGLREPLENISH raw format (1YYMMDD)
	ReplenishDate pgtype.Date `json:"replenish_date"`
	// Parsed from JAMREPLENISH raw format (HHMMSS without separators)
	ReplenishTime pgtype.Time `json:"replenish_time"`
	TerminalID    string      `json:"terminal_id"`
	// ATM50K | ATM100K | CRM
	MachineType string `json:"machine_type"`
	TellerID    string `json:"teller_id"`
	BranchCode  string `json:"branch_code"`
	// Escrow balance at time of replenishment (19-digit raw value from ITM)
	Escrow             pgtype.Numeric     `json:"escrow"`
	RefundDenom10k     pgtype.Numeric     `json:"refund_denom_10k"`
	RefundDenom20k     pgtype.Numeric     `json:"refund_denom_20k"`
	RefundDenom50k     pgtype.Numeric     `json:"refund_denom_50k"`
	RefundDenom100k    pgtype.Numeric     `json:"refund_denom_100k"`
	RefundTotal        pgtype.Numeric     `json:"refund_total"`
	ReplenishDenom10k  pgtype.Numeric     `json:"replenish_denom_10k"`
	ReplenishDenom20k  pgtype.Numeric     `json:"replenish_denom_20k"`
	ReplenishDenom50k  pgtype.Numeric     `json:"replenish_denom_50k"`
	ReplenishDenom100k pgtype.Numeric     `json:"replenish_denom_100k"`
	ReplenishTotal     pgtype.Numeric     `json:"replenish_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ItmReplenishFile struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Business date the file represents (from filename)
	FileDate pgtype.Date `json:"file_date"`
	Checksum *string     `json:"checksum"`
	// pending | processing | completed | failed
	Status       string             `json:"status"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID            int64              `json:"id"`
	RegionID      int64              `json:"region_id"`
	Type          string             `json:"type"`
	Name          string             `json:"name"`
	AddressLine1  string             `json:"address_line1"`
	AddressLine2  *string            `json:"address_line2"`
	Rt            *string            `json:"rt"`
	Rw            *string            `json:"rw"`
	Kelurahan     *string            `json:"kelurahan"`
	Kecamatan     *string            `json:"kecamatan"`
	CityOrRegency string             `json:"city_or_regency"`
	Province      string             `json:"province"`
	PostalCode    *string            `json:"postal_code"`
	CountryCode   string             `json:"country_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MenuFeature struct {
	ID        int64              `json:"id"`
	ParentID  *int64             `json:"parent_id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	Kind      string             `json:"kind"`
	SortOrder int32              `json:"sort_order"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Region    *string            `json:"region"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID int64 `json:"id"`
	// ADMIN | ADMIN_PARAM | ATM-USER | ATM-SPV | BRANCH-USER | BRANCH-SPV | BRANCH-ATM-USER | BRANCH-ATM-SPV | VENDOR-USER | APPACCESS
	Role        string             `json:"role"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID            int64              `json:"id"`
	RoleID        int64              `json:"role_id"`
	MenuFeatureID int64              `json:"menu_feature_id"`
	GrantedBy     int64              `json:"granted_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID     int64 `json:"id"`
	RoleID int64 `json:"role_id"`
	// Nullable for external/vendor users
	EmployeeID *string `json:"employee_id"`
	Username   string  `json:"username"`
	FullName   string  `json:"full_name"`
	Email      string  `json:"email"`
	IsKaryawan bool    `json:"is_karyawan"`
	// ldap | local
	AuthSource string `json:"auth_source"`
	// Only for auth_source=local
	PasswordHash *string `json:"password_hash"`
	// Required for vendor/local users, null for internal LDAP users
	VendorID    *int64             `json:"vendor_id"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	// Optional: pins a vendor user to one vendor_branches row. Must belong to the same vendor as vendor_id (enforced in app). NULL for internal/LDAP users.
	VendorBranchID *int64 `json:"vendor_branch_id"`
	// Direct supervisor in the reporting line (self-FK, tree). NULL = top of hierarchy or not yet assigned.
	SupervisorID *int64 `json:"supervisor_id"`
	// Explicit approval level for maker-checker routing, independent of role_id. NULL = not an approver.
	ApprovalLevel *int32 `json:"approval_level"`
	// Local-password policy only (auth_source=local|local_dev): last password change, basis for the 90-day expiry / 7-day warning window. NULL = not yet evaluated. Ignored for auth_source=ldap.
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	// Local-password policy only: true forces a password change on next login (set by APPACCESS set-initial-password, or after admin unlock). Ignored for auth_source=ldap.
	MustChangePassword bool `json:"must_change_password"`
	// Local-password policy only: consecutive failed local-login attempts; resets to 0 on success. 3 -> account locked (see locked_until). Ignored for auth_source=ldap.
	FailedLoginAttempts int32 `json:"failed_login_attempts"`
	// Local-password policy only: account locked until this timestamp (30 min after the 3rd consecutive failed login), or NULL if not locked. Ignored for auth_source=ldap.
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

// Explicit unavailability windows. The resolver (Task 5) checks for an overlap with now() to decide whether an approver is on leave.
type UserLeave struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Reason    *string            `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vendor struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	// 3-uppercase-char prefix embedded in vendor_requests.request_number (Req 4, Q1). NULL falls back to a deterministic service-side derivation from vendors.code.
	RequestPrefix *string `json:"request_prefix"`
}

type VendorBranch struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// Vendor regional grouping from MASTER_ATM_ESQ.FLMVendorRegion (e.g. "Jakarta Timur"). Distinct from regions.region (ATM geographic area) and branch_name (vendor sub-region). See migration 030.
	Region *string `json:"region"`
}

type VendorPackage struct {
	ID             int64              `json:"id"`
	VendorBranchID int64              `json:"vendor_branch_id"`
	Code           string             `json:"code"`
	PriorityClass  string             `json:"priority_class"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Cash replenishment request to a CIT vendor, composed from DMAA forecast rows; state machine + maker-checker.
type VendorRequest struct {
	ID            int64       `json:"id"`
	RequestNumber string      `json:"request_number"`
	ForecastDate  pgtype.Date `json:"forecast_date"`
	// draft | pending_approval | approved | rejected | processing | completed | failed | cancelled
	Status          string             `json:"status"`
	Notes           *string            `json:"notes"`
	CreatedBy       int64              `json:"created_by"`
	ApprovedBy      *int64             `json:"approved_by"`
	RejectedBy      *int64             `json:"rejected_by"`
	RejectionReason *string            `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectedAt      pgtype.Timestamptz `json:"rejected_at"`
	// Soft-cancel flag (Req 5); row/items are never deleted on cancel.
	IsCanceled bool `json:"is_canceled"`
	// Manual_Request classification: planned | emergency | additional. NULL for legacy rows AND for standard non-manual (Forecast Browser) requests -- see design.md Q-resolution.
	RequestCategory *string `json:"request_category"`
	// Vendor-facing delivery date chosen by the operator (Req 2/3), distinct from forecast_date. NULL only for legacy rows.
	ReplenishDate pgtype.Date `json:"replenish_date"`
	// True when items were entered directly without a matching dmaa_atm_forecast row (Req 3).
	IsManual bool `json:"is_manual"`
	// Single resolved CIT vendor this request is constrained to (Req 4, Q2); drives the request-number vendor prefix. NULL only for legacy VR-... rows.
	VendorID *int64 `json:"vendor_id"`
	// Reason captured on cancel (Req 3.2/3.3). NULL for non-canceled rows and for rows canceled before this column existed (their reason lives only in audit_logs.after).
	CancellationReason *string `json:"cancellation_reason"`
}

// Line items of a vendor_request, each referencing an ATM/date/denom row from dmaa_atm_forecast.
type VendorRequestItem struct {
	ID              int64 `json:"id"`
	VendorRequestID int64 `json:"vendor_request_id"`
	// ATM identifier; maps to requirements.md "atm_id" and dmaa_atm_forecast.terminal_id. Labeled "ATM ID" in the API/frontend.
	TerminalID      string             `json:"terminal_id"`
	PeriodePred     pgtype.Date        `json:"periode_pred"`
	Denom           int32              `json:"denom"`
	AmountReplenish int64              `json:"amount_replenish"`
	AmountRefund    int64              `json:"amount_refund"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	// Manual-request brand (Req 3, Q4); NULL for DMAA-backed rows, which derive it at read time.
	Brand *string `json:"brand"`
	// Manual-request ATM location (Req 3, Q4); NULL for DMAA-backed rows, which derive it at read time.
	LokasiAtm *string `json:"lokasi_atm"`
}

// Atomic per-(vendor, replenish_date) sequence backing the REP<prefix><YYYYMMDD><seq> request-number format (Req 4, Q3).
type VendorRequestNumberSeq struct {
	VendorID int64       `json:"vendor_id"`
	SeqDate  pgtype.Date `json:"seq_date"`
	LastSeq  int32       `json:"last_seq"`
}

type VendorVault struct {
	ID             int64  `json:"id"`
	VendorBranchID int64  `json:"vendor_branch_id"`
	VaultCode      string `json:"vault_code"`
	// Type of vault (e.g. main, transit, buffer)
	Type              string         `json:"type"`
	Amount            pgtype.Numeric `json:"amount"`
	MaxCapacityAmount pgtype.Numeric `json:"max_capacity_amount"`
	MinCapacityAmount pgtype.Numeric `json:"min_capacity_amount"`
	// ISO 4217 currency code (e.g. IDR, USD)
	CurrencyCode string             `json:"currency_code"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
