// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Atm struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type AtmDenom struct {
	ID      int64 `json:"id"`
	AtmID   int64 `json:"atm_id"`
	DenomID int64 `json:"denom_id"`
}

type AtmVendorPackage struct {
	ID                 int64              `json:"id"`
	AtmID              int64              `json:"atm_id"`
	VendorPackageID    int64              `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date        `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date        `json:"effective_end_date"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Currency struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Denom struct {
	ID        int64              `json:"id"`
	CurrID    int64              `json:"curr_id"`
	Denom     pgtype.Numeric     `json:"denom"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DmaaAtmForecast struct {
	TerminalID      string             `json:"terminal_id"`
	DmaaFileID      int64              `json:"dmaa_file_id"`
	PeriodePred     pgtype.Date        `json:"periode_pred"`
	Denom           int32              `json:"denom"`
	AmountReplenish int64              `json:"amount_replenish"`
	AmountRefund    int64              `json:"amount_refund"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DmaaFile struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	IsValid      bool               `json:"is_valid"`
	FileDate     pgtype.Date        `json:"file_date"`
	SourceSystem *string            `json:"source_system"`
	Checksum     *string            `json:"checksum"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DsrDailyRow struct {
	ID       int64 `json:"id"`
	UploadID int64 `json:"upload_id"`
	// Sheet line order (1..n) across both sections, excluding headers and derived subtotal/saldo rows. Stable ordering key for reproducing the statement.
	RowNo int32 `json:"row_no"`
	// Vault/site block header the row belongs to (e.g. LENTENG AGUNG, BINTARO). NULL for single-vault workbooks like BIJAK, which print one block.
	Location *string `json:"location"`
	// d0 = section 1 (report_date, settled, sampai pukul 00:00). d1 = section 2 (daily_status_date, status sementara).
	Section string `json:"section"`
	// saldo_awal = opening balance (d0 only). penerimaan / pengeluaran = receipt / disbursement line, sign stored verbatim as printed. status_cadangan = STATUS UANG CADANGAN ATM lines (Layak Edar / Rusak), d1 only.
	Flow string `json:"flow"`
	// Uraian text verbatim, e.g. Dari CIMB Niaga CIT, Untuk Cartridge Replenishment ATM & CRM.
	LineLabel string `json:"line_label"`
	// Memo/reference embedded in a line label, e.g. 313/ATM/BIJAK/VII/2026. NULL when the line carries none.
	MemoNo *string `json:"memo_no"`
	// Value attributable to the 100,000 denomination, verbatim as printed (the sheet labels this block "Denom (lembar)" but prints money). NULL when the source cell was an Excel error -- counts into daily_error_count.
	Denom100kIdr pgtype.Numeric `json:"denom_100k_idr"`
	Denom50kIdr  pgtype.Numeric `json:"denom_50k_idr"`
	Denom20kIdr  pgtype.Numeric `json:"denom_20k_idr"`
	Denom10kIdr  pgtype.Numeric `json:"denom_10k_idr"`
	Denom5kIdr   pgtype.Numeric `json:"denom_5k_idr"`
	Denom2kIdr   pgtype.Numeric `json:"denom_2k_idr"`
	Denom1kIdr   pgtype.Numeric `json:"denom_1k_idr"`
	// Total Rupiah x1.000 column, verbatim as printed. Cross-check: equals SUM(denom_*_idr) when no denom cell is NULL.
	LineTotalIdr pgtype.Numeric     `json:"line_total_idr"`
	Remarks      *string            `json:"remarks"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DsrRencanaIsiRow struct {
	ID       int64 `json:"id"`
	UploadID int64 `json:"upload_id"`
	RowNo    int32 `json:"row_no"`
	// ATM ID column as sent by the vendor (e.g. 2440, A353, ZZVX). Verbatim, never overwritten -- this is the evidence of what the vendor claimed.
	AtmTerminalID string `json:"atm_terminal_id"`
	// Resolved at ingest from atm_terminal_id. NULL = ATM not in master data; the file still ingests (counts into rencana_isi_error_count). Find unresolved rows WHERE atm_id IS NULL.
	AtmID *int64 `json:"atm_id"`
	// Lokasi ATM column verbatim, e.g. JKT.AMBASADOR 1.
	AtmLocation *string `json:"atm_location"`
	// Denom (x 1.000) column as printed: 50 | 100 | TST. TST rows are recyclers and carry both fill_100k_idr and fill_50k_idr.
	DenomConfig *string        `json:"denom_config"`
	Fill100kIdr pgtype.Numeric `json:"fill_100k_idr"`
	Fill50kIdr  pgtype.Numeric `json:"fill_50k_idr"`
	// Saldo Splank Pukul 08:00 column, verbatim as printed. 0 on TST/recycler rows in the sample.
	SplankBalance0800Idr pgtype.Numeric `json:"splank_balance_0800_idr"`
	// Keterangan column verbatim, e.g. PENDING DSR TGL 16/07/2026.
	Remarks   *string            `json:"remarks"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One row per ingested DSR workbook. Idempotent per checksum; re-ingest = delete this row, both sheets child rows cascade.
type DsrUpload struct {
	ID       int64   `json:"id"`
	Filename string  `json:"filename"`
	Checksum *string `json:"checksum"`
	// Vendor label as printed (e.g. BIJAK JAKARTA). Not yet FK to vendors.code.
	Vendor string `json:"vendor"`
	// Daily sheet Tanggal cell (e.g. 2026-07-15). Cross-checked against the filename.
	ReportDate pgtype.Date `json:"report_date"`
	// users.id of the vendor user who uploaded, resolved server-side from the JWT. NULL for manual backfill.
	UploadedByUserID     *int64  `json:"uploaded_by_user_id"`
	Bank                 *string `json:"bank"`
	Company              *string `json:"company"`
	Recipient            *string `json:"recipient"`
	Sender               *string `json:"sender"`
	Subject              *string `json:"subject"`
	PreparedBy           *string `json:"prepared_by"`
	CheckedBy            *string `json:"checked_by"`
	ApprovedBy           *string `json:"approved_by"`
	Currency             string  `json:"currency"`
	DailyStatus          string  `json:"daily_status"`
	DailyRowCount        *int32  `json:"daily_row_count"`
	DailyErrorCount      *int32  `json:"daily_error_count"`
	RencanaIsiStatus     string  `json:"rencana_isi_status"`
	RencanaIsiRowCount   *int32  `json:"rencana_isi_row_count"`
	RencanaIsiErrorCount *int32  `json:"rencana_isi_error_count"`
	ErrorMessage         *string `json:"error_message"`
	// Section-2 provisional date on Daily (STATUS SALDO SEMENTARA), normally report_date + 1.
	DailyStatusDate pgtype.Date `json:"daily_status_date"`
	// Tanggal cell on Rencana Isi: the day being planned, normally report_date + 1.
	RencanaIsiPlanDate    pgtype.Date    `json:"rencana_isi_plan_date"`
	SaldoAkhir0000Idr     pgtype.Numeric `json:"saldo_akhir_0000_idr"`
	SaldoSementara0900Idr pgtype.Numeric `json:"saldo_sementara_0900_idr"`
	StatusCadanganIdr     pgtype.Numeric `json:"status_cadangan_idr"`
	SaldoGabunganIdr      pgtype.Numeric `json:"saldo_gabungan_idr"`
	// Vendor-stated Sub Total of the fill plan. Must equal the Daily d1 Subtotal Pengeluaran total -- the one cross-sheet tie in the workbook.
	RencanaIsiSubtotalIdr pgtype.Numeric     `json:"rencana_isi_subtotal_idr"`
	ProcessedAt           pgtype.Timestamptz `json:"processed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ItmCashpo struct {
	ID     int64 `json:"id"`
	FileID int64 `json:"file_id"`
	// Business date parsed from the source filename
	CashposDate pgtype.Date `json:"cashpos_date"`
	TerminalID  string      `json:"terminal_id"`
	// ATM50K | ATM100K | CRM
	MachineType      string         `json:"machine_type"`
	TellerID         string         `json:"teller_id"`
	BranchCode       string         `json:"branch_code"`
	StartingCash10k  pgtype.Numeric `json:"starting_cash_10k"`
	CashIn10k        pgtype.Numeric `json:"cash_in_10k"`
	CashOut10k       pgtype.Numeric `json:"cash_out_10k"`
	CashPosition10k  pgtype.Numeric `json:"cash_position_10k"`
	StartingCash20k  pgtype.Numeric `json:"starting_cash_20k"`
	CashIn20k        pgtype.Numeric `json:"cash_in_20k"`
	CashOut20k       pgtype.Numeric `json:"cash_out_20k"`
	CashPosition20k  pgtype.Numeric `json:"cash_position_20k"`
	StartingCash50k  pgtype.Numeric `json:"starting_cash_50k"`
	CashIn50k        pgtype.Numeric `json:"cash_in_50k"`
	CashOut50k       pgtype.Numeric `json:"cash_out_50k"`
	CashPosition50k  pgtype.Numeric `json:"cash_position_50k"`
	StartingCash100k pgtype.Numeric `json:"starting_cash_100k"`
	CashIn100k       pgtype.Numeric `json:"cash_in_100k"`
	CashOut100k      pgtype.Numeric `json:"cash_out_100k"`
	CashPosition100k pgtype.Numeric `json:"cash_position_100k"`
	// Source indicator from POSITION_SOURCE, for example CURRENT or REPLENISH
	PositionSource string             `json:"position_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ItmCashposFile struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Business date parsed from the source filename
	FileDate pgtype.Date `json:"file_date"`
	Checksum *string     `json:"checksum"`
	// pending | processing | completed | failed
	Status       string             `json:"status"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ItmReplenish struct {
	ID     int64 `json:"id"`
	FileID int64 `json:"file_id"`
	// Parsed from TGLREPLENISH raw format (1YYMMDD)
	ReplenishDate pgtype.Date `json:"replenish_date"`
	// Parsed from JAMREPLENISH raw format (HHMMSS without separators)
	ReplenishTime pgtype.Time `json:"replenish_time"`
	TerminalID    string      `json:"terminal_id"`
	// ATM50K | ATM100K | CRM
	MachineType string `json:"machine_type"`
	TellerID    string `json:"teller_id"`
	BranchCode  string `json:"branch_code"`
	// Escrow balance at time of replenishment (19-digit raw value from ITM)
	Escrow             pgtype.Numeric     `json:"escrow"`
	RefundDenom10k     pgtype.Numeric     `json:"refund_denom_10k"`
	RefundDenom20k     pgtype.Numeric     `json:"refund_denom_20k"`
	RefundDenom50k     pgtype.Numeric     `json:"refund_denom_50k"`
	RefundDenom100k    pgtype.Numeric     `json:"refund_denom_100k"`
	RefundTotal        pgtype.Numeric     `json:"refund_total"`
	ReplenishDenom10k  pgtype.Numeric     `json:"replenish_denom_10k"`
	ReplenishDenom20k  pgtype.Numeric     `json:"replenish_denom_20k"`
	ReplenishDenom50k  pgtype.Numeric     `json:"replenish_denom_50k"`
	ReplenishDenom100k pgtype.Numeric     `json:"replenish_denom_100k"`
	ReplenishTotal     pgtype.Numeric     `json:"replenish_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ItmReplenishFile struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Business date the file represents (from filename)
	FileDate pgtype.Date `json:"file_date"`
	Checksum *string     `json:"checksum"`
	// pending | processing | completed | failed
	Status       string             `json:"status"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LateDetection struct {
	ID             pgtype.UUID        `json:"id"`
	FileType       string             `json:"file_type"`
	ProcessingDate pgtype.Date        `json:"processing_date"`
	SlaDeadline    pgtype.Time        `json:"sla_deadline"`
	DetectedAt     pgtype.Timestamptz `json:"detected_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	IsResolved     bool               `json:"is_resolved"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID            int64              `json:"id"`
	RegionID      int64              `json:"region_id"`
	Type          string             `json:"type"`
	Name          string             `json:"name"`
	AddressLine1  string             `json:"address_line1"`
	AddressLine2  *string            `json:"address_line2"`
	Rt            *string            `json:"rt"`
	Rw            *string            `json:"rw"`
	Kelurahan     *string            `json:"kelurahan"`
	Kecamatan     *string            `json:"kecamatan"`
	CityOrRegency string             `json:"city_or_regency"`
	Province      string             `json:"province"`
	PostalCode    *string            `json:"postal_code"`
	CountryCode   string             `json:"country_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Region    *string            `json:"region"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RetryAuditLog struct {
	ID pgtype.UUID `json:"id"`
	// retry_initiated | retry_completed
	EventType string `json:"event_type"`
	// auto | manual
	TriggerType    string             `json:"trigger_type"`
	FileID         pgtype.UUID        `json:"file_id"`
	FileType       string             `json:"file_type"`
	FileChecksum   *string            `json:"file_checksum"`
	ProcessingDate pgtype.Date        `json:"processing_date"`
	InitiatedBy    string             `json:"initiated_by"`
	Outcome        *string            `json:"outcome"`
	DurationMs     *int32             `json:"duration_ms"`
	ErrorDetail    *string            `json:"error_detail"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RetryFileTracking struct {
	ID pgtype.UUID `json:"id"`
	// dmaa | itm_cashpos | itm_replenish
	FileType       string      `json:"file_type"`
	Filename       string      `json:"filename"`
	FilePath       string      `json:"file_path"`
	FileChecksum   string      `json:"file_checksum"`
	ProcessingDate pgtype.Date `json:"processing_date"`
	// not_processed | input_remaining
	DetectionSource string  `json:"detection_source"`
	FailureReason   *string `json:"failure_reason"`
	// pending | processing | completed | failed | max_retries_exhausted
	ProcessingStatus string             `json:"processing_status"`
	AutoRetryCount   int32              `json:"auto_retry_count"`
	MaxRetries       int32              `json:"max_retries"`
	DetectedAt       pgtype.Timestamptz `json:"detected_at"`
	LastRetryAt      pgtype.Timestamptz `json:"last_retry_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID int64 `json:"id"`
	// ADMIN | ADMIN_PARAM | ATM-USER | ATM-SPV | BRANCH-USER | BRANCH-SPV | BRANCH-ATM-USER | BRANCH-ATM-SPV | VENDOR-USER
	Role        string             `json:"role"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ScanRun struct {
	ID pgtype.UUID `json:"id"`
	// failure_detection | late_detection
	ScanType   string             `json:"scan_type"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	// running | success | failed
	Status        string             `json:"status"`
	FilesDetected *int32             `json:"files_detected"`
	ErrorMessage  *string            `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID     int64 `json:"id"`
	RoleID int64 `json:"role_id"`
	// Nullable for external/vendor users
	EmployeeID *string `json:"employee_id"`
	Username   string  `json:"username"`
	FullName   string  `json:"full_name"`
	Email      string  `json:"email"`
	IsKaryawan bool    `json:"is_karyawan"`
	// ldap | local
	AuthSource string `json:"auth_source"`
	// Only for auth_source=local
	PasswordHash *string `json:"password_hash"`
	// Required for vendor/local users, null for internal LDAP users
	VendorID    *int64             `json:"vendor_id"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	// Optional: pins a vendor user to one vendor_branches row. Must belong to the same vendor as vendor_id (enforced in app). NULL for internal/LDAP users.
	VendorBranchID *int64 `json:"vendor_branch_id"`
}

type Vendor struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type VendorBranch struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type VendorPackage struct {
	ID             int64              `json:"id"`
	VendorBranchID int64              `json:"vendor_branch_id"`
	Code           string             `json:"code"`
	PriorityClass  string             `json:"priority_class"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VendorVault struct {
	ID             int64  `json:"id"`
	VendorBranchID int64  `json:"vendor_branch_id"`
	VaultCode      string `json:"vault_code"`
	// Type of vault (e.g. main, transit, buffer)
	Type              string         `json:"type"`
	Amount            pgtype.Numeric `json:"amount"`
	MaxCapacityAmount pgtype.Numeric `json:"max_capacity_amount"`
	MinCapacityAmount pgtype.Numeric `json:"min_capacity_amount"`
	// ISO 4217 currency code (e.g. IDR, USD)
	CurrencyCode string             `json:"currency_code"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
