// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Atm struct {
	ID                      int64              `json:"id"`
	TerminalID              string             `json:"terminal_id"`
	LocationID              int64              `json:"location_id"`
	MachineType             string             `json:"machine_type"`
	Brand                   string             `json:"brand"`
	Model                   string             `json:"model"`
	OperationHours          string             `json:"operation_hours"`
	DeploymentType          string             `json:"deployment_type"`
	CapacityAmount          pgtype.Numeric     `json:"capacity_amount"`
	LowThresholdAmount      pgtype.Numeric     `json:"low_threshold_amount"`
	CriticalThresholdAmount pgtype.Numeric     `json:"critical_threshold_amount"`
	Blacklisted             bool               `json:"blacklisted"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type AtmDenom struct {
	ID      int64 `json:"id"`
	AtmID   int64 `json:"atm_id"`
	DenomID int64 `json:"denom_id"`
}

type AtmVendorPackage struct {
	ID                 int64              `json:"id"`
	AtmID              int64              `json:"atm_id"`
	VendorPackageID    int64              `json:"vendor_package_id"`
	EffectiveStartDate pgtype.Date        `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date        `json:"effective_end_date"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Currency struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Denom struct {
	ID        int64              `json:"id"`
	CurrID    int64              `json:"curr_id"`
	Denom     pgtype.Numeric     `json:"denom"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DmaaAtmForecast struct {
	TerminalID      string             `json:"terminal_id"`
	DmaaFileID      int64              `json:"dmaa_file_id"`
	PeriodePred     pgtype.Date        `json:"periode_pred"`
	Denom           int32              `json:"denom"`
	AmountReplenish int64              `json:"amount_replenish"`
	AmountRefund    int64              `json:"amount_refund"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DmaaFile struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	IsValid      bool               `json:"is_valid"`
	FileDate     pgtype.Date        `json:"file_date"`
	SourceSystem *string            `json:"source_system"`
	Checksum     *string            `json:"checksum"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ItmCashpo struct {
	ID     int64 `json:"id"`
	FileID int64 `json:"file_id"`
	// Business date parsed from the source filename
	CashposDate pgtype.Date `json:"cashpos_date"`
	TerminalID  string      `json:"terminal_id"`
	// ATM50K | ATM100K | CRM
	MachineType      string         `json:"machine_type"`
	TellerID         string         `json:"teller_id"`
	BranchCode       string         `json:"branch_code"`
	StartingCash10k  pgtype.Numeric `json:"starting_cash_10k"`
	CashIn10k        pgtype.Numeric `json:"cash_in_10k"`
	CashOut10k       pgtype.Numeric `json:"cash_out_10k"`
	CashPosition10k  pgtype.Numeric `json:"cash_position_10k"`
	StartingCash20k  pgtype.Numeric `json:"starting_cash_20k"`
	CashIn20k        pgtype.Numeric `json:"cash_in_20k"`
	CashOut20k       pgtype.Numeric `json:"cash_out_20k"`
	CashPosition20k  pgtype.Numeric `json:"cash_position_20k"`
	StartingCash50k  pgtype.Numeric `json:"starting_cash_50k"`
	CashIn50k        pgtype.Numeric `json:"cash_in_50k"`
	CashOut50k       pgtype.Numeric `json:"cash_out_50k"`
	CashPosition50k  pgtype.Numeric `json:"cash_position_50k"`
	StartingCash100k pgtype.Numeric `json:"starting_cash_100k"`
	CashIn100k       pgtype.Numeric `json:"cash_in_100k"`
	CashOut100k      pgtype.Numeric `json:"cash_out_100k"`
	CashPosition100k pgtype.Numeric `json:"cash_position_100k"`
	// Source indicator from POSITION_SOURCE, for example CURRENT or REPLENISH
	PositionSource string             `json:"position_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ItmCashposFile struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Business date parsed from the source filename
	FileDate pgtype.Date `json:"file_date"`
	Checksum *string     `json:"checksum"`
	// pending | processing | completed | failed
	Status       string             `json:"status"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ItmReplenish struct {
	ID     int64 `json:"id"`
	FileID int64 `json:"file_id"`
	// Parsed from TGLREPLENISH raw format (1YYMMDD)
	ReplenishDate pgtype.Date `json:"replenish_date"`
	// Parsed from JAMREPLENISH raw format (HHMMSS without separators)
	ReplenishTime pgtype.Time `json:"replenish_time"`
	TerminalID    string      `json:"terminal_id"`
	// ATM50K | ATM100K | CRM
	MachineType string `json:"machine_type"`
	TellerID    string `json:"teller_id"`
	BranchCode  string `json:"branch_code"`
	// Escrow balance at time of replenishment (19-digit raw value from ITM)
	Escrow             pgtype.Numeric     `json:"escrow"`
	RefundDenom10k     pgtype.Numeric     `json:"refund_denom_10k"`
	RefundDenom20k     pgtype.Numeric     `json:"refund_denom_20k"`
	RefundDenom50k     pgtype.Numeric     `json:"refund_denom_50k"`
	RefundDenom100k    pgtype.Numeric     `json:"refund_denom_100k"`
	RefundTotal        pgtype.Numeric     `json:"refund_total"`
	ReplenishDenom10k  pgtype.Numeric     `json:"replenish_denom_10k"`
	ReplenishDenom20k  pgtype.Numeric     `json:"replenish_denom_20k"`
	ReplenishDenom50k  pgtype.Numeric     `json:"replenish_denom_50k"`
	ReplenishDenom100k pgtype.Numeric     `json:"replenish_denom_100k"`
	ReplenishTotal     pgtype.Numeric     `json:"replenish_total"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ItmReplenishFile struct {
	ID       int64  `json:"id"`
	Filename string `json:"filename"`
	// Business date the file represents (from filename)
	FileDate pgtype.Date `json:"file_date"`
	Checksum *string     `json:"checksum"`
	// pending | processing | completed | failed
	Status       string             `json:"status"`
	RowCount     *int32             `json:"row_count"`
	SuccessCount *int32             `json:"success_count"`
	ErrorCount   *int32             `json:"error_count"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID            int64              `json:"id"`
	RegionID      int64              `json:"region_id"`
	Type          string             `json:"type"`
	Name          string             `json:"name"`
	AddressLine1  string             `json:"address_line1"`
	AddressLine2  *string            `json:"address_line2"`
	Rt            *string            `json:"rt"`
	Rw            *string            `json:"rw"`
	Kelurahan     *string            `json:"kelurahan"`
	Kecamatan     *string            `json:"kecamatan"`
	CityOrRegency string             `json:"city_or_regency"`
	Province      string             `json:"province"`
	PostalCode    *string            `json:"postal_code"`
	CountryCode   string             `json:"country_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Region    *string            `json:"region"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID int64 `json:"id"`
	// ADMIN | ADMIN_PARAM | ATM-USER | ATM-SPV | BRANCH-USER | BRANCH-SPV | BRANCH-ATM-USER | BRANCH-ATM-SPV | VENDOR-USER
	Role        string             `json:"role"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID     int64 `json:"id"`
	RoleID int64 `json:"role_id"`
	// Nullable for external/vendor users
	EmployeeID *string `json:"employee_id"`
	Username   string  `json:"username"`
	FullName   string  `json:"full_name"`
	Email      string  `json:"email"`
	IsKaryawan bool    `json:"is_karyawan"`
	// ldap | local
	AuthSource string `json:"auth_source"`
	// Only for auth_source=local
	PasswordHash *string `json:"password_hash"`
	// Required for vendor/local users, null for internal LDAP users
	VendorID *int64 `json:"vendor_id"`
	// Optional: pins a vendor user to one vendor_branches row. Must belong to the same vendor as vendor_id (enforced in app). NULL for internal/LDAP users.
	VendorBranchID *int64             `json:"vendor_branch_id"`
	IsActive       bool               `json:"is_active"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Vendor struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type VendorBranch struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type VendorPackage struct {
	ID             int64              `json:"id"`
	VendorBranchID int64              `json:"vendor_branch_id"`
	Code           string             `json:"code"`
	PriorityClass  string             `json:"priority_class"`
	Price          pgtype.Numeric     `json:"price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VendorVault struct {
	ID             int64  `json:"id"`
	VendorBranchID int64  `json:"vendor_branch_id"`
	VaultCode      string `json:"vault_code"`
	// Type of vault (e.g. main, transit, buffer)
	Type              string         `json:"type"`
	Amount            pgtype.Numeric `json:"amount"`
	MaxCapacityAmount pgtype.Numeric `json:"max_capacity_amount"`
	MinCapacityAmount pgtype.Numeric `json:"min_capacity_amount"`
	// ISO 4217 currency code (e.g. IDR, USD)
	CurrencyCode string             `json:"currency_code"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
