// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingNotificationEmails = `-- name: ClaimPendingNotificationEmails :many
SELECT id, to_address, subject, body, attempts
FROM notification_emails
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY next_attempt_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimPendingNotificationEmailsRow struct {
	ID        int64  `json:"id"`
	ToAddress string `json:"to_address"`
	Subject   string `json:"subject"`
	Body      string `json:"body"`
	Attempts  int32  `json:"attempts"`
}

// Row locks held until the caller's tx ends; SKIP LOCKED keeps a second
// cmd/api instance from sending the same email.
func (q *Queries) ClaimPendingNotificationEmails(ctx context.Context, limit int32) ([]ClaimPendingNotificationEmailsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingNotificationEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingNotificationEmailsRow{}
	for rows.Next() {
		var i ClaimPendingNotificationEmailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ToAddress,
			&i.Subject,
			&i.Body,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotificationsForUser = `-- name: CountNotificationsForUser :one
SELECT count(*)
FROM notifications
WHERE recipient_user_id = $1
  AND (NOT $2::boolean OR is_read = false)
`

type CountNotificationsForUserParams struct {
	UserID     int64 `json:"user_id"`
	UnreadOnly bool  `json:"unread_only"`
}

func (q *Queries) CountNotificationsForUser(ctx context.Context, arg CountNotificationsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsForUser, arg.UserID, arg.UnreadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE recipient_user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientUserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldNotificationEmails = `-- name: DeleteOldNotificationEmails :execrows
DELETE FROM notification_emails
WHERE created_at < $1 AND status IN ('sent', 'failed', 'skipped')
`

func (q *Queries) DeleteOldNotificationEmails(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotificationEmails, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :execrows
DELETE FROM notifications WHERE created_at < $1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, before pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotifications, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (recipient_user_id, type, title, body, link, entity_type, entity_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertNotificationParams struct {
	RecipientUserID int64   `json:"recipient_user_id"`
	Type            string  `json:"type"`
	Title           string  `json:"title"`
	Body            string  `json:"body"`
	Link            *string `json:"link"`
	EntityType      *string `json:"entity_type"`
	EntityID        *int64  `json:"entity_id"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.RecipientUserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.EntityType,
		arg.EntityID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertNotificationEmail = `-- name: InsertNotificationEmail :exec
INSERT INTO notification_emails (notification_id, to_address, subject, body, status)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNotificationEmailParams struct {
	NotificationID *int64 `json:"notification_id"`
	ToAddress      string `json:"to_address"`
	Subject        string `json:"subject"`
	Body           string `json:"body"`
	Status         string `json:"status"`
}

func (q *Queries) InsertNotificationEmail(ctx context.Context, arg InsertNotificationEmailParams) error {
	_, err := q.db.Exec(ctx, insertNotificationEmail,
		arg.NotificationID,
		arg.ToAddress,
		arg.Subject,
		arg.Body,
		arg.Status,
	)
	return err
}

const listActiveUserRecipientsByIDs = `-- name: ListActiveUserRecipientsByIDs :many

SELECT u.id, u.email
FROM users u
WHERE u.id = ANY($1::bigint[])
  AND u.is_active = true AND u.deleted_at IS NULL
`

type ListActiveUserRecipientsByIDsRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

// Notifikasi in-app + outbox email (Phase 0.3, .claude/sdlc/notification/spec.md).
func (q *Queries) ListActiveUserRecipientsByIDs(ctx context.Context, ids []int64) ([]ListActiveUserRecipientsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserRecipientsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUserRecipientsByIDsRow{}
	for rows.Next() {
		var i ListActiveUserRecipientsByIDsRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUserRecipientsByRoles = `-- name: ListActiveUserRecipientsByRoles :many
SELECT u.id, u.email
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE r.role = ANY($1::text[])
  AND u.is_active = true AND u.deleted_at IS NULL
`

type ListActiveUserRecipientsByRolesRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) ListActiveUserRecipientsByRoles(ctx context.Context, roles []string) ([]ListActiveUserRecipientsByRolesRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserRecipientsByRoles, roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUserRecipientsByRolesRow{}
	for rows.Next() {
		var i ListActiveUserRecipientsByRolesRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUserRecipientsByVendors = `-- name: ListActiveUserRecipientsByVendors :many
SELECT u.id, u.email
FROM users u
WHERE u.vendor_id = ANY($1::bigint[])
  AND u.is_active = true AND u.deleted_at IS NULL
`

type ListActiveUserRecipientsByVendorsRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) ListActiveUserRecipientsByVendors(ctx context.Context, vendorIds []int64) ([]ListActiveUserRecipientsByVendorsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserRecipientsByVendors, vendorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUserRecipientsByVendorsRow{}
	for rows.Next() {
		var i ListActiveUserRecipientsByVendorsRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, type, title, body, link, is_read, created_at
FROM notifications
WHERE recipient_user_id = $1
  AND (NOT $2::boolean OR is_read = false)
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListNotificationsForUserParams struct {
	UserID     int64 `json:"user_id"`
	UnreadOnly bool  `json:"unread_only"`
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListNotificationsForUserRow struct {
	ID        int64              `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Link      *string            `json:"link"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]ListNotificationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser,
		arg.UserID,
		arg.UnreadOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsForUserRow{}
	for rows.Next() {
		var i ListNotificationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorNotificationPicEmails = `-- name: ListVendorNotificationPicEmails :many
SELECT p.email::text AS email
FROM vendor_pics p
WHERE p.vendor_id = ANY($1::bigint[])
  AND p.is_notification_recipient = true
  AND p.is_active = true AND p.deleted_at IS NULL
  AND COALESCE(btrim(p.email), '') <> ''
`

// PIC vendor bukan user: email saja, tanpa notifikasi in-app.
func (q *Queries) ListVendorNotificationPicEmails(ctx context.Context, vendorIds []int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listVendorNotificationPicEmails, vendorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET is_read = true, read_at = now()
WHERE recipient_user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, recipientUserID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, recipientUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationEmailFailed = `-- name: MarkNotificationEmailFailed :exec
UPDATE notification_emails
SET status = 'failed', attempts = attempts + 1, last_error = $1
WHERE id = $2
`

type MarkNotificationEmailFailedParams struct {
	LastError *string `json:"last_error"`
	ID        int64   `json:"id"`
}

func (q *Queries) MarkNotificationEmailFailed(ctx context.Context, arg MarkNotificationEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationEmailFailed, arg.LastError, arg.ID)
	return err
}

const markNotificationEmailRetry = `-- name: MarkNotificationEmailRetry :exec
UPDATE notification_emails
SET attempts = attempts + 1, last_error = $1, next_attempt_at = $2
WHERE id = $3
`

type MarkNotificationEmailRetryParams struct {
	LastError     *string            `json:"last_error"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	ID            int64              `json:"id"`
}

func (q *Queries) MarkNotificationEmailRetry(ctx context.Context, arg MarkNotificationEmailRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationEmailRetry, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}

const markNotificationEmailSent = `-- name: MarkNotificationEmailSent :exec
UPDATE notification_emails
SET status = 'sent', sent_at = now(), attempts = attempts + 1, last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkNotificationEmailSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNotificationEmailSent, id)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET is_read = true, read_at = COALESCE(read_at, now())
WHERE id = $1 AND recipient_user_id = $2
RETURNING id
`

type MarkNotificationReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Idempotent: an already-read row still matches (read_at kept), so the
// handler answers 204; no row = not the caller's (404, no existence leak).
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
