// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regions_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveLocationsByRegion = `-- name: CountActiveLocationsByRegion :one
SELECT COUNT(*) FROM locations WHERE region_id = $1
`

// Referential-integrity check backing Disable (Req 4.2/7.2). See NOTE above:
// locations has no is_active column, so this counts every locations row
// referencing the region (all are implicitly active).
func (q *Queries) CountActiveLocationsByRegion(ctx context.Context, regionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLocationsByRegion, regionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegionsAdmin = `-- name: CountRegionsAdmin :one
SELECT COUNT(*)
FROM regions r
WHERE ($1::text IS NULL
        OR r.code ILIKE '%' || $1::text || '%'
        OR r.region ILIKE '%' || $1::text || '%')
  AND (
        $2::text = 'all'
        OR ($2::text = 'active' AND r.is_active = true)
        OR ($2::text = 'inactive' AND r.is_active = false)
      )
`

type CountRegionsAdminParams struct {
	Q      *string `json:"q"`
	Status string  `json:"status"`
}

// Same filters as ListRegionsAdmin, no LIMIT/OFFSET/JOIN -- pagination total.
func (q *Queries) CountRegionsAdmin(ctx context.Context, arg CountRegionsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegionsAdmin, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegionAdmin = `-- name: CreateRegionAdmin :one
INSERT INTO regions (code, region)
VALUES ($1, $2)
RETURNING id, code, region, created_at, updated_at, is_active, deleted_at
`

type CreateRegionAdminParams struct {
	Code   string  `json:"code"`
	Region *string `json:"region"`
}

// code is stored pre-normalized (trim+uppercase) by the service; is_active
// defaults to true (migration 018).
func (q *Queries) CreateRegionAdmin(ctx context.Context, arg CreateRegionAdminParams) (Region, error) {
	row := q.db.QueryRow(ctx, createRegionAdmin, arg.Code, arg.Region)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const disableRegionAdmin = `-- name: DisableRegionAdmin :one
UPDATE regions
SET is_active = false, deleted_at = now()
WHERE id = $1 AND is_active = true
RETURNING id, code, region, created_at, updated_at, is_active, deleted_at
`

// Soft-disable: is_active=false, deleted_at=now(). WHERE guard makes it
// idempotent-safe (0 rows affected if already inactive); the service still
// pre-checks status to return a clear 409 (Req 4.7).
func (q *Queries) DisableRegionAdmin(ctx context.Context, id int64) (Region, error) {
	row := q.db.QueryRow(ctx, disableRegionAdmin, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const enableRegionAdmin = `-- name: EnableRegionAdmin :one
UPDATE regions
SET is_active = true, deleted_at = NULL
WHERE id = $1 AND is_active = false
RETURNING id, code, region, created_at, updated_at, is_active, deleted_at
`

// Reverses DisableRegionAdmin: is_active=true, deleted_at=NULL.
func (q *Queries) EnableRegionAdmin(ctx context.Context, id int64) (Region, error) {
	row := q.db.QueryRow(ctx, enableRegionAdmin, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const findRegionByCode = `-- name: FindRegionByCode :one
SELECT id FROM regions WHERE code = $1
`

// Uniqueness pre-check (incl. soft-deleted) for create (Req 2.2, 2.7).
func (q *Queries) FindRegionByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, findRegionByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRegionAdminByID = `-- name: GetRegionAdminByID :one
SELECT r.id, r.code, r.region, r.created_at, r.updated_at, r.is_active, r.deleted_at,
       COUNT(l.id) AS location_count
FROM regions r
LEFT JOIN locations l ON l.region_id = r.id
WHERE r.id = $1
GROUP BY r.id
`

type GetRegionAdminByIDRow struct {
	ID            int64              `json:"id"`
	Code          string             `json:"code"`
	Region        *string            `json:"region"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IsActive      bool               `json:"is_active"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	LocationCount int64              `json:"location_count"`
}

// Includes soft-deleted rows -- 404 pre-checks on update/disable/enable are
// decided by the service, same convention as GetATMAdminByID.
func (q *Queries) GetRegionAdminByID(ctx context.Context, id int64) (GetRegionAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getRegionAdminByID, id)
	var i GetRegionAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.DeletedAt,
		&i.LocationCount,
	)
	return i, err
}

const listRegionsAdmin = `-- name: ListRegionsAdmin :many

SELECT r.id, r.code, r.region, r.created_at, r.updated_at, r.is_active, r.deleted_at,
       COUNT(l.id) AS location_count
FROM regions r
LEFT JOIN locations l ON l.region_id = r.id
WHERE ($1::text IS NULL
        OR r.code ILIKE '%' || $1::text || '%'
        OR r.region ILIKE '%' || $1::text || '%')
  AND (
        $2::text = 'all'
        OR ($2::text = 'active' AND r.is_active = true)
        OR ($2::text = 'inactive' AND r.is_active = false)
      )
GROUP BY r.id
ORDER BY r.code ASC, r.id ASC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListRegionsAdminParams struct {
	Q          *string `json:"q"`
	Status     string  `json:"status"`
	PageOffset int64   `json:"page_offset"`
	PageLimit  int64   `json:"page_limit"`
}

type ListRegionsAdminRow struct {
	ID            int64              `json:"id"`
	Code          string             `json:"code"`
	Region        *string            `json:"region"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IsActive      bool               `json:"is_active"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	LocationCount int64              `json:"location_count"`
}

// Admin Region Management (.kiro/specs/region-management, Task 2): sqlc
// queries for the admin region CRUD endpoints. No new tables -- regions
// already exists (001_baseline_schema.sql); migration 018 added
// is_active/deleted_at for soft-disable.
//
// NOTE on "active locations": the design doc's referential-integrity check
// (Req 4.2/7.2) assumes a `locations.is_active` column, but `locations` has
// no such column and no soft-delete concept at all (confirmed against
// 001_baseline_schema.sql -- this feature's requirements explicitly exclude
// changing `locations`). Every `locations` row is therefore treated as
// implicitly active: "dependent active locations" below means "any
// locations row referencing the region", with no is_active filter.
// Filters: q (ILIKE on code OR region, case-insensitive; region is nullable
// so a NULL never matches, which is correct) and status (sqlc.arg,
// all|active|inactive). location_count = dependent locations rows (see NOTE
// above -- no is_active filter exists on locations). Ordered code ASC, id ASC.
func (q *Queries) ListRegionsAdmin(ctx context.Context, arg ListRegionsAdminParams) ([]ListRegionsAdminRow, error) {
	rows, err := q.db.Query(ctx, listRegionsAdmin,
		arg.Q,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionsAdminRow{}
	for rows.Next() {
		var i ListRegionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Region,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.DeletedAt,
			&i.LocationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegionName = `-- name: UpdateRegionName :one
UPDATE regions
SET region = $1
WHERE id = $2
RETURNING id, code, region, created_at, updated_at, is_active, deleted_at
`

type UpdateRegionNameParams struct {
	Region *string `json:"region"`
	ID     int64   `json:"id"`
}

// Display name only -- code is immutable after create (Req 3.1/3.2).
// updated_at is set by the existing trg_regions_set_updated_at trigger, not
// here.
func (q *Queries) UpdateRegionName(ctx context.Context, arg UpdateRegionNameParams) (Region, error) {
	row := q.db.QueryRow(ctx, updateRegionName, arg.Region, arg.ID)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Region,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}
