// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT COUNT(*)
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE ($1::text IS NULL
        OR u.username ILIKE '%' || $1::text || '%'
        OR u.full_name ILIKE '%' || $1::text || '%'
        OR u.email ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR r.role = $2::text)
  AND ($3::bigint IS NULL OR u.vendor_id = $3::bigint)
  AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND u.deleted_at IS NULL)
        OR ($4::text = 'disabled' AND u.deleted_at IS NOT NULL)
      )
`

type CountUsersAdminParams struct {
	Q        *string `json:"q"`
	Role     *string `json:"role"`
	VendorID *int64  `json:"vendor_id"`
	Status   string  `json:"status"`
}

// Same filters as ListUsersAdmin, no LIMIT/OFFSET — pagination total (Req 2.8).
func (q *Queries) CountUsersAdmin(ctx context.Context, arg CountUsersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin,
		arg.Q,
		arg.Role,
		arg.VendorID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAdmin = `-- name: CreateUserAdmin :one
INSERT INTO users (
    role_id, employee_id, username, full_name, email, is_karyawan,
    auth_source, password_hash, vendor_id, supervisor_id, approval_level,
    must_change_password
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12
)
RETURNING id, username, full_name, email, role_id, is_karyawan, auth_source,
          employee_id, vendor_id, is_active, deleted_at, supervisor_id,
          approval_level, last_login_at
`

type CreateUserAdminParams struct {
	RoleID             int64   `json:"role_id"`
	EmployeeID         *string `json:"employee_id"`
	Username           string  `json:"username"`
	FullName           string  `json:"full_name"`
	Email              string  `json:"email"`
	IsKaryawan         bool    `json:"is_karyawan"`
	AuthSource         string  `json:"auth_source"`
	PasswordHash       *string `json:"password_hash"`
	VendorID           *int64  `json:"vendor_id"`
	SupervisorID       *int64  `json:"supervisor_id"`
	ApprovalLevel      *int32  `json:"approval_level"`
	MustChangePassword bool    `json:"must_change_password"`
}

type CreateUserAdminRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	FullName      string             `json:"full_name"`
	Email         string             `json:"email"`
	RoleID        int64              `json:"role_id"`
	IsKaryawan    bool               `json:"is_karyawan"`
	AuthSource    string             `json:"auth_source"`
	EmployeeID    *string            `json:"employee_id"`
	VendorID      *int64             `json:"vendor_id"`
	IsActive      bool               `json:"is_active"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	SupervisorID  *int64             `json:"supervisor_id"`
	ApprovalLevel *int32             `json:"approval_level"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
}

// Single INSERT (Resolved Decision 5): for auth_source=local, password_hash
// and must_change_password=true are set in THIS insert — no follow-up
// SetInitialPassword call, so there is one write and one audit entry, and no
// window where the user row exists without its password. For auth_source=ldap,
// password_hash is NULL and must_change_password stays false (column default).
func (q *Queries) CreateUserAdmin(ctx context.Context, arg CreateUserAdminParams) (CreateUserAdminRow, error) {
	row := q.db.QueryRow(ctx, createUserAdmin,
		arg.RoleID,
		arg.EmployeeID,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.IsKaryawan,
		arg.AuthSource,
		arg.PasswordHash,
		arg.VendorID,
		arg.SupervisorID,
		arg.ApprovalLevel,
		arg.MustChangePassword,
	)
	var i CreateUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.RoleID,
		&i.IsKaryawan,
		&i.AuthSource,
		&i.EmployeeID,
		&i.VendorID,
		&i.IsActive,
		&i.DeletedAt,
		&i.SupervisorID,
		&i.ApprovalLevel,
		&i.LastLoginAt,
	)
	return i, err
}

const findUserAdminByEmail = `-- name: FindUserAdminByEmail :one
SELECT id FROM users WHERE email = $1
`

// Uniqueness pre-check (incl. soft-deleted) for create (Req 3.5).
func (q *Queries) FindUserAdminByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, findUserAdminByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserAdminByEmailExcludingID = `-- name: FindUserAdminByEmailExcludingID :one
SELECT id FROM users WHERE email = $1 AND id != $2
`

type FindUserAdminByEmailExcludingIDParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

// Uniqueness pre-check for update (Req 4.5): a collision with a DIFFERENT record.
func (q *Queries) FindUserAdminByEmailExcludingID(ctx context.Context, arg FindUserAdminByEmailExcludingIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, findUserAdminByEmailExcludingID, arg.Email, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserAdminByEmployeeID = `-- name: FindUserAdminByEmployeeID :one
SELECT id FROM users WHERE employee_id = $1
`

// Uniqueness pre-check (incl. soft-deleted) for create (Req 3.5). employee_id
// is nullable; callers only run this when employee_id is non-empty.
func (q *Queries) FindUserAdminByEmployeeID(ctx context.Context, employeeID *string) (int64, error) {
	row := q.db.QueryRow(ctx, findUserAdminByEmployeeID, employeeID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserAdminByEmployeeIDExcludingID = `-- name: FindUserAdminByEmployeeIDExcludingID :one
SELECT id FROM users WHERE employee_id = $1 AND id != $2
`

type FindUserAdminByEmployeeIDExcludingIDParams struct {
	EmployeeID *string `json:"employee_id"`
	ID         int64   `json:"id"`
}

// Uniqueness pre-check for update (Req 4.5): a collision with a DIFFERENT record.
func (q *Queries) FindUserAdminByEmployeeIDExcludingID(ctx context.Context, arg FindUserAdminByEmployeeIDExcludingIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, findUserAdminByEmployeeIDExcludingID, arg.EmployeeID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserAdminByUsername = `-- name: FindUserAdminByUsername :one
SELECT id FROM users WHERE username = $1
`

// Uniqueness pre-check (incl. soft-deleted) for create (Req 3.5). Named
// distinctly from auth.sql's FindUserByUsername (different projection, no
// deleted_at filter) to avoid a sqlc name collision.
func (q *Queries) FindUserAdminByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, findUserAdminByUsername, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, role FROM roles WHERE role = $1
`

type GetRoleByNameRow struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

// Resolves a role text (e.g. "APPACCESS") to its role_id for create/update
// (Req 3.6, 4.7). No role repository exists yet — this is its first query.
func (q *Queries) GetRoleByName(ctx context.Context, role string) (GetRoleByNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByName, role)
	var i GetRoleByNameRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const getUserAdminByID = `-- name: GetUserAdminByID :one
SELECT u.id, u.username, u.full_name, u.email, r.role, u.role_id, u.is_karyawan,
       u.auth_source, u.employee_id, u.vendor_id, u.is_active, u.deleted_at,
       u.supervisor_id, u.approval_level, u.last_login_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.id = $1
`

type GetUserAdminByIDRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	FullName      string             `json:"full_name"`
	Email         string             `json:"email"`
	Role          string             `json:"role"`
	RoleID        int64              `json:"role_id"`
	IsKaryawan    bool               `json:"is_karyawan"`
	AuthSource    string             `json:"auth_source"`
	EmployeeID    *string            `json:"employee_id"`
	VendorID      *int64             `json:"vendor_id"`
	IsActive      bool               `json:"is_active"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	SupervisorID  *int64             `json:"supervisor_id"`
	ApprovalLevel *int32             `json:"approval_level"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
}

// Unlike auth.sql's FindUserByID, this INCLUDES soft-deleted rows — the admin
// API needs to tell "not found" (404) apart from "disabled" (also 404 for
// edit per Req 4.4, but the disable/enable existence pre-check needs to see
// it). Never selects password_hash.
func (q *Queries) GetUserAdminByID(ctx context.Context, id int64) (GetUserAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAdminByID, id)
	var i GetUserAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.RoleID,
		&i.IsKaryawan,
		&i.AuthSource,
		&i.EmployeeID,
		&i.VendorID,
		&i.IsActive,
		&i.DeletedAt,
		&i.SupervisorID,
		&i.ApprovalLevel,
		&i.LastLoginAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, role FROM roles ORDER BY role
`

type ListRolesRow struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

// Populates the Role select in User_Form_Dialog (Req 11.2).
func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(&i.ID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many

SELECT u.id, u.username, u.full_name, u.email, r.role, u.is_karyawan,
       u.auth_source, u.vendor_id, u.is_active, u.deleted_at,
       u.supervisor_id, u.approval_level, u.last_login_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE ($1::text IS NULL
        OR u.username ILIKE '%' || $1::text || '%'
        OR u.full_name ILIKE '%' || $1::text || '%'
        OR u.email ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR r.role = $2::text)
  AND ($3::bigint IS NULL OR u.vendor_id = $3::bigint)
  AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND u.deleted_at IS NULL)
        OR ($4::text = 'disabled' AND u.deleted_at IS NOT NULL)
      )
ORDER BY u.full_name ASC, u.id ASC
LIMIT $6::bigint OFFSET $5::bigint
`

type ListUsersAdminParams struct {
	Q          *string `json:"q"`
	Role       *string `json:"role"`
	VendorID   *int64  `json:"vendor_id"`
	Status     string  `json:"status"`
	PageOffset int64   `json:"page_offset"`
	PageLimit  int64   `json:"page_limit"`
}

type ListUsersAdminRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	FullName      string             `json:"full_name"`
	Email         string             `json:"email"`
	Role          string             `json:"role"`
	IsKaryawan    bool               `json:"is_karyawan"`
	AuthSource    string             `json:"auth_source"`
	VendorID      *int64             `json:"vendor_id"`
	IsActive      bool               `json:"is_active"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	SupervisorID  *int64             `json:"supervisor_id"`
	ApprovalLevel *int32             `json:"approval_level"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
}

// Admin User & Vendor Management (Task 2): sqlc queries for the admin user
// CRUD endpoints (Req 2-5). Kept separate from auth.sql to avoid churn on the
// existing login/self-service auth queries.
// Admin user list (Req 2). Filters: q (case-insensitive substring across
// username/full_name/email), role (exact match on roles.role), vendor_id,
// and status — the caller resolves absent status to 'active' before calling
// (Resolved Decision 5), so this query only ever sees 'active' | 'disabled' | 'all'.
// Ordered full_name ASC, id ASC (Req 2.7 stable tiebreaker).
func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin,
		arg.Q,
		arg.Role,
		arg.VendorID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.Role,
			&i.IsKaryawan,
			&i.AuthSource,
			&i.VendorID,
			&i.IsActive,
			&i.DeletedAt,
			&i.SupervisorID,
			&i.ApprovalLevel,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE users
SET full_name = $1,
    email = $2,
    role_id = $3,
    is_karyawan = $4,
    employee_id = $5,
    vendor_id = $6,
    supervisor_id = $7,
    approval_level = $8,
    updated_at = now()
WHERE id = $9 AND deleted_at IS NULL
RETURNING id, username, full_name, email, role_id, is_karyawan, auth_source,
          employee_id, vendor_id, is_active, deleted_at, supervisor_id,
          approval_level, last_login_at
`

type UpdateUserAdminParams struct {
	FullName      string  `json:"full_name"`
	Email         string  `json:"email"`
	RoleID        int64   `json:"role_id"`
	IsKaryawan    bool    `json:"is_karyawan"`
	EmployeeID    *string `json:"employee_id"`
	VendorID      *int64  `json:"vendor_id"`
	SupervisorID  *int64  `json:"supervisor_id"`
	ApprovalLevel *int32  `json:"approval_level"`
	ID            int64   `json:"id"`
}

type UpdateUserAdminRow struct {
	ID            int64              `json:"id"`
	Username      string             `json:"username"`
	FullName      string             `json:"full_name"`
	Email         string             `json:"email"`
	RoleID        int64              `json:"role_id"`
	IsKaryawan    bool               `json:"is_karyawan"`
	AuthSource    string             `json:"auth_source"`
	EmployeeID    *string            `json:"employee_id"`
	VendorID      *int64             `json:"vendor_id"`
	IsActive      bool               `json:"is_active"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	SupervisorID  *int64             `json:"supervisor_id"`
	ApprovalLevel *int32             `json:"approval_level"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
}

// Editable fields only (Req 4.1); username/auth_source/password_hash are
// never touched here. `AND deleted_at IS NULL` makes a soft-disabled target
// update as 0 rows affected, which the repository maps to "not found" (Req 4.4).
func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (UpdateUserAdminRow, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin,
		arg.FullName,
		arg.Email,
		arg.RoleID,
		arg.IsKaryawan,
		arg.EmployeeID,
		arg.VendorID,
		arg.SupervisorID,
		arg.ApprovalLevel,
		arg.ID,
	)
	var i UpdateUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.RoleID,
		&i.IsKaryawan,
		&i.AuthSource,
		&i.EmployeeID,
		&i.VendorID,
		&i.IsActive,
		&i.DeletedAt,
		&i.SupervisorID,
		&i.ApprovalLevel,
		&i.LastLoginAt,
	)
	return i, err
}

const userAdminExists = `-- name: UserAdminExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1 AND deleted_at IS NULL) AS exists
`

// Reference check for supervisor_id on user create/update (Req 3.7, 4.7) —
// only an active (non-disabled) user is a valid supervisor.
func (q *Queries) UserAdminExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, userAdminExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const vendorExistsAdmin = `-- name: VendorExistsAdmin :one
SELECT EXISTS(SELECT 1 FROM vendors WHERE id = $1 AND deleted_at IS NULL) AS exists
`

// Reference check for vendor_id on user create/update (Req 3.7, 4.7) — only
// an active vendor is a valid reference, matching Vendor_Admin's own 404-on-
// disabled convention (Requirement 7.7).
func (q *Queries) VendorExistsAdmin(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, vendorExistsAdmin, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
