// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vault_plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelVaultPlansForRequest = `-- name: CancelVaultPlansForRequest :exec
UPDATE vendor_request_vault_plans SET status = 'cancelled'
WHERE vendor_request_id = $1 AND status <> 'cancelled'
`

// FR5.5: cancelling the request cancels every area plan.
func (q *Queries) CancelVaultPlansForRequest(ctx context.Context, vendorRequestID int64) error {
	_, err := q.db.Exec(ctx, cancelVaultPlansForRequest, vendorRequestID)
	return err
}

const clearVaultPlanAssignments = `-- name: ClearVaultPlanAssignments :exec
DELETE FROM vendor_request_vault_assignments WHERE vault_plan_id = $1
`

// Replace-all while the plan is draft (spec data model: draft rows are replaced, audited).
func (q *Queries) ClearVaultPlanAssignments(ctx context.Context, vaultPlanID int64) error {
	_, err := q.db.Exec(ctx, clearVaultPlanAssignments, vaultPlanID)
	return err
}

const countRequestAtmsWithoutApprovedVault = `-- name: CountRequestAtmsWithoutApprovedVault :one
SELECT COUNT(DISTINCT i.terminal_id)
FROM vendor_request_items i
WHERE i.vendor_request_id = $1
  AND NOT EXISTS (
        SELECT 1 FROM vendor_request_vault_assignments x
        JOIN vendor_request_vault_plans p ON p.id = x.vault_plan_id AND p.status = 'acm_approved'
        WHERE x.vendor_request_id = i.vendor_request_id AND x.terminal_id = i.terminal_id)
`

// FR4.6 gate: ATMs of the request not yet covered by an acm_approved plan
// (includes ATMs whose branch has no area -> no plan at all).
func (q *Queries) CountRequestAtmsWithoutApprovedVault(ctx context.Context, vendorRequestID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestAtmsWithoutApprovedVault, vendorRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMissingVaultPlans = `-- name: CreateMissingVaultPlans :many

INSERT INTO vendor_request_vault_plans (vendor_request_id, acm_area_id)
SELECT DISTINCT vr.id, ab.acm_area_id
FROM vendor_requests vr
JOIN vendor_request_tickets t ON t.request_number = vr.request_number AND t.is_active
JOIN atms a ON a.terminal_id = t.terminal_id
JOIN LATERAL (
    SELECT COALESCE(p.vendor_branch_id, avp.vendor_branch_id) AS vendor_branch_id
    FROM atm_vendor_packages avp
    LEFT JOIN vendor_packages_branch p ON p.id = avp.vendor_package_id
    WHERE avp.atm_id = a.id AND avp.is_active
      AND avp.effective_start_date <= t.replenish_date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= t.replenish_date)
    ORDER BY avp.effective_start_date DESC, avp.id DESC
    LIMIT 1
) k ON true
JOIN acm_area_branches ab ON ab.vendor_branch_id = k.vendor_branch_id
JOIN acm_areas ar ON ar.id = ab.acm_area_id AND ar.is_active
WHERE vr.status = 'vault_assignment'
  AND ($1::bigint IS NULL OR vr.id = $1::bigint)
ON CONFLICT (vendor_request_id, acm_area_id) DO NOTHING
RETURNING id, vendor_request_id, acm_area_id
`

type CreateMissingVaultPlansRow struct {
	ID              int64 `json:"id"`
	VendorRequestID int64 `json:"vendor_request_id"`
	AcmAreaID       int64 `json:"acm_area_id"`
}

// Penetapan vault per ATM oleh ACM (cit-acm-plan). One plan per
// (vendor_request, acm_area); an ATM belongs to the area of its replenish
// branch = the active kelolaan branch on the ticket's replenish_date.
// FR4.1 / FR7.3: insert a draft plan for every (request in vault_assignment,
// area) pair that has an ATM but no plan yet. request_id NULL = all such
// requests (after an ADMIN assigns branches). Returns only newly created rows.
func (q *Queries) CreateMissingVaultPlans(ctx context.Context, requestID *int64) ([]CreateMissingVaultPlansRow, error) {
	rows, err := q.db.Query(ctx, createMissingVaultPlans, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreateMissingVaultPlansRow{}
	for rows.Next() {
		var i CreateMissingVaultPlansRow
		if err := rows.Scan(&i.ID, &i.VendorRequestID, &i.AcmAreaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVaultAssignmentsOfRemovedAtms = `-- name: DeleteVaultAssignmentsOfRemovedAtms :many
DELETE FROM vendor_request_vault_assignments a
WHERE a.vendor_request_id = $1
  AND NOT EXISTS (SELECT 1 FROM vendor_request_items i WHERE i.vendor_request_id = a.vendor_request_id AND i.terminal_id = a.terminal_id)
RETURNING a.terminal_id
`

// cit-send-vendor FR6.2: an edit (draft only) removed ATMs from the request; their vault assignments go
// (draft rows, same rule as replace-all in 2.2a S1; caller audits). ATMs still in the request keep theirs.
func (q *Queries) DeleteVaultAssignmentsOfRemovedAtms(ctx context.Context, vendorRequestID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteVaultAssignmentsOfRemovedAtms, vendorRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var terminal_id string
		if err := rows.Scan(&terminal_id); err != nil {
			return nil, err
		}
		items = append(items, terminal_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultPlan = `-- name: GetVaultPlan :one

SELECT p.id, p.vendor_request_id, p.acm_area_id, p.status, p.submitted_by, p.submitted_at,
       p.approved_by, p.approved_at, p.rejected_by, p.rejected_at, p.rejection_reason,
       vr.request_number, vr.replenish_date, vr.vendor_id, vr.status AS request_status,
       vr.vault_rejection_reason, ar.name AS acm_area_name,
       -- cit-send-vendor FR4.3: the plan went back to draft because a vault vendor rejected it.
       EXISTS (SELECT 1 FROM users ru WHERE ru.id = p.rejected_by AND ru.vendor_id IS NOT NULL) AS rejected_by_vendor
FROM vendor_request_vault_plans p
JOIN vendor_requests vr ON vr.id = p.vendor_request_id
JOIN acm_areas ar ON ar.id = p.acm_area_id
WHERE p.id = $1
`

type GetVaultPlanRow struct {
	ID                   int64              `json:"id"`
	VendorRequestID      int64              `json:"vendor_request_id"`
	AcmAreaID            int64              `json:"acm_area_id"`
	Status               string             `json:"status"`
	SubmittedBy          *int64             `json:"submitted_by"`
	SubmittedAt          pgtype.Timestamptz `json:"submitted_at"`
	ApprovedBy           *int64             `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	RejectedBy           *int64             `json:"rejected_by"`
	RejectedAt           pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason      *string            `json:"rejection_reason"`
	RequestNumber        string             `json:"request_number"`
	ReplenishDate        pgtype.Date        `json:"replenish_date"`
	VendorID             *int64             `json:"vendor_id"`
	RequestStatus        string             `json:"request_status"`
	VaultRejectionReason *string            `json:"vault_rejection_reason"`
	AcmAreaName          string             `json:"acm_area_name"`
	RejectedByVendor     bool               `json:"rejected_by_vendor"`
}

// ---------------------------------------------------------------------------
// S6: rencana vault (read, saldo/kapasitas, penetapan, transisi)
// ---------------------------------------------------------------------------
// Plan header with the request and area it belongs to.
func (q *Queries) GetVaultPlan(ctx context.Context, id int64) (GetVaultPlanRow, error) {
	row := q.db.QueryRow(ctx, getVaultPlan, id)
	var i GetVaultPlanRow
	err := row.Scan(
		&i.ID,
		&i.VendorRequestID,
		&i.AcmAreaID,
		&i.Status,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.RequestNumber,
		&i.ReplenishDate,
		&i.VendorID,
		&i.RequestStatus,
		&i.VaultRejectionReason,
		&i.AcmAreaName,
		&i.RejectedByVendor,
	)
	return i, err
}

const insertVaultAssignment = `-- name: InsertVaultAssignment :one
INSERT INTO vendor_request_vault_assignments
    (vault_plan_id, vendor_request_id, terminal_id, replenish_branch_id, vault_branch_id, tier,
     is_urgent, urgent_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertVaultAssignmentParams struct {
	VaultPlanID       int64   `json:"vault_plan_id"`
	VendorRequestID   int64   `json:"vendor_request_id"`
	TerminalID        string  `json:"terminal_id"`
	ReplenishBranchID int64   `json:"replenish_branch_id"`
	VaultBranchID     int64   `json:"vault_branch_id"`
	Tier              int16   `json:"tier"`
	IsUrgent          bool    `json:"is_urgent"`
	UrgentReason      *string `json:"urgent_reason"`
}

func (q *Queries) InsertVaultAssignment(ctx context.Context, arg InsertVaultAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertVaultAssignment,
		arg.VaultPlanID,
		arg.VendorRequestID,
		arg.TerminalID,
		arg.ReplenishBranchID,
		arg.VaultBranchID,
		arg.Tier,
		arg.IsUrgent,
		arg.UrgentReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isAcmAreaMember = `-- name: IsAcmAreaMember :one
SELECT EXISTS (SELECT 1 FROM acm_area_members WHERE acm_area_id = $1 AND user_id = $2)
`

type IsAcmAreaMemberParams struct {
	AcmAreaID int64 `json:"acm_area_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) IsAcmAreaMember(ctx context.Context, arg IsAcmAreaMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isAcmAreaMember, arg.AcmAreaID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAcmAreaMemberIDsByRole = `-- name: ListAcmAreaMemberIDsByRole :many
SELECT DISTINCT m.user_id
FROM acm_area_members m
JOIN users u ON u.id = m.user_id AND u.is_active AND u.deleted_at IS NULL
JOIN roles r ON r.id = u.role_id
WHERE m.acm_area_id = ANY($1::bigint[]) AND r.role = $2::text
`

type ListAcmAreaMemberIDsByRoleParams struct {
	AreaIds []int64 `json:"area_ids"`
	Role    string  `json:"role"`
}

// Notification recipients: active members of the given areas holding role.
func (q *Queries) ListAcmAreaMemberIDsByRole(ctx context.Context, arg ListAcmAreaMemberIDsByRoleParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAcmAreaMemberIDsByRole, arg.AreaIds, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVaultPlansForRequest = `-- name: ListAllVaultPlansForRequest :many
SELECT id, acm_area_id, status FROM vendor_request_vault_plans WHERE vendor_request_id = $1 ORDER BY id
`

type ListAllVaultPlansForRequestRow struct {
	ID        int64  `json:"id"`
	AcmAreaID int64  `json:"acm_area_id"`
	Status    string `json:"status"`
}

// cit-send-vendor FR6.2: re-approval after an edit reopens every plan, including ones cancelled because
// an earlier edit left their area without ATMs (the unique (request, area) blocks recreating them).
func (q *Queries) ListAllVaultPlansForRequest(ctx context.Context, vendorRequestID int64) ([]ListAllVaultPlansForRequestRow, error) {
	rows, err := q.db.Query(ctx, listAllVaultPlansForRequest, vendorRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllVaultPlansForRequestRow{}
	for rows.Next() {
		var i ListAllVaultPlansForRequestRow
		if err := rows.Scan(&i.ID, &i.AcmAreaID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultAssignmentsForRequest = `-- name: ListVaultAssignmentsForRequest :many
SELECT x.vault_plan_id, x.terminal_id, x.replenish_branch_id, rb.branch_code AS replenish_branch_code,
       x.vault_branch_id, vb.branch_code AS vault_branch_code, vb.branch_name AS vault_branch_name,
       v.name AS vault_vendor_name, x.tier, x.is_urgent, x.urgent_reason,
       x.saldo_snapshot, x.capacity_snapshot, x.capacity_warning
FROM vendor_request_vault_assignments x
JOIN vendor_request_vault_plans p ON p.id = x.vault_plan_id AND p.status <> 'cancelled'
JOIN vendor_branches rb ON rb.id = x.replenish_branch_id
JOIN vendor_branches vb ON vb.id = x.vault_branch_id
JOIN vendors v ON v.id = vb.vendor_id
WHERE x.vendor_request_id = $1
ORDER BY x.terminal_id
`

type ListVaultAssignmentsForRequestRow struct {
	VaultPlanID         int64   `json:"vault_plan_id"`
	TerminalID          string  `json:"terminal_id"`
	ReplenishBranchID   int64   `json:"replenish_branch_id"`
	ReplenishBranchCode string  `json:"replenish_branch_code"`
	VaultBranchID       int64   `json:"vault_branch_id"`
	VaultBranchCode     string  `json:"vault_branch_code"`
	VaultBranchName     string  `json:"vault_branch_name"`
	VaultVendorName     string  `json:"vault_vendor_name"`
	Tier                int16   `json:"tier"`
	IsUrgent            bool    `json:"is_urgent"`
	UrgentReason        *string `json:"urgent_reason"`
	SaldoSnapshot       []byte  `json:"saldo_snapshot"`
	CapacitySnapshot    []byte  `json:"capacity_snapshot"`
	CapacityWarning     bool    `json:"capacity_warning"`
}

// ATM-SPV review panel (FR5.1): every assignment of the request's live plans.
func (q *Queries) ListVaultAssignmentsForRequest(ctx context.Context, vendorRequestID int64) ([]ListVaultAssignmentsForRequestRow, error) {
	rows, err := q.db.Query(ctx, listVaultAssignmentsForRequest, vendorRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultAssignmentsForRequestRow{}
	for rows.Next() {
		var i ListVaultAssignmentsForRequestRow
		if err := rows.Scan(
			&i.VaultPlanID,
			&i.TerminalID,
			&i.ReplenishBranchID,
			&i.ReplenishBranchCode,
			&i.VaultBranchID,
			&i.VaultBranchCode,
			&i.VaultBranchName,
			&i.VaultVendorName,
			&i.Tier,
			&i.IsUrgent,
			&i.UrgentReason,
			&i.SaldoSnapshot,
			&i.CapacitySnapshot,
			&i.CapacityWarning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultBranchSaldo = `-- name: ListVaultBranchSaldo :many
WITH saldo_rows AS (
    SELECT m.vendor_vault_id, r.denom_100k_idr, r.denom_50k_idr, r.denom_20k_idr, r.denom_10k_idr,
           r.denom_5k_idr, r.denom_2k_idr, r.denom_1k_idr
    FROM dsr_uploads u
    JOIN vendors vd ON vd.name = u.vendor
    JOIN dsr_daily_rows r ON r.upload_id = u.id AND r.flow = 'saldo_akhir' AND r.section = 'd0'
    JOIN dsr_location_vault_maps m ON m.vendor_id = vd.id AND m.is_active
         AND lower(m.dsr_location) = lower(btrim(r.location))
    WHERE u.report_date = $2::date AND u.daily_status = 'completed'
)
SELECT b.id AS vendor_branch_id,
       (COUNT(vv.id) = 0 OR COALESCE(bool_or(s.vendor_vault_id IS NULL
            OR s.denom_100k_idr IS NULL OR s.denom_50k_idr IS NULL OR s.denom_20k_idr IS NULL
            OR s.denom_10k_idr IS NULL OR s.denom_5k_idr IS NULL OR s.denom_2k_idr IS NULL
            OR s.denom_1k_idr IS NULL), false))::boolean AS unknown,
       COALESCE(TRUNC(SUM(s.denom_100k_idr)), 0)::bigint AS d100000,
       COALESCE(TRUNC(SUM(s.denom_50k_idr)), 0)::bigint AS d50000,
       COALESCE(TRUNC(SUM(s.denom_20k_idr)), 0)::bigint AS d20000,
       COALESCE(TRUNC(SUM(s.denom_10k_idr)), 0)::bigint AS d10000,
       COALESCE(TRUNC(SUM(s.denom_5k_idr)), 0)::bigint AS d5000,
       COALESCE(TRUNC(SUM(s.denom_2k_idr)), 0)::bigint AS d2000,
       COALESCE(TRUNC(SUM(s.denom_1k_idr)), 0)::bigint AS d1000
FROM vendor_branches b
LEFT JOIN vendor_vaults vv ON vv.vendor_branch_id = b.id AND vv.deleted_at IS NULL
LEFT JOIN saldo_rows s ON s.vendor_vault_id = vv.id
WHERE b.id = ANY($1::bigint[])
GROUP BY b.id
`

type ListVaultBranchSaldoParams struct {
	BranchIds  []int64     `json:"branch_ids"`
	ReportDate pgtype.Date `json:"report_date"`
}

type ListVaultBranchSaldoRow struct {
	VendorBranchID int64 `json:"vendor_branch_id"`
	Unknown        bool  `json:"unknown"`
	D100000        int64 `json:"d100000"`
	D50000         int64 `json:"d50000"`
	D20000         int64 `json:"d20000"`
	D10000         int64 `json:"d10000"`
	D5000          int64 `json:"d5000"`
	D2000          int64 `json:"d2000"`
	D1000          int64 `json:"d1000"`
}

// FR3.1: saldo akhir 00:00 per branch for DSR report_date = X, summed over the
// branch's active vaults via the DSR location map. unknown = no active vault,
// or a vault without a mapped saldo_akhir row, or a broken (NULL) denom cell.
// ponytail: amounts truncated to whole rupiah (DSR holds banknote totals, never cents).
func (q *Queries) ListVaultBranchSaldo(ctx context.Context, arg ListVaultBranchSaldoParams) ([]ListVaultBranchSaldoRow, error) {
	rows, err := q.db.Query(ctx, listVaultBranchSaldo, arg.BranchIds, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultBranchSaldoRow{}
	for rows.Next() {
		var i ListVaultBranchSaldoRow
		if err := rows.Scan(
			&i.VendorBranchID,
			&i.Unknown,
			&i.D100000,
			&i.D50000,
			&i.D20000,
			&i.D10000,
			&i.D5000,
			&i.D2000,
			&i.D1000,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultCandidateBranches = `-- name: ListVaultCandidateBranches :many
SELECT vb.id, vb.branch_code, vb.branch_name, vb.region_code::text AS region_code, vb.category,
       vb.vendor_id, v.name AS vendor_name
FROM vendor_branches vb
JOIN vendors v ON v.id = vb.vendor_id
WHERE vb.is_active AND vb.category IN ('CASH', 'ATM_CASH') AND vb.region_code IS NOT NULL
ORDER BY v.name, vb.branch_code
`

type ListVaultCandidateBranchesRow struct {
	ID         int64  `json:"id"`
	BranchCode string `json:"branch_code"`
	BranchName string `json:"branch_name"`
	RegionCode string `json:"region_code"`
	Category   string `json:"category"`
	VendorID   int64  `json:"vendor_id"`
	VendorName string `json:"vendor_name"`
}

// Every branch that can provide cash: active, CASH/ATM_CASH, with a region code.
func (q *Queries) ListVaultCandidateBranches(ctx context.Context) ([]ListVaultCandidateBranchesRow, error) {
	rows, err := q.db.Query(ctx, listVaultCandidateBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultCandidateBranchesRow{}
	for rows.Next() {
		var i ListVaultCandidateBranchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchCode,
			&i.BranchName,
			&i.RegionCode,
			&i.Category,
			&i.VendorID,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultDemand = `-- name: ListVaultDemand :many
SELECT vr.id AS vendor_request_id, i.terminal_id, i.denom, SUM(i.amount_replenish)::bigint AS amount,
       k.vendor_branch_id AS replenish_branch_id, asg.vault_branch_id
FROM vendor_requests vr
JOIN vendor_request_items i ON i.vendor_request_id = vr.id
JOIN atms a ON a.terminal_id = i.terminal_id
LEFT JOIN LATERAL (
    SELECT COALESCE(pk.vendor_branch_id, avp.vendor_branch_id) AS vendor_branch_id
    FROM atm_vendor_packages avp
    LEFT JOIN vendor_packages_branch pk ON pk.id = avp.vendor_package_id
    WHERE avp.atm_id = a.id AND avp.is_active
      AND avp.effective_start_date <= vr.replenish_date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= vr.replenish_date)
    ORDER BY avp.effective_start_date DESC, avp.id DESC
    LIMIT 1
) k ON true
LEFT JOIN vendor_request_vault_assignments asg ON asg.vendor_request_id = vr.id AND asg.terminal_id = i.terminal_id
     AND EXISTS (SELECT 1 FROM vendor_request_vault_plans pp WHERE pp.id = asg.vault_plan_id AND pp.status <> 'cancelled')
WHERE vr.replenish_date = $1::date
  AND vr.vault_flow AND NOT vr.is_canceled AND vr.status NOT IN ('cancelled', 'rejected')
GROUP BY vr.id, i.terminal_id, i.denom, k.vendor_branch_id, asg.vault_branch_id
`

type ListVaultDemandRow struct {
	VendorRequestID   int64  `json:"vendor_request_id"`
	TerminalID        string `json:"terminal_id"`
	Denom             int32  `json:"denom"`
	Amount            int64  `json:"amount"`
	ReplenishBranchID *int64 `json:"replenish_branch_id"`
	VaultBranchID     *int64 `json:"vault_branch_id"`
}

// FR3.2/3.3 input: every ATM order (per denom) of vault-flow requests for
// replenish date X that are still live, with its replenish branch and, if
// assigned in a non-cancelled plan, its vault branch.
func (q *Queries) ListVaultDemand(ctx context.Context, replenishDate pgtype.Date) ([]ListVaultDemandRow, error) {
	rows, err := q.db.Query(ctx, listVaultDemand, replenishDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultDemandRow{}
	for rows.Next() {
		var i ListVaultDemandRow
		if err := rows.Scan(
			&i.VendorRequestID,
			&i.TerminalID,
			&i.Denom,
			&i.Amount,
			&i.ReplenishBranchID,
			&i.VaultBranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultPlanAtms = `-- name: ListVaultPlanAtms :many
SELECT DISTINCT ON (i.terminal_id)
       i.terminal_id, vb.id AS replenish_branch_id, vb.branch_code AS replenish_branch_code,
       vb.branch_name AS replenish_branch_name, vb.region_code AS replenish_region_code,
       vb.vendor_id AS replenish_vendor_id, v.name AS replenish_vendor_name,
       asg.id AS assignment_id, asg.vault_branch_id, asg.tier, asg.is_urgent, asg.urgent_reason,
       asg.saldo_snapshot, asg.capacity_snapshot, asg.capacity_warning
FROM vendor_request_vault_plans p
JOIN vendor_requests vr ON vr.id = p.vendor_request_id
JOIN vendor_request_items i ON i.vendor_request_id = vr.id
JOIN atms a ON a.terminal_id = i.terminal_id
JOIN LATERAL (
    SELECT COALESCE(pk.vendor_branch_id, avp.vendor_branch_id) AS vendor_branch_id
    FROM atm_vendor_packages avp
    LEFT JOIN vendor_packages_branch pk ON pk.id = avp.vendor_package_id
    WHERE avp.atm_id = a.id AND avp.is_active
      AND avp.effective_start_date <= vr.replenish_date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= vr.replenish_date)
    ORDER BY avp.effective_start_date DESC, avp.id DESC
    LIMIT 1
) k ON true
JOIN vendor_branches vb ON vb.id = k.vendor_branch_id
JOIN vendors v ON v.id = vb.vendor_id
LEFT JOIN vendor_request_vault_assignments asg ON asg.vault_plan_id = p.id AND asg.terminal_id = i.terminal_id
WHERE p.id = $1
  AND (asg.id IS NOT NULL
       OR (EXISTS (SELECT 1 FROM acm_area_branches ab
                   WHERE ab.vendor_branch_id = k.vendor_branch_id AND ab.acm_area_id = p.acm_area_id)
           AND NOT EXISTS (SELECT 1 FROM vendor_request_vault_assignments o
                           JOIN vendor_request_vault_plans op ON op.id = o.vault_plan_id AND op.status <> 'cancelled'
                           WHERE o.vendor_request_id = vr.id AND o.terminal_id = i.terminal_id AND o.vault_plan_id <> p.id)))
ORDER BY i.terminal_id
`

type ListVaultPlanAtmsRow struct {
	TerminalID          string  `json:"terminal_id"`
	ReplenishBranchID   int64   `json:"replenish_branch_id"`
	ReplenishBranchCode string  `json:"replenish_branch_code"`
	ReplenishBranchName string  `json:"replenish_branch_name"`
	ReplenishRegionCode *string `json:"replenish_region_code"`
	ReplenishVendorID   int64   `json:"replenish_vendor_id"`
	ReplenishVendorName string  `json:"replenish_vendor_name"`
	AssignmentID        *int64  `json:"assignment_id"`
	VaultBranchID       *int64  `json:"vault_branch_id"`
	Tier                *int16  `json:"tier"`
	IsUrgent            *bool   `json:"is_urgent"`
	UrgentReason        *string `json:"urgent_reason"`
	SaldoSnapshot       []byte  `json:"saldo_snapshot"`
	CapacitySnapshot    []byte  `json:"capacity_snapshot"`
	CapacityWarning     *bool   `json:"capacity_warning"`
}

// ATMs of the plan, with their current assignment. An ATM with an assignment
// row stays in the plan holding that row even if ADMIN later moves its branch
// to another area (FR7.3: removing a branch does not change existing plans;
// review R1). An ATM without any row follows its replenish branch's current
// area (kelolaan on the replenish date), so a newly assigned branch is picked up.
func (q *Queries) ListVaultPlanAtms(ctx context.Context, id int64) ([]ListVaultPlanAtmsRow, error) {
	rows, err := q.db.Query(ctx, listVaultPlanAtms, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultPlanAtmsRow{}
	for rows.Next() {
		var i ListVaultPlanAtmsRow
		if err := rows.Scan(
			&i.TerminalID,
			&i.ReplenishBranchID,
			&i.ReplenishBranchCode,
			&i.ReplenishBranchName,
			&i.ReplenishRegionCode,
			&i.ReplenishVendorID,
			&i.ReplenishVendorName,
			&i.AssignmentID,
			&i.VaultBranchID,
			&i.Tier,
			&i.IsUrgent,
			&i.UrgentReason,
			&i.SaldoSnapshot,
			&i.CapacitySnapshot,
			&i.CapacityWarning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultPlans = `-- name: ListVaultPlans :many
SELECT p.id, p.vendor_request_id, p.acm_area_id, p.status, p.submitted_at, p.updated_at,
       vr.request_number, vr.replenish_date, vr.status AS request_status, ar.name AS acm_area_name,
       (SELECT COUNT(*) FROM vendor_request_vault_assignments x WHERE x.vault_plan_id = p.id) AS assigned_count,
       (SELECT COUNT(*) FROM vendor_request_vault_assignments x WHERE x.vault_plan_id = p.id AND x.capacity_warning) AS warning_count
FROM vendor_request_vault_plans p
JOIN vendor_requests vr ON vr.id = p.vendor_request_id
JOIN acm_areas ar ON ar.id = p.acm_area_id
WHERE ($1::bigint IS NULL
       OR EXISTS (SELECT 1 FROM acm_area_members m WHERE m.acm_area_id = p.acm_area_id AND m.user_id = $1::bigint))
  AND ($2::text = '' OR p.status = $2::text)
  AND ($3::bigint IS NULL OR p.acm_area_id = $3::bigint)
  AND ($4::date IS NULL OR vr.replenish_date >= $4::date)
  AND ($5::date IS NULL OR vr.replenish_date <= $5::date)
ORDER BY vr.replenish_date DESC NULLS LAST, p.id DESC
LIMIT 500
`

type ListVaultPlansParams struct {
	UserID   *int64      `json:"user_id"`
	Status   string      `json:"status"`
	AreaID   *int64      `json:"area_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type ListVaultPlansRow struct {
	ID              int64              `json:"id"`
	VendorRequestID int64              `json:"vendor_request_id"`
	AcmAreaID       int64              `json:"acm_area_id"`
	Status          string             `json:"status"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	RequestNumber   string             `json:"request_number"`
	ReplenishDate   pgtype.Date        `json:"replenish_date"`
	RequestStatus   string             `json:"request_status"`
	AcmAreaName     string             `json:"acm_area_name"`
	AssignedCount   int64              `json:"assigned_count"`
	WarningCount    int64              `json:"warning_count"`
}

// user_id NULL = every area (ADMIN read-only); else areas the user belongs to.
func (q *Queries) ListVaultPlans(ctx context.Context, arg ListVaultPlansParams) ([]ListVaultPlansRow, error) {
	rows, err := q.db.Query(ctx, listVaultPlans,
		arg.UserID,
		arg.Status,
		arg.AreaID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultPlansRow{}
	for rows.Next() {
		var i ListVaultPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorRequestID,
			&i.AcmAreaID,
			&i.Status,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.RequestNumber,
			&i.ReplenishDate,
			&i.RequestStatus,
			&i.AcmAreaName,
			&i.AssignedCount,
			&i.WarningCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaultPlansForRequest = `-- name: ListVaultPlansForRequest :many
SELECT p.id, p.acm_area_id, ar.name AS acm_area_name, p.status, p.submitted_by, p.approved_by,
       p.rejection_reason
FROM vendor_request_vault_plans p JOIN acm_areas ar ON ar.id = p.acm_area_id
WHERE p.vendor_request_id = $1 AND p.status <> 'cancelled'
ORDER BY ar.name
`

type ListVaultPlansForRequestRow struct {
	ID              int64   `json:"id"`
	AcmAreaID       int64   `json:"acm_area_id"`
	AcmAreaName     string  `json:"acm_area_name"`
	Status          string  `json:"status"`
	SubmittedBy     *int64  `json:"submitted_by"`
	ApprovedBy      *int64  `json:"approved_by"`
	RejectionReason *string `json:"rejection_reason"`
}

func (q *Queries) ListVaultPlansForRequest(ctx context.Context, vendorRequestID int64) ([]ListVaultPlansForRequestRow, error) {
	rows, err := q.db.Query(ctx, listVaultPlansForRequest, vendorRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVaultPlansForRequestRow{}
	for rows.Next() {
		var i ListVaultPlansForRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.AcmAreaID,
			&i.AcmAreaName,
			&i.Status,
			&i.SubmittedBy,
			&i.ApprovedBy,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVaultPlan = `-- name: LockVaultPlan :one
SELECT id, vendor_request_id, acm_area_id, status, submitted_by
FROM vendor_request_vault_plans WHERE id = $1 FOR UPDATE
`

type LockVaultPlanRow struct {
	ID              int64  `json:"id"`
	VendorRequestID int64  `json:"vendor_request_id"`
	AcmAreaID       int64  `json:"acm_area_id"`
	Status          string `json:"status"`
	SubmittedBy     *int64 `json:"submitted_by"`
}

func (q *Queries) LockVaultPlan(ctx context.Context, id int64) (LockVaultPlanRow, error) {
	row := q.db.QueryRow(ctx, lockVaultPlan, id)
	var i LockVaultPlanRow
	err := row.Scan(
		&i.ID,
		&i.VendorRequestID,
		&i.AcmAreaID,
		&i.Status,
		&i.SubmittedBy,
	)
	return i, err
}

const resetVaultPlansToDraft = `-- name: ResetVaultPlansToDraft :exec
UPDATE vendor_request_vault_plans
SET status = 'draft', approved_by = NULL, approved_at = NULL
WHERE vendor_request_id = $1 AND status <> 'cancelled'
`

// FR5.2: ATM-SPV rejects the recommendation -> every area plan back to draft.
func (q *Queries) ResetVaultPlansToDraft(ctx context.Context, vendorRequestID int64) error {
	_, err := q.db.Exec(ctx, resetVaultPlansToDraft, vendorRequestID)
	return err
}

const setVaultPlanStatus = `-- name: SetVaultPlanStatus :exec
UPDATE vendor_request_vault_plans
SET status = $1::text,
    submitted_by = CASE WHEN $1::text = 'pending_acm_approval' THEN $2::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $1::text = 'pending_acm_approval' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $1::text = 'acm_approved' THEN $2::bigint
                        WHEN $1::text = 'draft' THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $1::text = 'acm_approved' THEN now()
                        WHEN $1::text = 'draft' THEN NULL ELSE approved_at END,
    rejected_by  = CASE WHEN $3::text IS NOT NULL THEN $2::bigint ELSE rejected_by END,
    rejected_at  = CASE WHEN $3::text IS NOT NULL THEN now() ELSE rejected_at END,
    rejection_reason = CASE WHEN $3::text IS NOT NULL THEN $3::text ELSE rejection_reason END
WHERE id = $4::bigint
`

type SetVaultPlanStatusParams struct {
	Status  string  `json:"status"`
	ActorID *int64  `json:"actor_id"`
	Reason  *string `json:"reason"`
	ID      int64   `json:"id"`
}

// One query per plan transition; stamps only the columns of the target status.
func (q *Queries) SetVaultPlanStatus(ctx context.Context, arg SetVaultPlanStatusParams) error {
	_, err := q.db.Exec(ctx, setVaultPlanStatus,
		arg.Status,
		arg.ActorID,
		arg.Reason,
		arg.ID,
	)
	return err
}

const setVendorRequestStatusOnly = `-- name: SetVendorRequestStatusOnly :exec
UPDATE vendor_requests SET status = $1::text WHERE id = $2::bigint
`

type SetVendorRequestStatusOnlyParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

// System step vault_assignment -> vault_review (FR4.6); nothing else stamped.
func (q *Queries) SetVendorRequestStatusOnly(ctx context.Context, arg SetVendorRequestStatusOnlyParams) error {
	_, err := q.db.Exec(ctx, setVendorRequestStatusOnly, arg.Status, arg.ID)
	return err
}

const setVendorRequestVaultReview = `-- name: SetVendorRequestVaultReview :exec
UPDATE vendor_requests
SET status = $1::text,
    vault_reviewed_by = $2::bigint,
    vault_reviewed_at = now(),
    vault_rejection_reason = $3::text,
    vendor_sent = vendor_sent OR $1::text = 'sent_to_vendor',
    sent_at = CASE WHEN $1::text = 'sent_to_vendor' THEN now() ELSE sent_at END
WHERE id = $4::bigint
`

type SetVendorRequestVaultReviewParams struct {
	Status  string  `json:"status"`
	ActorID int64   `json:"actor_id"`
	Reason  *string `json:"reason"`
	ID      int64   `json:"id"`
}

// vault_review -> sent_to_vendor (cit-send-vendor S1; ready = legacy) | vault_assignment by the ATM-SPV (FR5.2).
func (q *Queries) SetVendorRequestVaultReview(ctx context.Context, arg SetVendorRequestVaultReviewParams) error {
	_, err := q.db.Exec(ctx, setVendorRequestVaultReview,
		arg.Status,
		arg.ActorID,
		arg.Reason,
		arg.ID,
	)
	return err
}

const updateVaultAssignmentSnapshot = `-- name: UpdateVaultAssignmentSnapshot :exec
UPDATE vendor_request_vault_assignments
SET saldo_snapshot = $2, capacity_snapshot = $3, capacity_warning = $4
WHERE id = $1
`

type UpdateVaultAssignmentSnapshotParams struct {
	ID               int64  `json:"id"`
	SaldoSnapshot    []byte `json:"saldo_snapshot"`
	CapacitySnapshot []byte `json:"capacity_snapshot"`
	CapacityWarning  bool   `json:"capacity_warning"`
}

func (q *Queries) UpdateVaultAssignmentSnapshot(ctx context.Context, arg UpdateVaultAssignmentSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateVaultAssignmentSnapshot,
		arg.ID,
		arg.SaldoSnapshot,
		arg.CapacitySnapshot,
		arg.CapacityWarning,
	)
	return err
}
