// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendor_branches_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVendorBranchesAdmin = `-- name: CountVendorBranchesAdmin :one
SELECT COUNT(*)
FROM vendor_branches
WHERE vendor_id = $1
  AND ($2::text IS NULL
        OR branch_code ILIKE '%' || $2::text || '%'
        OR branch_name ILIKE '%' || $2::text || '%')
  AND (
        $3::text = 'all'
        OR ($3::text = 'active' AND deleted_at IS NULL)
        OR ($3::text = 'disabled' AND deleted_at IS NOT NULL)
      )
`

type CountVendorBranchesAdminParams struct {
	VendorID int64   `json:"vendor_id"`
	Q        *string `json:"q"`
	Status   string  `json:"status"`
}

// Same filters as ListVendorBranchesAdmin, no LIMIT/OFFSET -- pagination total.
func (q *Queries) CountVendorBranchesAdmin(ctx context.Context, arg CountVendorBranchesAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorBranchesAdmin, arg.VendorID, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorBranchAdmin = `-- name: CreateVendorBranchAdmin :one
INSERT INTO vendor_branches (vendor_id, branch_code, branch_name, location_id, region)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, vendor_id, branch_code, branch_name, location_id, region, is_active, deleted_at
`

type CreateVendorBranchAdminParams struct {
	VendorID   int64   `json:"vendor_id"`
	BranchCode string  `json:"branch_code"`
	BranchName string  `json:"branch_name"`
	LocationID *int64  `json:"location_id"`
	Region     *string `json:"region"`
}

type CreateVendorBranchAdminRow struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	Region     *string            `json:"region"`
	IsActive   bool               `json:"is_active"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateVendorBranchAdmin(ctx context.Context, arg CreateVendorBranchAdminParams) (CreateVendorBranchAdminRow, error) {
	row := q.db.QueryRow(ctx, createVendorBranchAdmin,
		arg.VendorID,
		arg.BranchCode,
		arg.BranchName,
		arg.LocationID,
		arg.Region,
	)
	var i CreateVendorBranchAdminRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.BranchCode,
		&i.BranchName,
		&i.LocationID,
		&i.Region,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const disableVendorBranch = `-- name: DisableVendorBranch :exec
UPDATE vendor_branches SET is_active = false, deleted_at = now() WHERE id = $1
`

// Soft-disable only: is_active=false, deleted_at=now(). No hard DELETE
// anywhere in this codebase (no_hard_delete_test.go, extended for this
// table in T3.7).
func (q *Queries) DisableVendorBranch(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableVendorBranch, id)
	return err
}

const enableVendorBranch = `-- name: EnableVendorBranch :exec
UPDATE vendor_branches SET is_active = true, deleted_at = NULL WHERE id = $1
`

// Reverses DisableVendorBranch: is_active=true, deleted_at=NULL.
func (q *Queries) EnableVendorBranch(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableVendorBranch, id)
	return err
}

const findVendorBranchAdminByCode = `-- name: FindVendorBranchAdminByCode :one
SELECT id FROM vendor_branches WHERE branch_code = $1
`

// Uniqueness pre-check (incl. soft-deleted) -- branch_code is globally
// unique (uq_vendor_branches_branch_code), not just within a vendor.
func (q *Queries) FindVendorBranchAdminByCode(ctx context.Context, branchCode string) (int64, error) {
	row := q.db.QueryRow(ctx, findVendorBranchAdminByCode, branchCode)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getVendorBranchAdminByID = `-- name: GetVendorBranchAdminByID :one
SELECT id, vendor_id, branch_code, branch_name, location_id, region, is_active, deleted_at
FROM vendor_branches WHERE id = $1
`

type GetVendorBranchAdminByIDRow struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	Region     *string            `json:"region"`
	IsActive   bool               `json:"is_active"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

// Includes soft-deleted rows -- used both for the read endpoint and as the
// "before" snapshot / CurrentState staleness check (T2.5).
func (q *Queries) GetVendorBranchAdminByID(ctx context.Context, id int64) (GetVendorBranchAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getVendorBranchAdminByID, id)
	var i GetVendorBranchAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.BranchCode,
		&i.BranchName,
		&i.LocationID,
		&i.Region,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const listVendorBranchesAdmin = `-- name: ListVendorBranchesAdmin :many

SELECT id, vendor_id, branch_code, branch_name, location_id, region, is_active, deleted_at
FROM vendor_branches
WHERE vendor_id = $1
  AND ($2::text IS NULL
        OR branch_code ILIKE '%' || $2::text || '%'
        OR branch_name ILIKE '%' || $2::text || '%')
  AND (
        $3::text = 'all'
        OR ($3::text = 'active' AND deleted_at IS NULL)
        OR ($3::text = 'disabled' AND deleted_at IS NOT NULL)
      )
ORDER BY branch_name ASC, id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListVendorBranchesAdminParams struct {
	VendorID   int64   `json:"vendor_id"`
	Q          *string `json:"q"`
	Status     string  `json:"status"`
	PageOffset int64   `json:"page_offset"`
	PageLimit  int64   `json:"page_limit"`
}

type ListVendorBranchesAdminRow struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	Region     *string            `json:"region"`
	IsActive   bool               `json:"is_active"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

// Admin vendor branch management (plan.md Fase 3, T3.1). Mutations route
// through the master-data maker-checker engine (Fase 2, D1) -- these
// create/update/disable/enable queries are only ever run by
// VendorBranchApplier inside the apply-on-approve transaction, never
// directly by VendorBranchAdminService.
// Scoped to one vendor (Req: /api/v1/admin/vendors/{id}/branches). Filters:
// q (case-insensitive substring across branch_code/branch_name) and status
// ('active' | 'disabled' | 'all') -- caller resolves absent status to
// 'active' (mirrors ListVendorsAdmin's convention).
func (q *Queries) ListVendorBranchesAdmin(ctx context.Context, arg ListVendorBranchesAdminParams) ([]ListVendorBranchesAdminRow, error) {
	rows, err := q.db.Query(ctx, listVendorBranchesAdmin,
		arg.VendorID,
		arg.Q,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorBranchesAdminRow{}
	for rows.Next() {
		var i ListVendorBranchesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.BranchCode,
			&i.BranchName,
			&i.LocationID,
			&i.Region,
			&i.IsActive,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorBranchAdmin = `-- name: UpdateVendorBranchAdmin :one
UPDATE vendor_branches
SET branch_name = $1,
    location_id = $2,
    region = $3,
    updated_at = now()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, vendor_id, branch_code, branch_name, location_id, region, is_active, deleted_at
`

type UpdateVendorBranchAdminParams struct {
	BranchName string  `json:"branch_name"`
	LocationID *int64  `json:"location_id"`
	Region     *string `json:"region"`
	ID         int64   `json:"id"`
}

type UpdateVendorBranchAdminRow struct {
	ID         int64              `json:"id"`
	VendorID   int64              `json:"vendor_id"`
	BranchCode string             `json:"branch_code"`
	BranchName string             `json:"branch_name"`
	LocationID *int64             `json:"location_id"`
	Region     *string            `json:"region"`
	IsActive   bool               `json:"is_active"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

// branch_code is immutable (not editable here, mirrors vendors.code /
// atms.terminal_id convention). `AND deleted_at IS NULL` makes a
// soft-disabled target update as 0 rows affected, mapped to "not found" by
// the applier/service.
func (q *Queries) UpdateVendorBranchAdmin(ctx context.Context, arg UpdateVendorBranchAdminParams) (UpdateVendorBranchAdminRow, error) {
	row := q.db.QueryRow(ctx, updateVendorBranchAdmin,
		arg.BranchName,
		arg.LocationID,
		arg.Region,
		arg.ID,
	)
	var i UpdateVendorBranchAdminRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.BranchCode,
		&i.BranchName,
		&i.LocationID,
		&i.Region,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}
