// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendor_vaults_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveVendorVaultsByBranch = `-- name: CountActiveVendorVaultsByBranch :one
SELECT COUNT(*) FROM vendor_vaults WHERE vendor_branch_id = $1 AND deleted_at IS NULL
`

// Backs the branch-disable guard: refuse disabling a branch with active vaults.
func (q *Queries) CountActiveVendorVaultsByBranch(ctx context.Context, vendorBranchID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVendorVaultsByBranch, vendorBranchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendorVaultsAdmin = `-- name: CountVendorVaultsAdmin :one
SELECT COUNT(*)
FROM vendor_vaults v
JOIN vendor_branches b ON b.id = v.vendor_branch_id
WHERE b.vendor_id = $1
  AND ($2::bigint IS NULL OR v.vendor_branch_id = $2::bigint)
  AND ($3::text IS NULL OR v.vault_code ILIKE '%' || $3::text || '%')
  AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND v.deleted_at IS NULL)
        OR ($4::text = 'disabled' AND v.deleted_at IS NOT NULL)
      )
`

type CountVendorVaultsAdminParams struct {
	VendorID       int64   `json:"vendor_id"`
	VendorBranchID *int64  `json:"vendor_branch_id"`
	Q              *string `json:"q"`
	Status         string  `json:"status"`
}

func (q *Queries) CountVendorVaultsAdmin(ctx context.Context, arg CountVendorVaultsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorVaultsAdmin,
		arg.VendorID,
		arg.VendorBranchID,
		arg.Q,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorVaultAdmin = `-- name: CreateVendorVaultAdmin :one
INSERT INTO vendor_vaults (vendor_branch_id, vault_code, type, category, currency_code,
                           min_capacity_amount, max_capacity_amount, latitude, longitude,
                           operating_hours, location_id)
VALUES ($1, $2, $3, $3,
        $4, $5, $6,
        $7, $8, $9, $10)
RETURNING id, vendor_branch_id, vault_code, category, currency_code,
          min_capacity_amount, max_capacity_amount, latitude, longitude,
          operating_hours, location_id, is_active, deleted_at
`

type CreateVendorVaultAdminParams struct {
	VendorBranchID    int64          `json:"vendor_branch_id"`
	VaultCode         string         `json:"vault_code"`
	Category          string         `json:"category"`
	CurrencyCode      string         `json:"currency_code"`
	MinCapacityAmount pgtype.Numeric `json:"min_capacity_amount"`
	MaxCapacityAmount pgtype.Numeric `json:"max_capacity_amount"`
	Latitude          pgtype.Numeric `json:"latitude"`
	Longitude         pgtype.Numeric `json:"longitude"`
	OperatingHours    *string        `json:"operating_hours"`
	LocationID        *int64         `json:"location_id"`
}

type CreateVendorVaultAdminRow struct {
	ID                int64              `json:"id"`
	VendorBranchID    int64              `json:"vendor_branch_id"`
	VaultCode         string             `json:"vault_code"`
	Category          string             `json:"category"`
	CurrencyCode      string             `json:"currency_code"`
	MinCapacityAmount pgtype.Numeric     `json:"min_capacity_amount"`
	MaxCapacityAmount pgtype.Numeric     `json:"max_capacity_amount"`
	Latitude          pgtype.Numeric     `json:"latitude"`
	Longitude         pgtype.Numeric     `json:"longitude"`
	OperatingHours    *string            `json:"operating_hours"`
	LocationID        *int64             `json:"location_id"`
	IsActive          bool               `json:"is_active"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

// vendor_vaults.type is a legacy NOT NULL column (pre-category); new rows
// mirror category into it.
func (q *Queries) CreateVendorVaultAdmin(ctx context.Context, arg CreateVendorVaultAdminParams) (CreateVendorVaultAdminRow, error) {
	row := q.db.QueryRow(ctx, createVendorVaultAdmin,
		arg.VendorBranchID,
		arg.VaultCode,
		arg.Category,
		arg.CurrencyCode,
		arg.MinCapacityAmount,
		arg.MaxCapacityAmount,
		arg.Latitude,
		arg.Longitude,
		arg.OperatingHours,
		arg.LocationID,
	)
	var i CreateVendorVaultAdminRow
	err := row.Scan(
		&i.ID,
		&i.VendorBranchID,
		&i.VaultCode,
		&i.Category,
		&i.CurrencyCode,
		&i.MinCapacityAmount,
		&i.MaxCapacityAmount,
		&i.Latitude,
		&i.Longitude,
		&i.OperatingHours,
		&i.LocationID,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const disableVendorVault = `-- name: DisableVendorVault :exec
UPDATE vendor_vaults SET is_active = false, deleted_at = now() WHERE id = $1
`

// Soft-disable only (no_hard_delete_test.go extended in T3.7).
func (q *Queries) DisableVendorVault(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableVendorVault, id)
	return err
}

const enableVendorVault = `-- name: EnableVendorVault :exec
UPDATE vendor_vaults SET is_active = true, deleted_at = NULL WHERE id = $1
`

func (q *Queries) EnableVendorVault(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableVendorVault, id)
	return err
}

const findVendorVaultAdminByCode = `-- name: FindVendorVaultAdminByCode :one
SELECT id FROM vendor_vaults WHERE vault_code = $1
`

// Uniqueness pre-check (incl. soft-deleted): vault_code is globally unique.
func (q *Queries) FindVendorVaultAdminByCode(ctx context.Context, vaultCode string) (int64, error) {
	row := q.db.QueryRow(ctx, findVendorVaultAdminByCode, vaultCode)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getVendorBranchVendorID = `-- name: GetVendorBranchVendorID :one
SELECT vendor_id FROM vendor_branches WHERE id = $1
`

// Submit-time check that a vault's branch belongs to the vendor in the URL.
func (q *Queries) GetVendorBranchVendorID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getVendorBranchVendorID, id)
	var vendor_id int64
	err := row.Scan(&vendor_id)
	return vendor_id, err
}

const getVendorVaultAdminByID = `-- name: GetVendorVaultAdminByID :one
SELECT id, vendor_branch_id, vault_code, category, currency_code,
       min_capacity_amount, max_capacity_amount, latitude, longitude,
       operating_hours, location_id, is_active, deleted_at
FROM vendor_vaults WHERE id = $1
`

type GetVendorVaultAdminByIDRow struct {
	ID                int64              `json:"id"`
	VendorBranchID    int64              `json:"vendor_branch_id"`
	VaultCode         string             `json:"vault_code"`
	Category          string             `json:"category"`
	CurrencyCode      string             `json:"currency_code"`
	MinCapacityAmount pgtype.Numeric     `json:"min_capacity_amount"`
	MaxCapacityAmount pgtype.Numeric     `json:"max_capacity_amount"`
	Latitude          pgtype.Numeric     `json:"latitude"`
	Longitude         pgtype.Numeric     `json:"longitude"`
	OperatingHours    *string            `json:"operating_hours"`
	LocationID        *int64             `json:"location_id"`
	IsActive          bool               `json:"is_active"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

// Includes soft-deleted rows; doubles as the "before" snapshot / CurrentState (T2.5).
func (q *Queries) GetVendorVaultAdminByID(ctx context.Context, id int64) (GetVendorVaultAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getVendorVaultAdminByID, id)
	var i GetVendorVaultAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.VendorBranchID,
		&i.VaultCode,
		&i.Category,
		&i.CurrencyCode,
		&i.MinCapacityAmount,
		&i.MaxCapacityAmount,
		&i.Latitude,
		&i.Longitude,
		&i.OperatingHours,
		&i.LocationID,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const listVendorVaultsAdmin = `-- name: ListVendorVaultsAdmin :many

SELECT v.id, v.vendor_branch_id, v.vault_code, v.category, v.currency_code,
       v.min_capacity_amount, v.max_capacity_amount, v.latitude, v.longitude,
       v.operating_hours, v.location_id, v.is_active, v.deleted_at
FROM vendor_vaults v
JOIN vendor_branches b ON b.id = v.vendor_branch_id
WHERE b.vendor_id = $1
  AND ($2::bigint IS NULL OR v.vendor_branch_id = $2::bigint)
  AND ($3::text IS NULL OR v.vault_code ILIKE '%' || $3::text || '%')
  AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND v.deleted_at IS NULL)
        OR ($4::text = 'disabled' AND v.deleted_at IS NOT NULL)
      )
ORDER BY v.vault_code ASC, v.id ASC
LIMIT $6::bigint OFFSET $5::bigint
`

type ListVendorVaultsAdminParams struct {
	VendorID       int64   `json:"vendor_id"`
	VendorBranchID *int64  `json:"vendor_branch_id"`
	Q              *string `json:"q"`
	Status         string  `json:"status"`
	PageOffset     int64   `json:"page_offset"`
	PageLimit      int64   `json:"page_limit"`
}

type ListVendorVaultsAdminRow struct {
	ID                int64              `json:"id"`
	VendorBranchID    int64              `json:"vendor_branch_id"`
	VaultCode         string             `json:"vault_code"`
	Category          string             `json:"category"`
	CurrencyCode      string             `json:"currency_code"`
	MinCapacityAmount pgtype.Numeric     `json:"min_capacity_amount"`
	MaxCapacityAmount pgtype.Numeric     `json:"max_capacity_amount"`
	Latitude          pgtype.Numeric     `json:"latitude"`
	Longitude         pgtype.Numeric     `json:"longitude"`
	OperatingHours    *string            `json:"operating_hours"`
	LocationID        *int64             `json:"location_id"`
	IsActive          bool               `json:"is_active"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

// Admin vendor vault management (plan.md Fase 3, T3.2). Mutations route
// through the master-data maker-checker engine (Fase 2, D1): the
// create/update/disable/enable queries below are only run by
// VendorVaultApplier inside the apply-on-approve transaction.
// Scoped to one vendor via its branches. Filters: q (vault_code substring),
// status ('active'|'disabled'|'all', caller resolves absent to 'active'),
// vendor_branch_id (optional branch drill-down, NULL = all branches).
func (q *Queries) ListVendorVaultsAdmin(ctx context.Context, arg ListVendorVaultsAdminParams) ([]ListVendorVaultsAdminRow, error) {
	rows, err := q.db.Query(ctx, listVendorVaultsAdmin,
		arg.VendorID,
		arg.VendorBranchID,
		arg.Q,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorVaultsAdminRow{}
	for rows.Next() {
		var i ListVendorVaultsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorBranchID,
			&i.VaultCode,
			&i.Category,
			&i.CurrencyCode,
			&i.MinCapacityAmount,
			&i.MaxCapacityAmount,
			&i.Latitude,
			&i.Longitude,
			&i.OperatingHours,
			&i.LocationID,
			&i.IsActive,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorVaultAdmin = `-- name: UpdateVendorVaultAdmin :one
UPDATE vendor_vaults
SET category = $1,
    type = $1,
    currency_code = $2,
    min_capacity_amount = $3,
    max_capacity_amount = $4,
    latitude = $5,
    longitude = $6,
    operating_hours = $7,
    location_id = $8,
    updated_at = now()
WHERE id = $9 AND deleted_at IS NULL
RETURNING id, vendor_branch_id, vault_code, category, currency_code,
          min_capacity_amount, max_capacity_amount, latitude, longitude,
          operating_hours, location_id, is_active, deleted_at
`

type UpdateVendorVaultAdminParams struct {
	Category          string         `json:"category"`
	CurrencyCode      string         `json:"currency_code"`
	MinCapacityAmount pgtype.Numeric `json:"min_capacity_amount"`
	MaxCapacityAmount pgtype.Numeric `json:"max_capacity_amount"`
	Latitude          pgtype.Numeric `json:"latitude"`
	Longitude         pgtype.Numeric `json:"longitude"`
	OperatingHours    *string        `json:"operating_hours"`
	LocationID        *int64         `json:"location_id"`
	ID                int64          `json:"id"`
}

type UpdateVendorVaultAdminRow struct {
	ID                int64              `json:"id"`
	VendorBranchID    int64              `json:"vendor_branch_id"`
	VaultCode         string             `json:"vault_code"`
	Category          string             `json:"category"`
	CurrencyCode      string             `json:"currency_code"`
	MinCapacityAmount pgtype.Numeric     `json:"min_capacity_amount"`
	MaxCapacityAmount pgtype.Numeric     `json:"max_capacity_amount"`
	Latitude          pgtype.Numeric     `json:"latitude"`
	Longitude         pgtype.Numeric     `json:"longitude"`
	OperatingHours    *string            `json:"operating_hours"`
	LocationID        *int64             `json:"location_id"`
	IsActive          bool               `json:"is_active"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

// vault_code and vendor_branch_id are immutable. `AND deleted_at IS NULL`
// makes a soft-disabled target update 0 rows (mapped to not-found).
func (q *Queries) UpdateVendorVaultAdmin(ctx context.Context, arg UpdateVendorVaultAdminParams) (UpdateVendorVaultAdminRow, error) {
	row := q.db.QueryRow(ctx, updateVendorVaultAdmin,
		arg.Category,
		arg.CurrencyCode,
		arg.MinCapacityAmount,
		arg.MaxCapacityAmount,
		arg.Latitude,
		arg.Longitude,
		arg.OperatingHours,
		arg.LocationID,
		arg.ID,
	)
	var i UpdateVendorVaultAdminRow
	err := row.Scan(
		&i.ID,
		&i.VendorBranchID,
		&i.VaultCode,
		&i.Category,
		&i.CurrencyCode,
		&i.MinCapacityAmount,
		&i.MaxCapacityAmount,
		&i.Latitude,
		&i.Longitude,
		&i.OperatingHours,
		&i.LocationID,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}
