// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsersByVendor = `-- name: CountActiveUsersByVendor :one
SELECT COUNT(*) FROM users WHERE vendor_id = $1 AND deleted_at IS NULL
`

// Backs the Req 8.5 linked-active-users warning shown when a vendor with
// active (non-disabled) users is disabled — the disable still succeeds.
func (q *Queries) CountActiveUsersByVendor(ctx context.Context, vendorID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendorsAdmin = `-- name: CountVendorsAdmin :one
SELECT COUNT(*)
FROM vendors
WHERE ($1::text IS NULL
        OR code ILIKE '%' || $1::text || '%'
        OR name ILIKE '%' || $1::text || '%')
  AND (
        $2::text = 'all'
        OR ($2::text = 'active' AND deleted_at IS NULL)
        OR ($2::text = 'disabled' AND deleted_at IS NOT NULL)
      )
`

type CountVendorsAdminParams struct {
	Q      *string `json:"q"`
	Status string  `json:"status"`
}

// Same filters as ListVendorsAdmin, no LIMIT/OFFSET — pagination total (Req 6.6).
func (q *Queries) CountVendorsAdmin(ctx context.Context, arg CountVendorsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorsAdmin, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorAdmin = `-- name: CreateVendorAdmin :one
INSERT INTO vendors (code, name, contact_email, contact_phone, hq_address)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, code, name, contact_email, contact_phone, hq_address, is_active, deleted_at
`

type CreateVendorAdminParams struct {
	Code         string  `json:"code"`
	Name         string  `json:"name"`
	ContactEmail *string `json:"contact_email"`
	ContactPhone *string `json:"contact_phone"`
	HqAddress    *string `json:"hq_address"`
}

type CreateVendorAdminRow struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateVendorAdmin(ctx context.Context, arg CreateVendorAdminParams) (CreateVendorAdminRow, error) {
	row := q.db.QueryRow(ctx, createVendorAdmin,
		arg.Code,
		arg.Name,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.HqAddress,
	)
	var i CreateVendorAdminRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.HqAddress,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const disableVendor = `-- name: DisableVendor :exec
UPDATE vendors SET is_active = false, deleted_at = now() WHERE id = $1
`

// Soft-disable only (Req 8.1): is_active=false, deleted_at=now(). No hard
// DELETE on vendors anywhere in this codebase (Req 8.3, Task 6 guard).
func (q *Queries) DisableVendor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableVendor, id)
	return err
}

const enableVendor = `-- name: EnableVendor :exec
UPDATE vendors SET is_active = true, deleted_at = NULL WHERE id = $1
`

// Reverses DisableVendor (Req 8.2): is_active=true, deleted_at=NULL.
func (q *Queries) EnableVendor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enableVendor, id)
	return err
}

const findVendorAdminByCode = `-- name: FindVendorAdminByCode :one
SELECT id FROM vendors WHERE code = $1
`

// Uniqueness pre-check (incl. soft-deleted) for create (Req 7.3).
func (q *Queries) FindVendorAdminByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, findVendorAdminByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getVendorAdminByID = `-- name: GetVendorAdminByID :one
SELECT id, code, name, contact_email, contact_phone, hq_address, is_active, deleted_at
FROM vendors WHERE id = $1
`

type GetVendorAdminByIDRow struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// Includes soft-deleted rows — 404 pre-checks on update/disable/enable treat
// a soft-disabled vendor as not-found for edit (Req 7.7), consistent with
// GetUserAdminByID's convention.
func (q *Queries) GetVendorAdminByID(ctx context.Context, id int64) (GetVendorAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getVendorAdminByID, id)
	var i GetVendorAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.HqAddress,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}

const listVendorsAdmin = `-- name: ListVendorsAdmin :many

SELECT id, code, name, contact_email, contact_phone, hq_address, is_active, deleted_at
FROM vendors
WHERE ($1::text IS NULL
        OR code ILIKE '%' || $1::text || '%'
        OR name ILIKE '%' || $1::text || '%')
  AND (
        $2::text = 'all'
        OR ($2::text = 'active' AND deleted_at IS NULL)
        OR ($2::text = 'disabled' AND deleted_at IS NOT NULL)
      )
ORDER BY name ASC, id ASC
LIMIT $4::bigint OFFSET $3::bigint
`

type ListVendorsAdminParams struct {
	Q          *string `json:"q"`
	Status     string  `json:"status"`
	PageOffset int64   `json:"page_offset"`
	PageLimit  int64   `json:"page_limit"`
}

type ListVendorsAdminRow struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// Admin User & Vendor Management (Task 2): sqlc queries for the admin vendor
// CRUD endpoints (Req 6-8). Vendors have no admin queries anywhere yet.
// Admin vendor list (Req 6). Filters: q (case-insensitive substring across
// code/name) and status — the caller resolves absent status to 'active'
// before calling (Resolved Decision 5), so this query only ever sees
// 'active' | 'disabled' | 'all'. Ordered name ASC, id ASC (Req 6.5).
func (q *Queries) ListVendorsAdmin(ctx context.Context, arg ListVendorsAdminParams) ([]ListVendorsAdminRow, error) {
	rows, err := q.db.Query(ctx, listVendorsAdmin,
		arg.Q,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorsAdminRow{}
	for rows.Next() {
		var i ListVendorsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.HqAddress,
			&i.IsActive,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorAdmin = `-- name: UpdateVendorAdmin :one
UPDATE vendors
SET name = $1,
    contact_email = $2,
    contact_phone = $3,
    hq_address = $4,
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, code, name, contact_email, contact_phone, hq_address, is_active, deleted_at
`

type UpdateVendorAdminParams struct {
	Name         string  `json:"name"`
	ContactEmail *string `json:"contact_email"`
	ContactPhone *string `json:"contact_phone"`
	HqAddress    *string `json:"hq_address"`
	ID           int64   `json:"id"`
}

type UpdateVendorAdminRow struct {
	ID           int64              `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	ContactEmail *string            `json:"contact_email"`
	ContactPhone *string            `json:"contact_phone"`
	HqAddress    *string            `json:"hq_address"`
	IsActive     bool               `json:"is_active"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

// Editable fields only (Req 7.5); code is never touched here (immutable,
// Req 7.6). `AND deleted_at IS NULL` makes a soft-disabled target update as 0
// rows affected, mapped to "not found" by the repository (Req 7.7).
func (q *Queries) UpdateVendorAdmin(ctx context.Context, arg UpdateVendorAdminParams) (UpdateVendorAdminRow, error) {
	row := q.db.QueryRow(ctx, updateVendorAdmin,
		arg.Name,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.HqAddress,
		arg.ID,
	)
	var i UpdateVendorAdminRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.HqAddress,
		&i.IsActive,
		&i.DeletedAt,
	)
	return i, err
}
