// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendor_packages_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveVendorPackagesByBranch = `-- name: CountActiveVendorPackagesByBranch :one
SELECT COUNT(*) FROM vendor_packages_branch
WHERE vendor_branch_id = $1 AND (effective_end_date IS NULL OR effective_end_date >= CURRENT_DATE)
`

// Backs the branch-disable guard: refuse disabling a branch with a current
// or open-ended special price row.
func (q *Queries) CountActiveVendorPackagesByBranch(ctx context.Context, vendorBranchID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVendorPackagesByBranch, vendorBranchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendorPackagesAdmin = `-- name: CountVendorPackagesAdmin :one
SELECT COUNT(*)
FROM vendor_packages_branch p
JOIN vendor_branches b ON b.id = p.vendor_branch_id
WHERE b.vendor_id = $1
  AND ($2::bigint IS NULL OR p.vendor_branch_id = $2::bigint)
  AND ($3::text IS NULL OR p.package_code ILIKE '%' || $3::text || '%')
  AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND (p.effective_end_date IS NULL OR p.effective_end_date >= CURRENT_DATE))
        OR ($4::text = 'disabled' AND p.effective_end_date < CURRENT_DATE)
      )
`

type CountVendorPackagesAdminParams struct {
	VendorID       int64   `json:"vendor_id"`
	VendorBranchID *int64  `json:"vendor_branch_id"`
	Q              *string `json:"q"`
	Status         string  `json:"status"`
}

func (q *Queries) CountVendorPackagesAdmin(ctx context.Context, arg CountVendorPackagesAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorPackagesAdmin,
		arg.VendorID,
		arg.VendorBranchID,
		arg.Q,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorPackageAdmin = `-- name: CreateVendorPackageAdmin :one
INSERT INTO vendor_packages_branch
    (vendor_branch_id, package_code, machine_group, price_class, tier_min, tier_max,
     base_price, atm_id, sla_note, currency, effective_start_date, effective_end_date)
VALUES ($1, $2, $3, $4,
        $5, $6,
        $7, $8, $9, $10,
        $11, $12)
RETURNING id, vendor_branch_id, package_code, machine_group, price_class, tier_min, tier_max,
          base_price, atm_id, sla_note, currency, effective_start_date, effective_end_date
`

type CreateVendorPackageAdminParams struct {
	VendorBranchID     *int64         `json:"vendor_branch_id"`
	PackageCode        string         `json:"package_code"`
	MachineGroup       string         `json:"machine_group"`
	PriceClass         string         `json:"price_class"`
	TierMin            int32          `json:"tier_min"`
	TierMax            *int32         `json:"tier_max"`
	BasePrice          pgtype.Numeric `json:"base_price"`
	AtmID              *int64         `json:"atm_id"`
	SlaNote            *string        `json:"sla_note"`
	Currency           string         `json:"currency"`
	EffectiveStartDate pgtype.Date    `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date    `json:"effective_end_date"`
}

type CreateVendorPackageAdminRow struct {
	ID                 int64          `json:"id"`
	VendorBranchID     *int64         `json:"vendor_branch_id"`
	PackageCode        string         `json:"package_code"`
	MachineGroup       string         `json:"machine_group"`
	PriceClass         string         `json:"price_class"`
	TierMin            int32          `json:"tier_min"`
	TierMax            *int32         `json:"tier_max"`
	BasePrice          pgtype.Numeric `json:"base_price"`
	AtmID              *int64         `json:"atm_id"`
	SlaNote            *string        `json:"sla_note"`
	Currency           string         `json:"currency"`
	EffectiveStartDate pgtype.Date    `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date    `json:"effective_end_date"`
}

// Grain (vendor_branch_id, package_code, machine_group, price_class, tier,
// atm_id, currency, effective_start_date) is immutable after create -- a
// grain change is a new price period, same convention as
// CreateVendorPackagePriceAdmin.
func (q *Queries) CreateVendorPackageAdmin(ctx context.Context, arg CreateVendorPackageAdminParams) (CreateVendorPackageAdminRow, error) {
	row := q.db.QueryRow(ctx, createVendorPackageAdmin,
		arg.VendorBranchID,
		arg.PackageCode,
		arg.MachineGroup,
		arg.PriceClass,
		arg.TierMin,
		arg.TierMax,
		arg.BasePrice,
		arg.AtmID,
		arg.SlaNote,
		arg.Currency,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
	)
	var i CreateVendorPackageAdminRow
	err := row.Scan(
		&i.ID,
		&i.VendorBranchID,
		&i.PackageCode,
		&i.MachineGroup,
		&i.PriceClass,
		&i.TierMin,
		&i.TierMax,
		&i.BasePrice,
		&i.AtmID,
		&i.SlaNote,
		&i.Currency,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
	)
	return i, err
}

const disableVendorPackage = `-- name: DisableVendorPackage :exec
UPDATE vendor_packages_branch
SET effective_end_date = CURRENT_DATE - 1, updated_at = now()
WHERE id = $1
  AND (effective_end_date IS NULL OR effective_end_date >= CURRENT_DATE)
`

// Ends the price period as of yesterday. No-op on an already-ended row.
func (q *Queries) DisableVendorPackage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableVendorPackage, id)
	return err
}

const getVendorPackageAdminByID = `-- name: GetVendorPackageAdminByID :one
SELECT p.id, p.vendor_branch_id, b.vendor_id, p.package_code, p.machine_group, p.price_class,
       p.tier_min, p.tier_max, p.base_price, p.atm_id, p.sla_note, p.currency,
       p.effective_start_date, p.effective_end_date
FROM vendor_packages_branch p
JOIN vendor_branches b ON b.id = p.vendor_branch_id
WHERE p.id = $1
`

type GetVendorPackageAdminByIDRow struct {
	ID                 int64          `json:"id"`
	VendorBranchID     *int64         `json:"vendor_branch_id"`
	VendorID           int64          `json:"vendor_id"`
	PackageCode        string         `json:"package_code"`
	MachineGroup       string         `json:"machine_group"`
	PriceClass         string         `json:"price_class"`
	TierMin            int32          `json:"tier_min"`
	TierMax            *int32         `json:"tier_max"`
	BasePrice          pgtype.Numeric `json:"base_price"`
	AtmID              *int64         `json:"atm_id"`
	SlaNote            *string        `json:"sla_note"`
	Currency           string         `json:"currency"`
	EffectiveStartDate pgtype.Date    `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date    `json:"effective_end_date"`
}

// Includes expired rows and the owning vendor_id (for URL scoping); doubles
// as the "before" snapshot / CurrentState.
func (q *Queries) GetVendorPackageAdminByID(ctx context.Context, id int64) (GetVendorPackageAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getVendorPackageAdminByID, id)
	var i GetVendorPackageAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.VendorBranchID,
		&i.VendorID,
		&i.PackageCode,
		&i.MachineGroup,
		&i.PriceClass,
		&i.TierMin,
		&i.TierMax,
		&i.BasePrice,
		&i.AtmID,
		&i.SlaNote,
		&i.Currency,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
	)
	return i, err
}

const listVendorPackagesAdmin = `-- name: ListVendorPackagesAdmin :many

SELECT p.id, p.vendor_branch_id, p.package_code, p.machine_group, p.price_class,
       p.tier_min, p.tier_max, p.base_price, p.atm_id, p.sla_note, p.currency,
       p.effective_start_date, p.effective_end_date
FROM vendor_packages_branch p
JOIN vendor_branches b ON b.id = p.vendor_branch_id
WHERE b.vendor_id = $1
  AND ($2::bigint IS NULL OR p.vendor_branch_id = $2::bigint)
  AND ($3::text IS NULL OR p.package_code ILIKE '%' || $3::text || '%')
  AND (
        $4::text = 'all'
        OR ($4::text = 'active' AND (p.effective_end_date IS NULL OR p.effective_end_date >= CURRENT_DATE))
        OR ($4::text = 'disabled' AND p.effective_end_date < CURRENT_DATE)
      )
ORDER BY p.package_code ASC, p.id ASC
LIMIT $6::bigint OFFSET $5::bigint
`

type ListVendorPackagesAdminParams struct {
	VendorID       int64   `json:"vendor_id"`
	VendorBranchID *int64  `json:"vendor_branch_id"`
	Q              *string `json:"q"`
	Status         string  `json:"status"`
	PageOffset     int64   `json:"page_offset"`
	PageLimit      int64   `json:"page_limit"`
}

type ListVendorPackagesAdminRow struct {
	ID                 int64          `json:"id"`
	VendorBranchID     *int64         `json:"vendor_branch_id"`
	PackageCode        string         `json:"package_code"`
	MachineGroup       string         `json:"machine_group"`
	PriceClass         string         `json:"price_class"`
	TierMin            int32          `json:"tier_min"`
	TierMax            *int32         `json:"tier_max"`
	BasePrice          pgtype.Numeric `json:"base_price"`
	AtmID              *int64         `json:"atm_id"`
	SlaNote            *string        `json:"sla_note"`
	Currency           string         `json:"currency"`
	EffectiveStartDate pgtype.Date    `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date    `json:"effective_end_date"`
}

// Admin vendor branch package price ("harga khusus cabang") management
// (migration 016). Mutations route through the master-data maker-checker
// engine (Fase 2, D1): the create/update/disable queries below are only run
// by VendorPackageApplier inside the apply-on-approve transaction. No Enable
// (effective-dated history, not a togglable entity) -- same convention as
// vendor_package_prices_admin.sql; "disable" ends validity via
// effective_end_date, a new period is a new row.
// Scoped to one vendor via its branches. Filters: q (package_code
// substring), status ('active'|'disabled'|'all', caller resolves absent to
// 'active'), vendor_branch_id (optional branch drill-down, NULL = all
// branches). status 'active' = current or open-ended (effective_end_date
// IS NULL OR >= today), 'disabled' = effective_end_date in the past.
func (q *Queries) ListVendorPackagesAdmin(ctx context.Context, arg ListVendorPackagesAdminParams) ([]ListVendorPackagesAdminRow, error) {
	rows, err := q.db.Query(ctx, listVendorPackagesAdmin,
		arg.VendorID,
		arg.VendorBranchID,
		arg.Q,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorPackagesAdminRow{}
	for rows.Next() {
		var i ListVendorPackagesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorBranchID,
			&i.PackageCode,
			&i.MachineGroup,
			&i.PriceClass,
			&i.TierMin,
			&i.TierMax,
			&i.BasePrice,
			&i.AtmID,
			&i.SlaNote,
			&i.Currency,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorPackageAdmin = `-- name: UpdateVendorPackageAdmin :one
UPDATE vendor_packages_branch
SET base_price = $1, sla_note = $2,
    effective_end_date = $3, updated_at = now()
WHERE id = $4
  AND (effective_end_date IS NULL OR effective_end_date >= CURRENT_DATE)
RETURNING id, vendor_branch_id, package_code, machine_group, price_class, tier_min, tier_max,
          base_price, atm_id, sla_note, currency, effective_start_date, effective_end_date
`

type UpdateVendorPackageAdminParams struct {
	BasePrice        pgtype.Numeric `json:"base_price"`
	SlaNote          *string        `json:"sla_note"`
	EffectiveEndDate pgtype.Date    `json:"effective_end_date"`
	ID               int64          `json:"id"`
}

type UpdateVendorPackageAdminRow struct {
	ID                 int64          `json:"id"`
	VendorBranchID     *int64         `json:"vendor_branch_id"`
	PackageCode        string         `json:"package_code"`
	MachineGroup       string         `json:"machine_group"`
	PriceClass         string         `json:"price_class"`
	TierMin            int32          `json:"tier_min"`
	TierMax            *int32         `json:"tier_max"`
	BasePrice          pgtype.Numeric `json:"base_price"`
	AtmID              *int64         `json:"atm_id"`
	SlaNote            *string        `json:"sla_note"`
	Currency           string         `json:"currency"`
	EffectiveStartDate pgtype.Date    `json:"effective_start_date"`
	EffectiveEndDate   pgtype.Date    `json:"effective_end_date"`
}

// Only the content fields (base_price, sla_note, effective_end_date) are
// editable; grain fields stay immutable, same convention as
// UpdateVendorPackagePriceAdmin. An already-ended row's update is 0 rows
// (mapped to not-found).
func (q *Queries) UpdateVendorPackageAdmin(ctx context.Context, arg UpdateVendorPackageAdminParams) (UpdateVendorPackageAdminRow, error) {
	row := q.db.QueryRow(ctx, updateVendorPackageAdmin,
		arg.BasePrice,
		arg.SlaNote,
		arg.EffectiveEndDate,
		arg.ID,
	)
	var i UpdateVendorPackageAdminRow
	err := row.Scan(
		&i.ID,
		&i.VendorBranchID,
		&i.PackageCode,
		&i.MachineGroup,
		&i.PriceClass,
		&i.TierMin,
		&i.TierMax,
		&i.BasePrice,
		&i.AtmID,
		&i.SlaNote,
		&i.Currency,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
	)
	return i, err
}
