-- Vendor Request (DMAA forecast -> CIT vendor replenishment order) queries.
-- Backs backend/internal/service/vendor_request.go (task 3). See
-- .kiro/specs/request-replenish-to-vendor/design.md for the state machine,
-- API contract, and correctness properties these queries support.

-- name: CreateVendorRequest :one
-- Inserts the header row in draft status. request_number is generated by the
-- service (REP-<prefix>-<YYYYMMDD>-<seq>, see NextRequestNumberSeq below)
-- before this call, inside the same transaction, so a unique-constraint
-- violation here means a concurrent insert raced the number and the service
-- retries. replenish_date/vendor_id are always set by new callers (Req 2, 4);
-- request_category is set by every new caller (replenishment-request-
-- enhancements Req 1.9, manual or Forecast-Browser alike); sqlc.narg keeps
-- legacy NULL rows representable -- see
-- .kiro/specs/cit-vendor-request-enhancements/design.md.
INSERT INTO vendor_requests
    (request_number, forecast_date, replenish_date, request_category, is_manual, vendor_id, status, notes, created_by)
VALUES (
    sqlc.arg('request_number')::text,
    sqlc.arg('forecast_date')::date,
    sqlc.arg('replenish_date')::date,
    sqlc.narg('request_category')::text,
    sqlc.arg('is_manual')::boolean,
    sqlc.arg('vendor_id')::bigint,
    'draft',
    sqlc.narg('notes')::text,
    sqlc.arg('created_by')::bigint
)
RETURNING *;

-- name: InsertVendorRequestItem :one
-- amount_refund is not part of the client payload (Req 4.1) -- it is copied
-- from the matching dmaa_atm_forecast row (see ForecastRowsExist below) so
-- the item stays informationally consistent with the forecast it was drawn
-- from, even though amount_replenish itself may be a manual override.
-- brand/lokasi_atm (sqlc.narg) are set only for Manual_Request items (Req 3,
-- Q4) that have no dmaa_atm_forecast row to re-derive them from at read time;
-- DMAA-backed items leave them NULL.
INSERT INTO vendor_request_items
    (vendor_request_id, terminal_id, periode_pred, denom, amount_replenish, amount_refund, brand, lokasi_atm)
VALUES ($1, $2, $3, $4, $5, $6, sqlc.narg('brand')::text, sqlc.narg('lokasi_atm')::text)
RETURNING *;

-- name: DeleteVendorRequestItems :exec
-- Used by UpdateItems' full-replacement strategy (Req 8.2): delete all
-- existing items, then InsertVendorRequestItem the new set, in one tx.
DELETE FROM vendor_request_items WHERE vendor_request_id = $1;

-- name: GetVendorRequest :one
-- Plain read, no joins -- used where only the request's own columns are
-- needed (e.g. existence checks). See GetVendorRequestDetail for the
-- response-shaped read with creator/approver/rejecter names.
SELECT * FROM vendor_requests WHERE id = $1;

-- name: GetVendorRequestForUpdate :one
-- Row-locking read for every state transition (submit/approve/reject/revise/
-- cancel): SELECT ... FOR UPDATE serializes concurrent actions on the same
-- request so a second concurrent actor blocks until the first tx commits,
-- then sees the already-changed status and gets ErrInvalidTransition (409)
-- instead of racing past the guard.
SELECT * FROM vendor_requests WHERE id = $1 FOR UPDATE;

-- name: UpdateVendorRequestStatus :one
-- One query for every transition: sets status plus only the timestamp/actor
-- columns relevant to the target status (Req 2.9-2.11), leaving the others
-- untouched. actor_id / rejection_reason are nullable (sqlc.narg) because
-- most transitions (submit, revise, cancel) don't supply them -- the CASE
-- guards mean an unused NULL is simply never written.
UPDATE vendor_requests
SET
    status = sqlc.arg('status')::text,
    submitted_at = CASE WHEN sqlc.arg('status')::text = 'pending_approval' THEN now() ELSE submitted_at END,
    approved_at = CASE WHEN sqlc.arg('status')::text = 'approved' THEN now() ELSE approved_at END,
    approved_by = CASE WHEN sqlc.arg('status')::text = 'approved' THEN sqlc.narg('actor_id')::bigint ELSE approved_by END,
    rejected_at = CASE WHEN sqlc.arg('status')::text = 'rejected' THEN now() ELSE rejected_at END,
    rejected_by = CASE WHEN sqlc.arg('status')::text = 'rejected' THEN sqlc.narg('actor_id')::bigint ELSE rejected_by END,
    rejection_reason = CASE WHEN sqlc.arg('status')::text = 'rejected' THEN sqlc.narg('rejection_reason')::text ELSE rejection_reason END
WHERE id = sqlc.arg('id')::bigint
RETURNING *;

-- name: ListVendorRequestItems :many
SELECT * FROM vendor_request_items WHERE vendor_request_id = $1 ORDER BY id ASC;

-- name: GetVendorRequestDetail :one
-- Detail response shape (Req 9.6): header plus created_by/approved_by/
-- rejected_by full_name. created_by is always present (NOT NULL FK);
-- approved_by/rejected_by are only set once the request reaches that state,
-- hence LEFT JOIN.
SELECT
    vr.*,
    cu.full_name AS created_by_name,
    au.full_name AS approved_by_name,
    ru.full_name AS rejected_by_name
FROM vendor_requests vr
JOIN users cu ON cu.id = vr.created_by
LEFT JOIN users au ON au.id = vr.approved_by
LEFT JOIN users ru ON ru.id = vr.rejected_by
WHERE vr.id = sqlc.arg('id')::bigint;

-- name: ListVendorRequests :many
-- Paginated, filtered list (Req 9.1-9.5). Empty-string / 0 filter args mean
-- "no filter applied" (same convention as dmaa_forecast.sql / atm_portal.sql
-- -- callers always pass concrete sentinel values, never NULL). status is
-- comma-separated multi-select, matching ListATMsWithCashPos's pattern.
-- item_count/total_amount come from a per-request LATERAL aggregate over
-- vendor_request_items so a request with zero items still returns a row
-- (COALESCE to 0) instead of being dropped by an inner join.
SELECT
    vr.id,
    vr.request_number,
    vr.forecast_date,
    vr.status,
    vr.notes,
    vr.created_at,
    vr.submitted_at,
    vr.approved_at,
    vr.rejected_at,
    vr.is_canceled,
    vr.request_category,
    vr.replenish_date,
    vr.is_manual,
    vr.cancellation_reason,
    cu.id AS created_by_id,
    cu.full_name AS created_by_name,
    au.id AS approved_by_id,
    au.full_name AS approved_by_name,
    COALESCE(items.item_count, 0)::bigint AS item_count,
    COALESCE(items.total_amount, 0)::bigint AS total_amount
FROM vendor_requests vr
JOIN users cu ON cu.id = vr.created_by
LEFT JOIN users au ON au.id = vr.approved_by
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS item_count, SUM(vri.amount_replenish) AS total_amount
    FROM vendor_request_items vri
    WHERE vri.vendor_request_id = vr.id
) items ON true
WHERE
    (sqlc.arg('status')::text = '' OR vr.status = ANY(string_to_array(sqlc.arg('status')::text, ',')))
    AND (sqlc.arg('forecast_date')::text = '' OR vr.forecast_date = sqlc.arg('forecast_date')::date)
    AND (sqlc.arg('created_by')::bigint = 0 OR vr.created_by = sqlc.arg('created_by')::bigint)
    AND (sqlc.arg('request_number')::text = '' OR vr.request_number ILIKE '%' || sqlc.arg('request_number')::text || '%')
    AND (sqlc.arg('include_canceled')::boolean = true OR vr.is_canceled = false)
ORDER BY vr.created_at DESC, vr.id DESC
LIMIT sqlc.arg('page_size')::int OFFSET (sqlc.arg('page')::int - 1) * sqlc.arg('page_size')::int;

-- name: CountVendorRequests :one
-- Mirrors ListVendorRequests' WHERE exactly (minus joins that don't affect
-- row count, ORDER BY/LIMIT/OFFSET) so the count matches the filtered result.
SELECT COUNT(*)
FROM vendor_requests vr
WHERE
    (sqlc.arg('status')::text = '' OR vr.status = ANY(string_to_array(sqlc.arg('status')::text, ',')))
    AND (sqlc.arg('forecast_date')::text = '' OR vr.forecast_date = sqlc.arg('forecast_date')::date)
    AND (sqlc.arg('created_by')::bigint = 0 OR vr.created_by = sqlc.arg('created_by')::bigint)
    AND (sqlc.arg('request_number')::text = '' OR vr.request_number ILIKE '%' || sqlc.arg('request_number')::text || '%')
    AND (sqlc.arg('include_canceled')::boolean = true OR vr.is_canceled = false);

-- name: SoftCancelVendorRequest :one
-- Soft-cancel (Req 5): sets status='cancelled' AND is_canceled=true in one
-- statement so old readers keying on status and new readers keying on
-- is_canceled agree; row/items are never deleted. Distinct from
-- UpdateVendorRequestStatus so that query's CASE-driven timestamp columns
-- stay untouched by cancel. cancellation_reason (replenishment-request-
-- enhancements Req 3.2/3.3/3.11, migration 038) is always set here -- Cancel
-- validates it non-empty before calling this query.
UPDATE vendor_requests
SET status = 'cancelled', is_canceled = true, cancellation_reason = sqlc.arg('cancellation_reason')::text
WHERE id = sqlc.arg('id')::bigint
RETURNING *;

-- name: ListForecastForDate :many
-- Forecast Browser source (Req 3): dmaa_atm_forecast rows for one
-- periode_pred, optional terminal_id partial match, default sort terminal_id
-- ascending (Req 3.2). Extended with ATM/vendor context (Req 3.1): Lokasi ATM,
-- Brand, FLM Vendor, FLM Vendor Region, resolved via the ATM's single active
-- vendor package as of the forecast date (Req 3.2 — the LATERAL picks at most
-- one row so it cannot multiply forecast rows). All master-data joins are
-- LEFT JOIN so a missing atms/locations/vendor match never drops a
-- recommendation row (Req 3.3, 3.4). flm_vendor_region is vendor_branches.region
-- (migration 030), NOT regions.region (that is the ATM's geographic area) —
-- see .kiro/specs/update-cit-forecast-browser/design.md "Data model" note.
-- CIT-2 (Req 1): adds brand/flm_vendor/flm_vendor_region filters, exact
-- case-insensitive match via LOWER(...) = LOWER(...) (not ILIKE substring,
-- unlike terminal_id) against the already-joined a.brand/v.name/vb.region.
-- Empty-string sentinel = "no filter" for all three, matching the existing
-- terminal_id convention; the service requires a concrete flm_vendor/
-- flm_vendor_region before calling this (Req 1.4), so the SQL layer never
-- actually receives empty for those two in practice.
-- replenishment-request-enhancements (Req 5): three additive SELECT columns
-- -- priority_class (atms.priority_class, migration 030; Req 5.2), paket
-- (vendor_packages.code of the single active package, now deterministic with
-- the avp.id DESC tie-breaker -- OQ3; Req 5.3, 5.4), and escrow (latest
-- itm_replenish.escrow per terminal, numeric(20,2) the service carries as a
-- decimal string, never float -- OQ2; Req 5.5, 5.10). WHERE/ORDER BY/
-- pagination untouched so row count and the (terminal_id, periode_pred,
-- denom) identity are unchanged (Req 5.12); CountForecastForDate stays as-is
-- because every LATERAL is LIMIT 1 and cannot change the count.
-- paket is selected via the pkg LEFT JOIN (same outer-join pattern as vb)
-- rather than straight out of the active_pkg LATERAL: sqlc v1.31.1 does not
-- infer nullability on directly-scanned LATERAL subquery columns (it would
-- emit a non-nullable string that crashes pgx scan on the no-active-package
-- NULL -- Req 5.4/5.8 requires that case to render "-"), while a real-table
-- LEFT JOIN yields the nullable *string the service maps via notesOrEmpty.
SELECT f.terminal_id, f.periode_pred, f.denom, f.amount_replenish, f.amount_refund, f.dmaa_file_id,
       l.name    AS lokasi_atm,
       a.brand   AS brand,
       v.name    AS flm_vendor,
       vb.region AS flm_vendor_region,
       a.priority_class AS priority_class,
       pkg.code         AS paket,
       esc.escrow        AS escrow
FROM dmaa_atm_forecast f
LEFT JOIN atms a ON a.terminal_id = f.terminal_id
LEFT JOIN locations l ON l.id = a.location_id
LEFT JOIN LATERAL (
    SELECT vp.vendor_branch_id, vp.id AS vendor_package_id
    FROM atm_vendor_packages avp
    JOIN vendor_packages vp ON vp.id = avp.vendor_package_id
    WHERE avp.atm_id = a.id
      AND avp.is_active = true
      AND avp.effective_start_date <= sqlc.arg('forecast_date')::date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= sqlc.arg('forecast_date')::date)
    ORDER BY avp.effective_start_date DESC, avp.id DESC
    LIMIT 1
) active_pkg ON true
LEFT JOIN vendor_packages pkg ON pkg.id = active_pkg.vendor_package_id
LEFT JOIN vendor_branches vb ON vb.id = active_pkg.vendor_branch_id
LEFT JOIN vendors v ON v.id = vb.vendor_id
LEFT JOIN LATERAL (
    SELECT cp.escrow
    FROM itm_replenish cp
    WHERE cp.terminal_id = f.terminal_id
    ORDER BY cp.replenish_date DESC, cp.replenish_time DESC
    LIMIT 1
) esc ON true
WHERE f.periode_pred = sqlc.arg('forecast_date')::date
  AND (sqlc.arg('terminal_id')::text = '' OR f.terminal_id ILIKE '%' || sqlc.arg('terminal_id')::text || '%')
  AND (sqlc.arg('brand')::text = '' OR LOWER(a.brand) = LOWER(sqlc.arg('brand')::text))
  AND (sqlc.arg('flm_vendor')::text = '' OR LOWER(v.name) = LOWER(sqlc.arg('flm_vendor')::text))
  AND (sqlc.arg('flm_vendor_region')::text = '' OR LOWER(vb.region) = LOWER(sqlc.arg('flm_vendor_region')::text))
ORDER BY f.terminal_id ASC
LIMIT sqlc.arg('page_size')::int OFFSET (sqlc.arg('page')::int - 1) * sqlc.arg('page_size')::int;

-- name: CountForecastForDate :one
-- Mirrors ListForecastForDate's WHERE for pagination total. CIT-2 (Req 1):
-- unlike the pre-CIT-2 version, this now NEEDS the same
-- atms -> atm_vendor_packages (active) -> vendor_packages -> vendor_branches
-- -> vendors join chain as ListForecastForDate, because brand/flm_vendor/
-- flm_vendor_region filter on those joined columns. The LATERAL active-package
-- resolution still yields at most one row per forecast row, so the joins
-- still never change the row count for an unfiltered browse.
SELECT COUNT(*)
FROM dmaa_atm_forecast f
LEFT JOIN atms a ON a.terminal_id = f.terminal_id
LEFT JOIN LATERAL (
    SELECT vp.vendor_branch_id
    FROM atm_vendor_packages avp
    JOIN vendor_packages vp ON vp.id = avp.vendor_package_id
    WHERE avp.atm_id = a.id
      AND avp.is_active = true
      AND avp.effective_start_date <= sqlc.arg('forecast_date')::date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= sqlc.arg('forecast_date')::date)
    ORDER BY avp.effective_start_date DESC
    LIMIT 1
) active_pkg ON true
LEFT JOIN vendor_branches vb ON vb.id = active_pkg.vendor_branch_id
LEFT JOIN vendors v ON v.id = vb.vendor_id
WHERE f.periode_pred = sqlc.arg('forecast_date')::date
  AND (sqlc.arg('terminal_id')::text = '' OR f.terminal_id ILIKE '%' || sqlc.arg('terminal_id')::text || '%')
  AND (sqlc.arg('brand')::text = '' OR LOWER(a.brand) = LOWER(sqlc.arg('brand')::text))
  AND (sqlc.arg('flm_vendor')::text = '' OR LOWER(v.name) = LOWER(sqlc.arg('flm_vendor')::text))
  AND (sqlc.arg('flm_vendor_region')::text = '' OR LOWER(vb.region) = LOWER(sqlc.arg('flm_vendor_region')::text));

-- name: NextRequestNumberSeq :one
-- Atomic per-(vendor, replenish_date) increment backing the new
-- REP-<prefix>-<YYYYMMDD>-<seq> request-number format (Req 4, Q3). The
-- INSERT ... ON CONFLICT DO UPDATE ... RETURNING is a single atomic
-- statement: concurrent creates in the same (vendor_id, seq_date) scope
-- serialize on the row lock and each gets a distinct last_seq, stronger than
-- the old MaxRequestNumberSeqForDate MAX(SUBSTRING(...)) approach it
-- replaces (which races under concurrent creates). The
-- vendor_request_number_seq_last_chk CHECK (0..999) turns exhaustion at 1000
-- into a constraint violation the service maps to ErrNumberExhausted
-- (Req 4.7).
INSERT INTO vendor_request_number_seq (vendor_id, seq_date, last_seq)
VALUES (sqlc.arg('vendor_id')::bigint, sqlc.arg('seq_date')::date, 1)
ON CONFLICT (vendor_id, seq_date)
DO UPDATE SET last_seq = vendor_request_number_seq.last_seq + 1
RETURNING last_seq;

-- name: ListActiveVendors :many
-- Backs GET /vendor-requests/vendors (CIT-2 Req 1.2, 3 Q2): populates the
-- required FLM Vendor select on the Forecast Browser and the manual-request
-- vendor select. id is needed for the manual create payload's vendor_id;
-- name is what the forecast filter and the Forecast Browser select match on.
SELECT id, name
FROM vendors
WHERE is_active = true AND deleted_at IS NULL
ORDER BY name ASC;

-- name: ListDistinctVendorBranchRegions :many
-- Backs GET /vendor-requests/vendors (CIT-2 Req 1.3): populates the required
-- FLM Vendor Region select. Distinct across all active vendor branches,
-- independent of which vendor is chosen (Req 1 does not cascade Brand/FLM
-- Vendor/FLM Vendor Region -- each is filtered independently).
SELECT DISTINCT region
FROM vendor_branches
WHERE region IS NOT NULL AND is_active = true
ORDER BY region ASC;

-- name: GetVendorForRequestNumber :one
-- Resolves vendors.code + request_prefix for the request-number generator
-- (Req 4, Q1): code feeds the deterministic fallback when request_prefix is
-- NULL. Deliberately separate from dsr.sql's GetVendorByID (a different
-- feature's narrower id/code/name lookup, filtered to active vendors only)
-- rather than widening that query's shape for an unrelated caller.
SELECT id, code, request_prefix
FROM vendors
WHERE id = sqlc.arg('id')::bigint;

-- name: GetActiveVendorForTerminal :one
-- Resolves an ATM terminal's active vendor as of a given date (Req 4, Q2
-- defence-in-depth): mirrors ListForecastForDate's active-package LATERAL
-- join chain, but for a single terminal, so the service can confirm every
-- create item actually belongs to the request's single resolved vendor_id
-- rather than trusting a possibly-stale Forecast Browser selection or a
-- manual entry against the wrong vendor's ATM. INNER JOINs (unlike
-- ListForecastForDate's LEFT JOINs) are deliberate: no resolvable active
-- vendor for the terminal is itself a mismatch here, surfaced to the caller
-- as pgx.ErrNoRows.
SELECT v.id AS vendor_id
FROM atms a
JOIN LATERAL (
    SELECT vp.vendor_branch_id
    FROM atm_vendor_packages avp
    JOIN vendor_packages vp ON vp.id = avp.vendor_package_id
    WHERE avp.atm_id = a.id
      AND avp.is_active = true
      AND avp.effective_start_date <= sqlc.arg('as_of_date')::date
      AND (avp.effective_end_date IS NULL OR avp.effective_end_date >= sqlc.arg('as_of_date')::date)
    ORDER BY avp.effective_start_date DESC
    LIMIT 1
) active_pkg ON true
JOIN vendor_branches vb ON vb.id = active_pkg.vendor_branch_id
JOIN vendors v ON v.id = vb.vendor_id
WHERE a.terminal_id = sqlc.arg('terminal_id')::text;

-- name: ForecastRowExists :one
-- Validates one (terminal_id, periode_pred, denom) tuple from a create/
-- update-items payload against dmaa_atm_forecast (Req 4.4, 4.5, 8.6), and
-- returns its amount_refund so the service can copy it onto the inserted
-- item (see InsertVendorRequestItem) without a second lookup.
-- Per-tuple rather than a set-based check across the whole payload: sqlc
-- v1.31.1's built-in catalog (no live-DB engine configured) does not resolve
-- the 3-array parallel UNNEST(...) form needed for a single set-based query.
-- The service loops over items (payloads are capped at 1000, Req 8.1) and
-- calls this once per item inside the same transaction; pgx.ErrNoRows means
-- the item is invalid and gets named in the 400 response.
SELECT amount_replenish, amount_refund
FROM dmaa_atm_forecast
WHERE terminal_id = sqlc.arg('terminal_id')::text
  AND periode_pred = sqlc.arg('periode_pred')::date
  AND denom = sqlc.arg('denom')::int;
