-- Vendor Request (DMAA forecast -> CIT vendor replenishment order) queries.
-- Backs backend/internal/service/vendor_request.go (task 3). See
-- .kiro/specs/request-replenish-to-vendor/design.md for the state machine,
-- API contract, and correctness properties these queries support.

-- name: CreateVendorRequest :one
-- Inserts the header row in draft status. request_number is generated by the
-- service (VR-YYYYMMDD-NNNN, see MaxRequestNumberSeqForDate below) before
-- this call, inside the same transaction, so a unique-constraint violation
-- here means a concurrent insert raced the number and the service retries.
INSERT INTO vendor_requests (request_number, forecast_date, status, notes, created_by)
VALUES ($1, $2, 'draft', $3, $4)
RETURNING *;

-- name: InsertVendorRequestItem :one
-- amount_refund is not part of the client payload (Req 4.1) -- it is copied
-- from the matching dmaa_atm_forecast row (see ForecastRowsExist below) so
-- the item stays informationally consistent with the forecast it was drawn
-- from, even though amount_replenish itself may be a manual override.
INSERT INTO vendor_request_items
    (vendor_request_id, terminal_id, periode_pred, denom, amount_replenish, amount_refund)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING *;

-- name: DeleteVendorRequestItems :exec
-- Used by UpdateItems' full-replacement strategy (Req 8.2): delete all
-- existing items, then InsertVendorRequestItem the new set, in one tx.
DELETE FROM vendor_request_items WHERE vendor_request_id = $1;

-- name: GetVendorRequest :one
-- Plain read, no joins -- used where only the request's own columns are
-- needed (e.g. existence checks). See GetVendorRequestDetail for the
-- response-shaped read with creator/approver/rejecter names.
SELECT * FROM vendor_requests WHERE id = $1;

-- name: GetVendorRequestForUpdate :one
-- Row-locking read for every state transition (submit/approve/reject/revise/
-- cancel): SELECT ... FOR UPDATE serializes concurrent actions on the same
-- request so a second concurrent actor blocks until the first tx commits,
-- then sees the already-changed status and gets ErrInvalidTransition (409)
-- instead of racing past the guard.
SELECT * FROM vendor_requests WHERE id = $1 FOR UPDATE;

-- name: UpdateVendorRequestStatus :one
-- One query for every transition: sets status plus only the timestamp/actor
-- columns relevant to the target status (Req 2.9-2.11), leaving the others
-- untouched. actor_id / rejection_reason are nullable (sqlc.narg) because
-- most transitions (submit, revise, cancel) don't supply them -- the CASE
-- guards mean an unused NULL is simply never written.
UPDATE vendor_requests
SET
    status = sqlc.arg('status')::text,
    submitted_at = CASE WHEN sqlc.arg('status')::text = 'pending_approval' THEN now() ELSE submitted_at END,
    approved_at = CASE WHEN sqlc.arg('status')::text = 'approved' THEN now() ELSE approved_at END,
    approved_by = CASE WHEN sqlc.arg('status')::text = 'approved' THEN sqlc.narg('actor_id')::bigint ELSE approved_by END,
    rejected_at = CASE WHEN sqlc.arg('status')::text = 'rejected' THEN now() ELSE rejected_at END,
    rejected_by = CASE WHEN sqlc.arg('status')::text = 'rejected' THEN sqlc.narg('actor_id')::bigint ELSE rejected_by END,
    rejection_reason = CASE WHEN sqlc.arg('status')::text = 'rejected' THEN sqlc.narg('rejection_reason')::text ELSE rejection_reason END
WHERE id = sqlc.arg('id')::bigint
RETURNING *;

-- name: ListVendorRequestItems :many
SELECT * FROM vendor_request_items WHERE vendor_request_id = $1 ORDER BY id ASC;

-- name: GetVendorRequestDetail :one
-- Detail response shape (Req 9.6): header plus created_by/approved_by/
-- rejected_by full_name. created_by is always present (NOT NULL FK);
-- approved_by/rejected_by are only set once the request reaches that state,
-- hence LEFT JOIN.
SELECT
    vr.*,
    cu.full_name AS created_by_name,
    au.full_name AS approved_by_name,
    ru.full_name AS rejected_by_name
FROM vendor_requests vr
JOIN users cu ON cu.id = vr.created_by
LEFT JOIN users au ON au.id = vr.approved_by
LEFT JOIN users ru ON ru.id = vr.rejected_by
WHERE vr.id = sqlc.arg('id')::bigint;

-- name: ListVendorRequests :many
-- Paginated, filtered list (Req 9.1-9.5). Empty-string / 0 filter args mean
-- "no filter applied" (same convention as dmaa_forecast.sql / atm_portal.sql
-- -- callers always pass concrete sentinel values, never NULL). status is
-- comma-separated multi-select, matching ListATMsWithCashPos's pattern.
-- item_count/total_amount come from a per-request LATERAL aggregate over
-- vendor_request_items so a request with zero items still returns a row
-- (COALESCE to 0) instead of being dropped by an inner join.
SELECT
    vr.id,
    vr.request_number,
    vr.forecast_date,
    vr.status,
    vr.notes,
    vr.created_at,
    vr.submitted_at,
    vr.approved_at,
    vr.rejected_at,
    cu.id AS created_by_id,
    cu.full_name AS created_by_name,
    au.id AS approved_by_id,
    au.full_name AS approved_by_name,
    COALESCE(items.item_count, 0)::bigint AS item_count,
    COALESCE(items.total_amount, 0)::bigint AS total_amount
FROM vendor_requests vr
JOIN users cu ON cu.id = vr.created_by
LEFT JOIN users au ON au.id = vr.approved_by
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS item_count, SUM(vri.amount_replenish) AS total_amount
    FROM vendor_request_items vri
    WHERE vri.vendor_request_id = vr.id
) items ON true
WHERE
    (sqlc.arg('status')::text = '' OR vr.status = ANY(string_to_array(sqlc.arg('status')::text, ',')))
    AND (sqlc.arg('forecast_date')::text = '' OR vr.forecast_date = sqlc.arg('forecast_date')::date)
    AND (sqlc.arg('created_by')::bigint = 0 OR vr.created_by = sqlc.arg('created_by')::bigint)
    AND (sqlc.arg('request_number')::text = '' OR vr.request_number ILIKE '%' || sqlc.arg('request_number')::text || '%')
ORDER BY vr.created_at DESC, vr.id DESC
LIMIT sqlc.arg('page_size')::int OFFSET (sqlc.arg('page')::int - 1) * sqlc.arg('page_size')::int;

-- name: CountVendorRequests :one
-- Mirrors ListVendorRequests' WHERE exactly (minus joins that don't affect
-- row count, ORDER BY/LIMIT/OFFSET) so the count matches the filtered result.
SELECT COUNT(*)
FROM vendor_requests vr
WHERE
    (sqlc.arg('status')::text = '' OR vr.status = ANY(string_to_array(sqlc.arg('status')::text, ',')))
    AND (sqlc.arg('forecast_date')::text = '' OR vr.forecast_date = sqlc.arg('forecast_date')::date)
    AND (sqlc.arg('created_by')::bigint = 0 OR vr.created_by = sqlc.arg('created_by')::bigint)
    AND (sqlc.arg('request_number')::text = '' OR vr.request_number ILIKE '%' || sqlc.arg('request_number')::text || '%');

-- name: MaxRequestNumberSeqForDate :one
-- Next sequence number for VR-YYYYMMDD-NNNN (Req 15.1-15.2): request_number
-- already encodes forecast_date, so filtering by the forecast_date column
-- (rather than parsing the text) is enough to scope the max per date.
SELECT COALESCE(MAX(SUBSTRING(request_number FROM '\d{4}$')::int), 0)::int AS max_seq
FROM vendor_requests
WHERE forecast_date = sqlc.arg('forecast_date')::date;

-- name: ListForecastForDate :many
-- Forecast Browser source (Req 3): dmaa_atm_forecast rows for one
-- periode_pred, optional terminal_id partial match, default sort terminal_id
-- ascending (Req 3.2).
SELECT terminal_id, periode_pred, denom, amount_replenish, amount_refund, dmaa_file_id
FROM dmaa_atm_forecast
WHERE periode_pred = sqlc.arg('forecast_date')::date
  AND (sqlc.arg('terminal_id')::text = '' OR terminal_id ILIKE '%' || sqlc.arg('terminal_id')::text || '%')
ORDER BY terminal_id ASC
LIMIT sqlc.arg('page_size')::int OFFSET (sqlc.arg('page')::int - 1) * sqlc.arg('page_size')::int;

-- name: CountForecastForDate :one
-- Mirrors ListForecastForDate's WHERE for pagination total.
SELECT COUNT(*)
FROM dmaa_atm_forecast
WHERE periode_pred = sqlc.arg('forecast_date')::date
  AND (sqlc.arg('terminal_id')::text = '' OR terminal_id ILIKE '%' || sqlc.arg('terminal_id')::text || '%');

-- name: ForecastRowExists :one
-- Validates one (terminal_id, periode_pred, denom) tuple from a create/
-- update-items payload against dmaa_atm_forecast (Req 4.4, 4.5, 8.6), and
-- returns its amount_refund so the service can copy it onto the inserted
-- item (see InsertVendorRequestItem) without a second lookup.
-- Per-tuple rather than a set-based check across the whole payload: sqlc
-- v1.31.1's built-in catalog (no live-DB engine configured) does not resolve
-- the 3-array parallel UNNEST(...) form needed for a single set-based query.
-- The service loops over items (payloads are capped at 1000, Req 8.1) and
-- calls this once per item inside the same transaction; pgx.ErrNoRows means
-- the item is invalid and gets named in the 400 response.
SELECT amount_replenish, amount_refund
FROM dmaa_atm_forecast
WHERE terminal_id = sqlc.arg('terminal_id')::text
  AND periode_pred = sqlc.arg('periode_pred')::date
  AND denom = sqlc.arg('denom')::int;
